### ISSUE TITLE
Dag processor error: Connection doesn't have a host url

### ISSUE THREAD

**Issue by dramis** [apache/airflow#56165]
### Apache Airflow Provider(s)

git

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==9.14.0
apache-airflow-providers-common-compat==1.7.4
apache-airflow-providers-common-io==1.6.3
apache-airflow-providers-common-sql==1.28.1
apache-airflow-providers-elasticsearch==6.3.3
apache-airflow-providers-fab==2.4.3
apache-airflow-providers-git==0.0.8
apache-airflow-providers-http==5.3.4
apache-airflow-providers-postgres==6.3.0
apache-airflow-providers-samba==4.11.0
apache-airflow-providers-smtp==2.3.0
apache-airflow-providers-ssh==4.1.4
apache-airflow-providers-standard==1.8.0

### Apache Airflow version

3.1.0

### Operating System

Debian 12.12

### Deployment

Virtualenv installation

### What happened

After upgrading to Airflow **3.1.0** and the Git provider **0.8.0**, I started seeing errors in the logs when DAG bundles are refreshed.

The error message is:

```
Sep 27 07:37:21 fondor airflow[1695637]: Traceback (most recent call last):
  File "/opt/airflow/venv/lib/python3.11/site-packages/airflow/dag_processing/manager.py", line 508, in _refresh_dag_bundles
    bundle.initialize()
  File "/opt/airflow/venv/lib/python3.11/site-packages/airflow/providers/git/bundles/git.py", line 112, in initialize
    raise AirflowException(f"Connection {self.git_conn_id} doesn't have a host url")
airflow.exceptions.AirflowException: Connection git_dags_bundle doesn't have a host url
Sep 27 07:37:26 fondor airflow[1695637]: [2025-09-27T11:37:26.687021Z] {manager.py:536} INFO - Not time to refresh bundle dags-folder
Sep 27 07:37:26 fondor airflow[1695637]: [2025-09-27T11:37:26.687228Z] {manager.py:510} ERROR - Error initializing bundle thehub_git_repo: Connection git_dags_bundle doesn't have a host url
```

This happens systematically after the upgrade and prevents the bundle from initializing properly.

### What you think should happen instead

The Git bundle should initialize successfully using the configured Airflow connection.

When the scheduler refreshes DAG bundles, the `git_dags_bundle` connection should be resolved properly, and the repository `thehub_git_repo` should be cloned or updated without raising an exception about a missing host URL.

In short: the bundle should load the DAGs normally after the upgrade, without errors in the logs.

### How to reproduce

Configure Airflow with the following `airflow.cfg` snippet:

```
[dag_processor]
dag_bundle_config_list = [
      {
        "name": "dags-folder",
        "classpath": "airflow.dag_processing.bundles.local.LocalDagBundle",
        "kwargs": {}
      },
      {
        "name": "thehub_git_repo",
        "classpath": "airflow.providers.git.bundles.git.GitDagBundle",
        "kwargs": {"tracking_ref": "main",
                   "subdir": "dags",
                   "git_conn_id": "git_dags_bundle"
                  }
      }
    ]
```

Then create a connection named `git_dags_bundle` in Airflow, with the **repository URL properly configured** along with authentication details.

After restarting the scheduler with this setup, the error appears in the logs.

### Anything else

This configuration was working correctly with Airflow 3.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by prdai** [comment]
hi, i would like to look into this, could i be assigned to this issue? thanks

**Comment by badf007** [comment]
Same error trying to connect a GitHub repo as a DagBundle:

Airflow version: 3.1.0
Running on the official Docker Compose file

airflow.cfg bundle config
```
dag_bundle_config_list = [
      {
        "name": "local-dags-test2",
        "classpath": "airflow.providers.git.bundles.git.GitDagBundle",
        "kwargs": {"tracking_ref": "main", "git_conn_id": "local-dags-test"}
      },
      {
        "name": "dags-folder",
        "classpath": "airflow.dag_processing.bundles.local.LocalDagBundle",
        "kwargs": {}
      }
    ]

``` 

Error Message
```
2025-09-29T19:26:31.845555Z [error    ] Error initializing bundle local-dags-test2: Connection local-dags-test doesn't have a host url [airflow.dag_processing.manager.DagFileProcessorManager] loc=manager.py:510

Traceback (most recent call last):

  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 508, in _refresh_dag_bundles

    bundle.initialize()

  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/git/bundles/git.py", line 112, in initialize

    raise AirflowException(f"Connection {self.git_conn_id} doesn't have a host url")

airflow.exceptions.AirflowException: Connection local-dags-test doesn't have a host url
``` 

Connection config:

<img width="940" height="852" alt="Image" src="https://github.com/user-attachments/assets/b751d080-784a-4de4-86b2-d0795c6d4486" />

**Comment by maxcotec** [comment]
Happened with me , and I've been banging my head for 2 days, and finally got around with it. 
I am using Airflow v3.0.4. And when i tried deploying on prod, which was using old fernet-key (which was supported by airflow v2.10.4, Airflow 3 wasn't happy with the old key. I had to provide correct fernet-key. 

```
from airflow.sdk import Connection as TaskSDKConnection
conn = TaskSDKConnection.get(conn_id=<YOUR_CONN_NAME_HERE>)
```
the above code threw error about fernet-key. Hope this may help someone.

**Comment by srchunter** [comment]
I also had this problem after upgrading from 3.0.4 to 3.1.0
I could fix it by setting `repo_url` in the `kwargs` in `airflow.cfg` directly. It seems like due to the changes in the Git provider the GitHook can not grab the repo_url correctly

**Comment by adrian-edbert** [comment]
Tried to check on this one  
got the same issue and saw this warning, both on 0.0.7 and 0.0.8 providers

> WARNING - Could not create GitHook bundle_name=data_platform_test_migration_dag version=None bare_repo_path=PosixPath('/tmp/airflow/dag_bundles/data_platform_test_migration_dag/bare') repo_path=PosixPath('/tmp/airflow/dag_bundles/data_platform_test_migration_dag/tracking_repo') versions_path=PosixPath('/tmp/airflow/dag_bundles/data_platform_test_migration_dag/versions') git_conn_id=git_data_platform conn_id=git_data_platform exc=ImportError("cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)")


The reason I think is because the Githook object is failing to be created on the bundle caused by SUPERVISOR_COMMS failure to import  

possibly related with some other similar issue https://github.com/apache/airflow/issues/56120 https://github.com/apache/airflow/issues/51816 https://github.com/apache/airflow/issues/48554

**Comment by adrian-edbert** [comment]
I also got this debug message as well, which indicate that the connection can't be found on any secret backends  

> [2025-10-02T09:54:51.797357Z] {context.py:169} DEBUG - Connection not found in any of the configured Secrets Backends. Trying to retrieve from API server conn_id=git_data_platform

checked through the DB and UI confirmed that the connection should exist  
and the secrets backend also using the default ones  
using API to get the connection works as expected  

not sure what causing the connection issue for now


setting repo_url directly on the airflow.cfg seems to be the only workaround but it can't use the git auth url for authentication without the Githook object

**Comment by adrian-edbert** [comment]
oh the root cause seems because the git provider version_compat  
providers/git/src/airflow/providers/git/version_compat.py  

is using sdk basehook object, which eventually will load secrets backend from airflow-core/src/airflow/secrets/__init__.py
but only by `DEFAULT_SECRETS_SEARCH_PATH_WORKERS`

this load git providers without the metastore secret backend, causing the githook get_connection to fails  

I'm unsure if this is expected, perhaps due to the AIP-72 progress  

I can workaround the issue by explicitly adding  
```
[secrets]
backend = airflow.secrets.metastore.MetastoreBackend
```
on the airflow.cfg  
though this might be anti pattern due to the AIP

**Comment by irakl1s** [comment]
> oh the root cause seems because the git provider version_compat providers/git/src/airflow/providers/git/version_compat.py
> 
> is using sdk basehook object, which eventually will load secrets backend from airflow-core/src/airflow/secrets/**init**.py but only by `DEFAULT_SECRETS_SEARCH_PATH_WORKERS`
> 
> this load git providers without the metastore secret backend, causing the githook get_connection to fails
> 
> I'm unsure if this is expected, perhaps due to the AIP-72 progress
> 
> I can workaround the issue by explicitly adding
> 
> ```
> [secrets]
> backend = airflow.secrets.metastore.MetastoreBackend
> ```
> 
> on the airflow.cfg though this might be anti pattern due to the AIP

This also fixed the issue for me, thanks.
I guess it’s not an ideal solution, but it does confirm the problem with the git provider.

**Comment by adrian-edbert** [comment]
> oh the root cause seems because the git provider version_compat providers/git/src/airflow/providers/git/version_compat.py
> 
> is using sdk basehook object, which eventually will load secrets backend from airflow-core/src/airflow/secrets/**init**.py but only by `DEFAULT_SECRETS_SEARCH_PATH_WORKERS`
> 
> this load git providers without the metastore secret backend, causing the githook get_connection to fails
> 
> I'm unsure if this is expected, perhaps due to the AIP-72 progress
> 
> I can workaround the issue by explicitly adding
> 
> ```
> [secrets]
> backend = airflow.secrets.metastore.MetastoreBackend
> ```
> 
> on the airflow.cfg though this might be anti pattern due to the AIP

I'm sorry, this workaround seems to have an unexpected consequences, since the secrets backend running session.expunge_all() and this is being called every time the git dag bundle is initialized, and it seems the session context is shared between airflow components  

during dag processing import_errors, on `airflow-core/src/airflow/dag_processing/collection.py`, there's a part where it called `import_error.full_file_path()` after session.add() and before session.flush(), this will call the git dag bundle init -> secrets metastore backend, causing the import_errors update / insert not flushed to db and not shown in the UI (since it got expunged by secrets metastore backend)

so for now instead of using the web ui to configure the connection we decided to just use the env secret backend and deploy it along the server and worker env variable
https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#environment-variables-connections

**Comment by gopidesupavan** [comment]
can anyone of you test on latest 3.1.1rc2 please ? is it still happening please update.

**Comment by adrian-edbert** [comment]
> can anyone of you test on latest 3.1.1rc2 please ? is it still happening please update.

Can confirm working on my local docker env, thanks for the fix. may I know which PR supposed to fix the issue?

**Comment by gopidesupavan** [comment]
> > can anyone of you test on latest 3.1.1rc2 please ? is it still happening please update.
> 
> Can confirm working on my local docker env, thanks for the fix. may I know which PR supposed to fix the issue?

https://github.com/apache/airflow/pull/56602

**Comment by gopidesupavan** [comment]
https://github.com/apache/airflow/pull/56602
