### ISSUE TITLE
Add conf not importable from airflow rule

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#13945]
**Description**

A new rule should be added to Airflow upgrade check to verify that users import `conf` from proper place and their code will work with 2.0.

**Use case / motivation**

In 1.10 users can do:

```py
In [1]: from airflow import conf

In [2]: conf
Out[2]: <airflow.configuration.AirflowConfigParser at 0x7f6f28650f28>
```
in 2.0 it's not possible:
```py
In [1]: from airflow import conf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2cf28b1802b4> in <module>
----> 1 from airflow import conf

ImportError: cannot import name 'conf'
```

**Are you willing to submit a PR?**

Possibly if time allows 🕐 

**Related Issues**

N/A

**Comment by griffincosgrove** [comment]
Hey @turbaszek, I am interested in making a PR for this. 

I see you tagged this with good first issue. I am still a novice when it comes to airflow, so if you could help me with the review I think we can accomplish this together.

**Comment by griffincosgrove** [comment]
hey @turbaszek, struggling to get started with this PR. Could you elaborate more on "Airflow upgrade check", not sure about the implementation strategy at the moment?

**Comment by turbaszek** [comment]
> Could you elaborate more on "Airflow upgrade check", not sure about the implementation strategy at the moment?

@griffincosgrove upgrade check is additional package that can be installed next to Airflow 1.10.X and allows users check if they are ready to upgrade to Airflow 2.0:
https://github.com/apache/airflow/tree/v1-10-stable/airflow/upgrade

As you can see solving this issue requires to open a PR to `v1-10-stable` branch not `master`. What we need is a new rule that will check that users do not use `from airflow import conf`. Here are existing rules for reference:
https://github.com/apache/airflow/tree/v1-10-stable/airflow/upgrade/rules

**Comment by digitalsimboja** [comment]
Hi @turbaszek is @griffincosgrove working on this issue already, if not I will like to take it up. I am new to Airflow as well and looking for a good-first-issue to taken on. Could this be assigned to me if @griffincosgrove is occupied at the moment. Thanks

**Comment by turbaszek** [comment]
@digitalsimboja you can work on as @griffincosgrove seems to be inactive for last few days

**Comment by griffincosgrove** [comment]
Had trouble with this one. Good luck @digitalsimboja!

**Comment by digitalsimboja** [comment]
@turbaszek  Thanks I am taking it on already. Do I need to install anything in order to access the file. I have looking through the repo I have but yet to locate the file at **apache/airflow/tree/v1-10-stable/airflow/upgrade**. Need to mention that I run Airflow on WSL.

**Comment by turbaszek** [comment]
@digitalsimboja you need to checkout to `v1-10-stable` branch, then you should have the `upgrade` directory.

**Comment by eladkal** [comment]
@turbaszek @digitalsimboja this is solved by https://github.com/apache/airflow/pull/14400 correct?

**Comment by digitalsimboja** [comment]
Yes,

That is correct.

Regards
