### PR TITLE
Add compat layer for import errors caused by `AirflowSecretsBackendAccessDenied`

### PR DESCRIPTION
**Pull request by amoghrajesh**
---

##### Was generative AI tooling used to co-author this PR?

- [ ] Yes (please specify the tool below)

caused by #66575

`AirflowSecretsBackendAccessDenied` was added to task sdk in 1.2.2. Tests running with Airflow 3.2.2+ with `apache-airflow-task-sdk==1.2.1` installed hit an ImportError at startup:

```
ImportError: cannot import name 'AirflowSecretsBackendAccessDenied' from 'airflow.sdk.exceptions'
```

**Current behaviour**
Any environment with apache-airflow-core>=3.2.2 and apache-airflow-task-sdk==1.2.1 is completely broken at import time.

**Proposed change**
Wrap the import in a `try/except` for import error in both `connection.py` and `variable.py`. The fallback defines a stub `PermissionError` subclass that is never raised by task-sdk 1.2.1, so the `except AirflowSecretsBackendAccessDenied` clauses in those files simply never fire — behaviour is identical to pre-1.2.2 task-sdk.

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

**Review by rawwar — APPROVED** [review]

**Comment by potiuk** [comment]
Do we need that? We should have `==` relation between airflow core and task-sdk - to avoid those kind of errors

**Comment by amoghrajesh** [comment]
We already have that, installing in same process / container is an issue like compat tests.

Isolated processes work fine

**Review by kaxil — APPROVED** [review]
