### PR TITLE
Add chain_linear, cross_downstream imports to deprecated classes in models baseoperator

### LINKED ISSUE #53916: ImportError: cannot import name 'cross_downstream' from 'airflow.models.baseoperator' (unknown location)
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

from airflow.models.baseoperator import cross_downstream, chain"
Above import statement is throwing import error: 
ImportError: cannot import name 'cross_downstream' from 'airflow.models.baseoperator' (unknown location)

Image

**Note: This dag was working in 3.0.3**

### What you think should happen instead?

_No response_

### How to reproduce

Have a below dag in dags folder and notice the import error:

```python
from airflow.utils.task_group import TaskGroup
from airflow.utils.edgemodifier import Label
from airflow.models.baseoperator import cross_downstream, chain
from airflow.decorators import dag, task, task_group
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.sdk import DAG
from airflow.utils.dot_renderer import render_dag
from textwrap import indent

from datetime import datetime, timedelta

two_days = datetime.now() - timedelta(days=2)

default_args = {
    'owner':'airflow',
    'depends_on_past': True
}

with DAG(
    dag_id="cross_downstream_group_compare2",
    schedule=None,
    start_date=two_days,
    default_args=default_args,
    tags=['core'],
) as dag:
    
    with TaskGroup(group_id="group1") as tg1:
        t1 = EmptyOperator(task_id="dummy1")
        t2 = EmptyOperator(task_id="dummy2")
        t3 = EmptyOperator(task_id="dummy3")
        t4 = EmptyOperator(task_id="dummy4")
        t5 = EmptyOperator(task_id="dummy5")
        t6 = EmptyOperator(task_id="dummy6")
        t7 = EmptyOperator(task_id="dummy7")
        @task
        def dummy0():
            return 0
        d0 = dummy0()
        cross_downstream(from_tasks=[d0, t1, t2, t3], to_tasks=[t4, t5, t6, t7])

    with TaskGroup(group_id="group2") as tg2:
        t1 = EmptyOperator(task_id="dummy1")
        t2 = EmptyOperator(task_id="dummy2")
        t3 = EmptyOperator(task_id="dummy3")
        t4 = EmptyOperator(task_id="dummy4")
        t5 = EmptyOperator(task_id="dummy5")
        t6 = EmptyOperator(task_id="dummy6")
        t7 = EmptyOperator(task_id="dummy7")
        @task
        def dummy0():
            return 0

        d0 = dummy0()
        """
        d0.set_downstream(t5)
        d0.set_downstream(t6)
        d0.set_downstream(t7)
        t1.set_downstream(t5)
        t1.set_downstream(t6)
        t1.set_downstream(t7)
        t2.set_downstream(t5)
        t2.set_downstream(t6)
        t2.set_downstream(t7)
        t3.set_downstream(t5)
        t3.set_downstream(t6)
        t3.set_downstream(t7)
        t4.set_downstream(t5)
        t4.set_downstream(t6)
        t4.set_downstream(t7)
        """
        chain(d0, [t4, t5, t6, t7])
        chain(t1, [t4, t5, t6, t7])
        chain(t2, [t4, t5, t6, t7])
        chain(t3, [t4, t5, t6, t7])


chain([tg1, tg2])
``` 

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by gopidesupavan**
closes https://github.com/apache/airflow/issues/53916

image

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Review by amoghrajesh — APPROVED** [review]

**Comment by gopidesupavan** [comment]
Looks like all these are not backported , do we need to backport?

```
__deprecated_classes = {
    "abstractoperator": {
        "AbstractOperator": "airflow.sdk.definitions._internal.abstractoperator.AbstractOperator",
        "NotMapped": "airflow.sdk.definitions._internal.abstractoperator.NotMapped",
        "TaskStateChangeCallback": "airflow.sdk.definitions._internal.abstractoperator.TaskStateChangeCallback",
        "DEFAULT_OWNER": "airflow.sdk.definitions._internal.abstractoperator.DEFAULT_OWNER",
        "DEFAULT_QUEUE": "airflow.sdk.definitions._internal.abstractoperator.DEFAULT_QUEUE",
        "DEFAULT_TASK_EXECUTION_TIMEOUT": "airflow.sdk.definitions._internal.abstractoperator.DEFAULT_TASK_EXECUTION_TIMEOUT",
    },
    "param": {
        "Param": "airflow.sdk.definitions.param.Param",
        "ParamsDict": "airflow.sdk.definitions.param.ParamsDict",
    },
    "baseoperator": {
        "BaseOperator": "airflow.sdk.bases.operator.BaseOperator",
        "chain": "airflow.sdk.bases.operator.chain",
    },
    "baseoperatorlink": {
        "BaseOperatorLink": "airflow.sdk.bases.operatorlink.BaseOperatorLink",
    },
    "operator": {
        "BaseOperator": "airflow.sdk.bases.operator.BaseOperator",
        "Operator": "airflow.sdk.types.Operator",
    },
}
```

**Comment by gopidesupavan** [comment]
Not backporting this to v3-0-test, as its working and none previous deprecated rules backported
