### PR TITLE
Feature: fixed task-sdk SUPPERVISOR_COMMS import error

### LINKED ISSUE #48554: [CLI command only] Importing `Variable` from `airflow.sdk` causes an `ImportError: cannot import name 'SUPERVISOR_COMMS'` for top-level Variable when running `airflow dags reserialize`
EDIT: this only affects the CLI command `airflow dags reserialize`, the dag-processor handles the dag fine and it runs correctly.

### Apache Airflow version

3.0.0

### If "Other Airflow 2 version" selected, which one?

main

### What happened?

This dag serializes and runs fine for `from airflow.models import Variable` but not for `from airflow.sdk import Variable`

```
from airflow.sdk import dag, Variable
from airflow.decorators import task 
# from airflow.models import Variable

# This one only works for imports from airflow.models, not from airflow.sdk
var1 = Variable.get("v1", "TOP_LEVEL_VAR")

@dag()
def test_var():

    @task 
    def get_var():
        print("TOP LEVEL VAR ", var1)

        # this one works for both imports, from airflow.sdk and from airflow.models
        var2 = Variable.get("v2", "TASK_LEVEL_VAR")
        print("TASK LEVEL VAR ", var2)
    
    get_var() 


test_var()
```

The error is only caused when the Variable is used at the top level of the dag, not when within a task. 

Error:

```
Traceback (most recent call last):
  File "/opt/airflow/task-sdk/src/airflow/sdk/definitions/variable.py", line 53, in get
    return _get_variable(key, deserialize_json=deserialize_json)
  File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/context.py", line 185, in _get_variable
    from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py)
```

### What you think should happen instead?

The dag should serialize and run with the updated import.

### How to reproduce

Add the above dag to your env, run airflow dags reserialize, see the error. Switch the import of Variable to `airflow.models` to see the dag work.

### Operating System

MacOS

### Versions of Apache Airflow Providers

None

### Deployment

Other

### Deployment details

breeze

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### LINKED ISSUE #51062: Metastore not available from external_python task
Hi, i have decided to create a new issue, however, I think it relates to #48554.
I get the following error in v3.0.1 when trying to retrieve variables from the metastore within an external python environment `ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner'`.

Retrieving the same variable within the same DAG but using an ordinary task, works just fine. I'm therefore let to believe that this is caused by accessing the metastore from an external environment. The variable shows when executing the `airflow variables list` command from an python environment activated terminal. In my opinion, the latter suggests, that the virtual environment should be properly set up.

Retrieving variables from the metastor within external python environments worked fine for me in v2.10.5 (however using `from airflow.models import Variable` instead of `from airflow.sdk import Variable`)

I cannot retrieve connections stored in the metastore from an external environment either. However, I do not know if this is caused by the same root problem.

My original post can be found beneath .

> I seem to get this error in 3.0.1 as well when using `Variable.get("my_variable")` inside an external_python task. The variable is perfectly able to be retrieved from an ordinary task. The variable is also listed when executing the `airflow variables list` command from an python environment activated terminal. The latter suggests, that the virtual environment should be properly set up, in my opinion. This setup worked fine in airflow 2.10.5 (however using `from airflow.models import Variable` instead of `from airflow.sdk import Variable`)
> 
> I don't know if the cause of this issue is the same, but sounds similar to me. 

 _Originally posted by @fromm1990 in [#48554](https://github.com/apache/airflow/issues/48554#issuecomment-2903910966)_

### LINKED ISSUE #51816: ImportError: cannot import name 'SUPERVISOR_COMMS' with dag.test()
### Apache Airflow version

3.0.2

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

The exception occurred when the DAG ran with `dag.test()` attempted to retrieve a variable from the API server. Some similar issues have been opened (#48554, #51062, #51316). The PRs provided as a solution (#50300, #50419) were included in 3.0.2 but did not fix the problem.

```
Exception has occurred: ImportError
cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/workspaces/airflow/.venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)
  File "/workspaces/airflow/test.py", line 7, in <module>
    x = Variable.get("my_variable")
        ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/workspaces/airflow/.venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)
```

### What you think should happen instead?

The variable should have been successfully retrieved without exceptions.

### How to reproduce

1. Set the variable: `airflow variables set my_variable my_value`
2. Run DAG:
```
import logging

from airflow import DAG
from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.providers.standard.operators.python import PythonOperator
from airflow.sdk import Variable

x = Variable.get("my_variable")

def my_function(my_var: str) -> None:
    logging.getLogger(__name__).info(my_var)

with DAG("test_dag") as dag:

    start = EmptyOperator(task_id="start")

    py_func = PythonOperator(
        task_id="py_func",
        python_callable=my_function,
        op_kwargs={
            "my_var": x
        }
    )

    end = EmptyOperator(task_id="end")

    start >> py_func >> end

if __name__ == "__main__":
    dag.test()
```

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other Docker-based deployment

### Deployment details

Extended image based on `apache/airflow:slim-3.0.2-python3.12`

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Nataneljpwd**
---

This PR fixes issues #51062, #48554 and #51816 by adjusting the logic a little to work as intended, even if called outside the task sdk
Closes: #51062 
Closes: #48554 
Closes: #51816

### CODE REVIEW

File: task-sdk/src/airflow/sdk/execution_time/context.py [hunk 1]
```diff
@@ -200,6 +200,17 @@ def _get_variable(key: str, deserialize_json: bool) -> Any:
     from airflow.sdk.execution_time.comms import ErrorResponse, GetVariable
     from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
 
+    if SUPERVISOR_COMMS is None:
+        # if this happens, that means that we are not in task_runner scope and most likely are in the
+        # dag parser scope, which means that SUPERVISOR_COMMS won't work as it connects to a socket on the
```
Comment (ashb) [inline task-sdk/src/airflow/sdk/execution_time/context.py]: This comment isn't true -- even inside the Dag parsing context there is a supervisor comms socket available.

File: task-sdk/src/airflow/sdk/execution_time/context.py [hunk 2]
```diff
@@ -200,6 +200,17 @@ def _get_variable(key: str, deserialize_json: bool) -> Any:
...
+        # task_runner, and hence we throw the notfound error, during runtime, the variable might work
+        raise AirflowRuntimeError(
+            ErrorResponse(
+                error=ErrorType.VARIABLE_NOT_FOUND,
+                detail={"message": "Variable not found in any airflow backend"},
+            )
+        )
```
Comment (ashb) [inline task-sdk/src/airflow/sdk/execution_time/context.py]: This message isn't true -- we didn't actually check anything.

**Review by ashb — CHANGES_REQUESTED** [review]
a) I'm not at all conviced this does anything other than paper over the crack.
b) at the very least it needs unit tests to show that the fix is working.

**Comment by ashb** [comment]
Does this actually let you get at variables at parse time? If not then it doesn't fix anything.

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 1 above)
Comment (Nataneljpwd) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: the supervisor_comms is not available from the context of the dagparser, even if I create it, it does not connect to the socket and does not create it, it gets an issue of a non-socket operation called.

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 2 above)
Comment (Nataneljpwd) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: we did, it is done in lines 170 to 193, we try to get variable from each backend

**Comment by Nataneljpwd** [comment]
this does fix the issue, I will add test to show how it fixes it, we are able to pull the variables during dag parsing, but if they are created in runtime, they will be pulled in runtime and not found during parsing.

This pr is still a draft, should have marked it as such, my bad

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 1 above)
Comment (ashb) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: That is untrue. The supervisor comms is used by the parsing process to send the parsed dag back to the supervisor. The parsing process reuses most of the process model and communication from task sdk

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 2 above)
Comment (ashb) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: Crucially: those lines do not check the database. They only check the external backend.

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 1 above)
Comment (ashb) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: (`SUPERVISOR_COMMS` might not be set up, but there is a valid socket and comms path generally)

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 2 above)
Comment (Nataneljpwd) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: Oh ok, I guess I overlooked that, I will fix it

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 1 above)
Comment (Nataneljpwd) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: When I tried initializing it, I got an error on the socket that a non socket operation was called (errno 88), is there any setup needed before initializing it? As it was not stated in any  docstring of the class

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 2 above)
Comment (ashb) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: How do you propose to fix that? the Task SDK is not allowed to access the DB directly

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 1 above)
Comment (ashb) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: https://github.com/apache/airflow/blob/584050de80f4d818acd3298539c4c532f9b7d75d/airflow-core/src/airflow/dag_processing/processor.py#L142.

Comment (ashb) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: Two of the three issues you linked to talk about cli/dag.test, which is not in a dag parser scope. Not an "official" one anyway.

**Comment by ashb** [comment]
For `dag.test`, I think the fix is to make use of the InProcessAPIServer we have elsewhere (I think triggerrer?) and then use an approach like discussed in https://github.com/apache/airflow/issues/51816#issuecomment-2980679579 to catch top-level use of variables in order to get to `dag.test` calls..

**Comment by ashb** [comment]
> This pr is still a draft, should have marked it as such, my bad

All good. Thanks for trying to tackle this one. It's important, but also quite complex and gets deep into the depths of the new architecture on Airflow 3

**Comment by Nataneljpwd** [comment]
OK, I will keep trying to tackle this problem, as there are a few observations that I made ( like the CommsSupervisor never being defined when the variable from models is used, as it is declared but not defined, and the hasattr seems to always return false, and never print the warning, I still have a few possible solutions I haven't exhausted yet, I will try them all on this PR, if I find a solution, I will comment on this PR again finalizing it.

Thank you for the valuable feedback, I think it pushed me closer to implementing a solution that solves the issue.

File: task-sdk/src/airflow/sdk/execution_time/context.py (hunk 2 above)
Comment (Nataneljpwd) [reply task-sdk/src/airflow/sdk/execution_time/context.py]: hmm, after looking at it, it looks like we need to open a socket to stdin and send the getvariable there, for IPC and get the variable, but I do not see any task that could get the command and execute it, as it seems that there are no processes that relate to airflow, is there some process which listens to stdin and executes commands? or reads it and reacts to the input? I will look into it and check, as I think that running that process (when creating a dagbag), could solve the issue as we will always have access to the socket, or if I find the process which reads the stdin and reacts, I can see what it does and do exactly what it does
