### PR TITLE
Fix celery provider ImportError on airflow 3.2.x by gating ExecutorWorkload on 3.3+

### PR DESCRIPTION
**Pull request by anishgirianish**
<!-- SPDX-License-Identifier: Apache-2.0
      https://www.apache.org/licenses/LICENSE-2.0 -->

<!--
Thank you for contributing!

Please provide above a brief description of the changes made in this pull request.
Write a good git commit message following this guide: http://chris.beams.io/posts/git-commit/

Please make sure that your code changes are covered with tests.
And in case of new features or big changes remember to adjust the documentation.

Feel free to ping (in general) for the review if you do not see reaction for a few days
(72 Hours is the minimum reaction time you can expect from volunteers) - we sometimes miss notifications.

In case of an existing issue, reference it using one of the following:

* closes: #ISSUE
* related: #ISSUE
-->

---

##### Was generative AI tooling used to co-author this PR?

<!--
If generative AI tooling has been used in the process of authoring this PR, please
change below checkbox to `[X]` followed by the name of the tool, uncomment the "Generated-by".
-->

- [ ] Yes (please specify the tool below)

<!--
Generated-by: [Tool Name] following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)
-->

celery_executor_utils.execute_workload gates the new ExecutorWorkload / BaseExecutor.run_workload path on AIRFLOW_V_3_2_PLUS, but both symbols were only added on main (3.3+). On airflow 3.2.0 every celery task fails with:                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                       
`ImportError: cannot import name 'ExecutorWorkload' from 'airflow.executors.workloads'        `                                                    
                                                                                                                                                       
Fix: add AIRFLOW_V_3_3_PLUS and move the gate (+ rename the fallback helper to _execute_workload_pre_3_3).                                                                                                             
                                          
Surfaced while verifying #65702 (celery 3.19.0rc1). Regression from #62645. 


---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

**Comment by anishgirianish** [comment]
cc: @shahar1 @ferruzzi

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I think we should add some executor tests with compatibility tests. We do not seem to test compatibility for executors in our compat tests. It's the second time when the tests were not catching something I think.

Anyone could take a look maybe?

**Review by hussein-awala — APPROVED** [review]
> I think we should add some executor tests with compatibility tests

+1
