### ISSUE TITLE
"Task Duration" and "Landing Times" stopped working in 1.5.2

### ISSUE THREAD

**Issue by storpipfugl** [apache/airflow#586]
We just upgraded from 1.5.1 to 1.5.2 and the "Task Duration" and "Landing Times"  have stopped working. They just display a gray "Loading...". The other views work fine. No errors are logged when the duration and landing views are accessed through a browser but strangly cURL'ing the same URL the airflow webserver logs:

ERROR:airflow.www.app:Exception on /admin/airflow/landing_times [GET]
...
  File "/usr/share/python/one.com-airflow/local/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, _args, *_kwargs)
  File "/usr/share/python/one.com-airflow/local/lib/python2.7/site-packages/airflow/www/app.py", line 1356, in landing_times
    dag = dagbag.get_dag(dag_id)
  File "/usr/share/python/one.com-airflow/local/lib/python2.7/site-packages/airflow/models.py", line 145, in get_dag
    filepath=orm_dag.fileloc, only_if_updated=False)
AttributeError: 'NoneType' object has no attribute 'fileloc'

Any idea what could be causing this and how to proceed debugging?

EDIT: The above stacktrace comes when curling includes the "days" field in the URL. Just hitting the landing times URL with only the "dag_id" returns a valid reponse including something like "CDATA[
new Chartkick.LineChart(document.getElementById("chart-5"), [{u'data': [['2015-10-30T05:40:00', 4.625270864166667], ['2015-10-30T06:40:00', 3.626762292777778]..." which I assume it the dataset?  So it might be a client side (dependency) problem rendering the dataset?

**Comment by storpipfugl** [comment]
The problem is actually visible in the Chartkick data show above. Notice the prepended unicode indicator "u" in u'data'.

**Comment by mistercrunch** [comment]
Should be fixed in `1.6`
