### ISSUE TITLE
ImportError: cannot import name 'cross_downstream' from 'airflow.models.baseoperator' (unknown location)

### ISSUE THREAD

**Issue by atul-astronomer** [apache/airflow#53916]
### Apache Airflow version

main (development)

### What happened?

from airflow.models.baseoperator import cross_downstream, chain"
Above import statement is throwing import error: 
ImportError: cannot import name 'cross_downstream' from 'airflow.models.baseoperator' (unknown location)

<img width="816" height="209" alt="Image" src="https://github.com/user-attachments/assets/e5489b20-4993-4bbe-9e42-17f71b38725e" />

**Note: This dag was working in 3.0.3**

### How to reproduce

Have a below dag in dags folder and notice the import error:

```python
from airflow.utils.task_group import TaskGroup
from airflow.utils.edgemodifier import Label
from airflow.models.baseoperator import cross_downstream, chain
from airflow.decorators import dag, task, task_group
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.sdk import DAG
from airflow.utils.dot_renderer import render_dag
from textwrap import indent

from datetime import datetime, timedelta

two_days = datetime.now() - timedelta(days=2)

default_args = {
    'owner':'airflow',
    'depends_on_past': True
}

with DAG(
    dag_id="cross_downstream_group_compare2",
    schedule=None,
    start_date=two_days,
    default_args=default_args,
    tags=['core'],
) as dag:
    
    with TaskGroup(group_id="group1") as tg1:
        t1 = EmptyOperator(task_id="dummy1")
        t2 = EmptyOperator(task_id="dummy2")
        t3 = EmptyOperator(task_id="dummy3")
        t4 = EmptyOperator(task_id="dummy4")
        t5 = EmptyOperator(task_id="dummy5")
        t6 = EmptyOperator(task_id="dummy6")
        t7 = EmptyOperator(task_id="dummy7")
        @task
        def dummy0():
            return 0
        d0 = dummy0()
        cross_downstream(from_tasks=[d0, t1, t2, t3], to_tasks=[t4, t5, t6, t7])

    with TaskGroup(group_id="group2") as tg2:
        t1 = EmptyOperator(task_id="dummy1")
        t2 = EmptyOperator(task_id="dummy2")
        t3 = EmptyOperator(task_id="dummy3")
        t4 = EmptyOperator(task_id="dummy4")
        t5 = EmptyOperator(task_id="dummy5")
        t6 = EmptyOperator(task_id="dummy6")
        t7 = EmptyOperator(task_id="dummy7")
        @task
        def dummy0():
            return 0

        d0 = dummy0()
        """
        d0.set_downstream(t5)
        d0.set_downstream(t6)
        d0.set_downstream(t7)
        t1.set_downstream(t5)
        t1.set_downstream(t6)
        t1.set_downstream(t7)
        t2.set_downstream(t5)
        t2.set_downstream(t6)
        t2.set_downstream(t7)
        t3.set_downstream(t5)
        t3.set_downstream(t6)
        t3.set_downstream(t7)
        t4.set_downstream(t5)
        t4.set_downstream(t6)
        t4.set_downstream(t7)
        """
        chain(d0, [t4, t5, t6, t7])
        chain(t1, [t4, t5, t6, t7])
        chain(t2, [t4, t5, t6, t7])
        chain(t3, [t4, t5, t6, t7])


chain([tg1, tg2])
``` 

### Operating System

Linux

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gopidesupavan** [comment]
@atul-astronomer is it working on latest released version? can you please confirm

**Comment by atuls4441** [comment]
Resolved now, thanks @gopidesupavan

**Comment by gopidesupavan** [comment]
does this is coming on  v3.0.3 ? can you please check?

**Comment by atuls4441** [comment]
> does this is coming on v3.0.3 ? can you please check?

No its not coming on 3.0.3
