### ISSUE TITLE
'_DockerDecoratedOperator' object has no attribute 'xcom_push'

### ISSUE THREAD

**Issue by deytao** [apache/airflow#53077]
### Apache Airflow Provider(s)

docker

### Versions of Apache Airflow Providers

apache-airflow-providers-docker[common-compat]>=4.4.1
apache-airflow-providers-http>=5.3.
apache-airflow-providers-postgres>=6.2.0

### Apache Airflow version

3.0.2

### Operating System

Manjaro

### Deployment

Virtualenv installation

### Deployment details

uv

```toml
[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "apache-airflow>=3.0.2",
    "apache-airflow-providers-docker[common-compat]>=4.4.1",
    "apache-airflow-providers-http>=5.3.1",
    "apache-airflow-providers-postgres>=6.2.0",
    "httpx>=0.28.1",
    "polars>=1.31.0",
    "ruff>=0.12.2",
]
```

Running
```
	AIRFLOW_HOME=$(CURDIR) \
	AIRFLOW__CORE__LOAD_EXAMPLES=False \
	AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER=True \
	uv run airflow standalone
```

### What happened

I'm trying to use the docker task.
It seems that the container is started, and the code is executed correctly.

## Logs:

```
Log message source details: sources=["/logs/dag_id=docker_xcom_pipeline/run_id=manual__2025-07-09T08:35:46.168850+00:00/task_id=process_in_docker/attempt=1.log"]
[2025-07-09, 10:35:48] INFO - DAG bundles loaded: dags-folder: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
[2025-07-09, 10:35:48] INFO - Filling up the DagBag from/dags/docker_xcom_pipeline.py: source="airflow.models.dagbag.DagBag"
[2025-07-09, 10:35:48] INFO - Starting docker container from image apache/airflow:3.0.2-python3.11: source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
[2025-07-09, 10:35:53] INFO - : source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
[2025-07-09, 10:35:53] INFO - + python3 -c 'import base64, os;x = base64.b64decode(os.environ["__PYTHON_SCRIPT"]);f = open("/tmp/script.py", "wb"); f.write(x);': source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
[2025-07-09, 10:35:53] INFO - + python3 -c 'import base64, os;x = base64.b64decode(os.environ["__PYTHON_INPUT"]);f = open("/tmp/script.in", "wb"); f.write(x);': source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
[2025-07-09, 10:35:53] INFO - + python3 /tmp/script.py /tmp/script.in /tmp/script.out none /tmp/script.out: source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
[2025-07-09, 10:35:56] ERROR - Task failed with exception: source="task"
AttributeError: '_DockerDecoratedOperator' object has no attribute 'xcom_push'

File "/.venv/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py", line 867 in run

File /.venv/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py", line 1159 in _execute_task

File "/.venv/lib/python3.11/site-packages/airflow/sdk/bases/operator.py", line 397 in wrapper

File "/.venv/lib/python3.11/site-packages/airflow/providers/docker/decorators/docker.py", line 194 in execute

File "/.venv/lib/python3.11/site-packages/airflow/sdk/bases/operator.py", line 397 in wrapper

File "/.venv/lib/python3.11/site-packages/airflow/sdk/bases/decorator.py", line 253 in execute
```

### How to reproduce

Create a task with

```python
@task.docker(
    image="apache/airflow:3.0.2-python3.11",
    multiple_outputs=True,
    auto_remove="force",
    network_mode="bridge",
)
def process_in_docker(input_data: dict) -> dict:
    value = input_data.get("value", 0)
    message = input_data.get("message", "")
    return {
        "double_value": value * 2,
        "message": f"{message} (processed in Docker)"
    }
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Indeed seems like there is a compatibility issue with task-sdk

**Comment by jroachgolf84** [comment]
Here's what I'm finding:

* The `DecoratedOperator` is inheriting from the ` airflow.sdk.bases.operator.BaseOperator`. This Operator does NOT implement a `xcom_push` method.
* The `airflow.sdk.BaseOperator` inherits from the `airflow.sdk.bases.operator.BaseOperator` and implements an `xcom_push` method.

I think it might makes sense to update the `DecoratedOperator` to inherit from `airflow.sdk.BaseOperator`, rather than `airflow.sdk.bases.operator.BaseOperator`. @potiuk, thoughts here?

**Comment by jroachgolf84** [comment]
Hmmm, but the `_DockerDecoratedOperator` inherits from both the `DecoratedOperator`, and the `DockerOperator`. The `DockerOperator` inherits from `airflow.sdk.BaseOperator`, so that shouldn't be an issue...

**Comment by zoetsekas** [comment]
is there a work around?

**Comment by GaMeRaM** [comment]
Airflow 3.0.4
Same problem still

**Comment by potiuk** [comment]
cc: @kaxil @ashb -> this might be an important one to fix and seems task-sdk related - also mentioned in  https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1757315973568239

**Comment by potiuk** [comment]
Can anyone confirm it's the case for 3.0.6 + latest docker provider in the meantime?

**Comment by Maxdeboer9** [comment]
I am using the Apache Airflow image 3.0.6 with the latest docker provider 4.4.2:

```
default@0cae6d17f5b7:/opt/airflow$ python3
Python 3.12.11 (main, Aug 12 2025, 22:47:31) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import airflow
>>> import airflow.providers.docker as dock
>>> airflow.__version__
'3.0.6'
>>> dock.__version__
'4.4.2'

```

The following basic use of the task.docker operator:
```
from datetime import datetime
from zoneinfo import ZoneInfo

from airflow import DAG
from airflow.decorators import task

@task.docker(
        image="python:3.12", 
        network_mode="bridge", 
        task_id="get_evc_data_docker", 
        multiple_outputs=True, 
        docker_url="unix://var/run/docker.sock", 
        mount_tmp_dir=False
        )
def evc_data_operator(some_text: str) -> None:
    print(some_text)

def_args = {
    "owner": "airflow",
    "retries": 0,
    "start_date": datetime(2025, 6, 28, tzinfo=ZoneInfo("Europe/Amsterdam")),
}

with DAG(
    dag_id="some_test_dag",
    default_args=def_args,
    catchup=False,
    schedule="0 9 * * 1",
) as dag:

    data_evc_task = evc_data_operator("Some text passed to docker operator")

    data_evc_task
```
Will result in the following error:

```
INFO - DAG bundles loaded: dags-folder: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
INFO - Filling up the DagBag from /opt/airflow/dags/peaklogger/test_dag.py: source="airflow.models.dagbag.DagBag"
INFO - Starting docker container from image python:3.12: source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
INFO - + python3 -c 'import base64, os;x = base64.b64decode(os.environ["__PYTHON_SCRIPT"]);f = open("/tmp/script.py", "wb"); f.write(x);': source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
INFO - + python3 -c 'import base64, os;x = base64.b64decode(os.environ["__PYTHON_INPUT"]);f = open("/tmp/script.in", "wb"); f.write(x);': source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
INFO - + python3 /tmp/script.py /tmp/script.in /tmp/script.out none /tmp/script.out: source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
INFO - Some text passed to docker operator: source="airflow.task.operators.airflow.providers.docker.decorators.docker._DockerDecoratedOperator"
ERROR - Task failed with exception: source="task"
AttributeError: '_DockerDecoratedOperator' object has no attribute 'xcom_push
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 920 in run
  
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1215 in _execute_task
  
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 397 in wrapper
  
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/decorators/docker.py", line 194 in execute
  
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 397 in wrapper
  
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py", line 253 in execute
```

**Comment by morgan-dgk** [comment]
Did a little further digging. 

Can reproduce this using Airflow 3.0.6 / Docker provider v4.4.1+.  However, the issue is **not reproducible** with provider version < 4.4.1. 

I think this was introduced by #52465, which changes import of BaseOperator to Task SDK:

```
if AIRFLOW_V_3_0_PLUS:
    from airflow.sdk import BaseOperator
else:
    from airflow.models import BaseOperator

__all__ = ["AIRFLOW_V_3_0_PLUS", "BaseOperator"]
```
The BaseOperator from airflow.models includes the static[`xcom_push`](https://github.com/apache/airflow/blob/81845de9d95a733b4eb7826aaabe23ba9813eba3/airflow/models/baseoperator.py#L1547-L1565) method. The BaseOperator from airflow.sdk does not appear to include any such method.
