### PR TITLE
Fix proper termination of gunicorn when it hangs

### PR DESCRIPTION
**Pull request by potiuk**
During refactoring of the internal API background test, it was found that the SIGKILL termination of gunicorn in case it was not responding to SIGTERM (introduced in #11734) has never been working properly. The code assumed that gunicorn_master_process was of the subprocess.Popen type and used .poll() method to check if the process is still running and it would issue sigkill in such case.

However the Process we have there is a psutil.Process and it has no poll() method - instead we can use is_running() method, which has the added advantage that is_running() is also checking if the pid has not been reused by another process after terminating the original gunicorn.

The result of it was this error:

```
AttributeError: 'Process' object has no attribute 'poll'
```

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I **think** that one might actually fix not only the production behaviour but also the flakey test we have https://github.com/apache/airflow/actions/runs/4458374125/jobs/7833545103

**Review by pierrejeambrun — APPROVED** [review]
