### ISSUE TITLE
_TaskDecorator has no __wrapped__ attribute in v2.3.0

### ISSUE THREAD

**Issue by ddeepwell** [apache/airflow#23688]
### Apache Airflow version

2.3.0 (latest released)

### What happened

I run a unit test on a task which is defined using the task decorator. In the unit test, I unwrap the task decorator with the `__wrapped__` attribute, but this no longer works in v2.3.0. It works in v2.2.5.

### What you think should happen instead

I expect the wrapped function to be returned. This was what occurred in v2.2.5

When running pytest on the airflow v2.3.0 the following error is thrown:
```AttributeError: '_TaskDecorator' object has no attribute '__wrapped__'```

### How to reproduce

Here's a rough outline of the code.

A module `hello.py` contains the task definition:
```
from airflow.decorators import task

@task
def hello_airflow():
    print('hello airflow')
```

and the test contains
```
from hello import hello_airflow

def test_hello_airflow():
    hello_airflow.__wrapped__()
```

Then run pytest

### Operating System

Rocky Linux 8.5 (Green Obsidian)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Unfortunately the decorator using `functools.wraps()` under the hood (which is responsible for `__wrapped__`) is an implementation detail, and we never thought about keeping compatibility. It could still be added easily enough though (just add a `@property` on `_TaskDecorator`) and I guess no-one would really complain. Would you mind working on a PR for this?

**Comment by ddeepwel** [comment]
I would be happy to work on this, but I don't really know where to begin.

**Comment by uranusjr** [comment]
Simply search in `airflow/decorators/base.py`:

1. In class `_TaskDecorator` (the one with a leading underscore), add

    ```python
    @property
    def __wrapped__(self) -> Function:
        return self.function
    ```

3. In class `TaskDecorator` (the one _without_ an underscore), add

    ```python
    @property
    def __wrapped__(self) -> Function:
        ...
    ```

The first class adds the actual property (so you can access this in tests), while the other declares the interface. The second one is not strictly necessary, but it’s good to provide it for editor autocompletion and stuff.

**Comment by snjypl** [comment]
@uranusjr  @ddeepwel  do you mind if i create a PR for this?

**Comment by uranusjr** [comment]
Go ahead
