### PR TITLE
Fix plugin macros not being exposed through airflow.macros

### LINKED ISSUE #12785: Macros added through plugins can not be used within Jinja templates in Airflow 2.0
**Apache Airflow version**: 2.0.0b3
**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A
**Environment**:

- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): Linux 6ae65b86e112 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 GNU/Linux
- **Others**: Python 3.8

**What happened**:

At JW Player we add additional macros to Airflow through a plugin. The definition of this plugin looks like the following (simplified):

```
from airflow.plugins_manager import AirflowPlugin
from utils_plugin.macros.convert_image_tag import convert_image_tag


class JwUtilsPlugin(AirflowPlugin):
    name = 'jw_utils'
    macros = [convert_image_tag]
```

`convert_image_tag` is a function that takes a string (a docker tag) as argument and resolves it to a SHA-256 hash that uniquely identifies an image by querying the docker registry. I.e. it is a function that takes a string as argument and returns a string.

In Airflow 1.10.x we can successfully use this macro in our DAGs to resolve image tags to SHA-256 hashes, e.g. the following DAG will run an Alpine Image using a DockerOperator:

```python
from datetime import datetime, timedelta
from airflow import DAG

try:
    from airflow.providers.docker.operators.docker import DockerOperator
except ModuleNotFoundError:
    from airflow.operators.docker_operator import DockerOperator

now = datetime.now()

with DAG('test_dag',
         schedule_interval='*/15 * * * *',
         default_args={
             'owner': 'airflow',
             'start_date': datetime.utcnow() - timedelta(hours=1),
             'task_concurrency': 1,
             'execution_timeout': timedelta(minutes=5)
         },
         max_active_runs=1) as dag:
    
    task_sleep = DockerOperator(
        task_id='task_sleep',
        image=f"{{ macros.jw_utils.convert_image_tag('alpine') }}",
        command=['sleep', '10']
    )
```

This is in contrast to Airflow 2.0, if we attempt to use our custom macro here, then when Airflow attempts to render the task template it will error out with the following error:

```
[2020-12-03 12:54:43,666] {{taskinstance.py:1402}} ERROR - 'module object' has no attribute 'jw_utils'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1087, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1224, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1690, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 857, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 870, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 907, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'module object' has no attribute 'jw_utils'
```

**What you expected to happen**:

I would have expected that the DAG definition from above would have worked in Airflow 2.0, like it would have functioned in Airflow 1.10.x.

**How to reproduce it**:

This bug can be reproduced by creating a plugin that adds a macro, and then attempting to use that macro in a DAG.

**Anything else we need to know**:

In order to better understand the issue, I did a bit of digging. The plugin that we extend Airflow's functionality with has its own suite of pytest testcases. Since we are in the process of preparing for a transition to Airflow 2.0 we are now running the unit tests for this plugin against both Airflow 1.10.x and Airflow 2.0.0b3.

After reviewing how plugins were being loaded in Airflow, I've added the following testcase to mimic how plugins were being loaded and how  [`get_template_context()`](https://github.com/apache/airflow/blob/2.0.0b3/airflow/models/taskinstance.py#L1481) in Airflow 2.0 ensures that plugins have been imported:

```python
def test_macro_namespacing(is_airflow_1):
    """
    Tests whether macros can be loaded from Airflow's namespace after loading plugins.
    """
    from airflow import macros
    if not is_airflow_1:
        # In Airflow 2.x, we need to make sure we invoke integrate_macros_plugins(), otherwise
        # the namespace will not be created properly.
        from airflow.plugins_manager import integrate_macros_plugins
        integrate_macros_plugins()
    from utils_plugin.plugin import JwUtilsPlugin

    # After Airflow has loaded the plugins, the macros should be available as airflow.macros.jw_utils.
    macros_module = import_module(f"airflow.macros.{JwUtilsPlugin.name}")

    for macro in JwUtilsPlugin.macros:
        # Verify that macros have been registered correctly.
        assert hasattr(macros_module, macro.__name__)

    # However, in order for the module to actually be allowed to be used in templates, it must also exist on
    # airflow.macros.
    assert hasattr(macros, 'jw_utils')
```

This test case passes when being ran on Airflow 1.10, but surprisngly enough it fails on Airflow 2.x. Specifically it fails on the `assert hasattr(macros, 'jw_utils')` statement in Airflow 2.0. This statement tests whether the macros that we create through the `JwUtilsPlugin` have been properly added to `airflow.macros`.

I thought it was strange for the test-case to fail on this module, given that the `import_module()` statement succeeded in Airflow 2.0. After this observation I started comparing the logic for registering macros in Airflow 1.10.x to the Airflow 2.0.0 implementation.

While doing this I observed that the plugin loading mechanism in Airflow 1.10.x works because Airflow [automatically discovers](https://github.com/apache/airflow/blob/1.10.13/airflow/__init__.py#L104) all plugins through the `plugins_manager` module. When this happens it automatically [initializes plugin-macro modules](https://github.com/apache/airflow/blob/1.10.13/airflow/plugins_manager.py#L306) in the `airflow.macros` namespace. Notably, after the plugin's module has been initialized it will also automatically be registered on the `airflow.macros` module [by updating the dictionary](https://github.com/apache/airflow/blob/1.10.13/airflow/macros/__init__.py#L93) returned by `globals()`.

This is in contrast to Airflow 2.0, where plugins are no longer loaded automatically. Instead they are being loaded lazily, i.e. they will be loaded on-demand whenever a function needs them. In order to load macros (or ensure that macros have been loaded), modules need to import the [`integrate_macros_plugins`](https://github.com/apache/airflow/blob/2.0.0b3/airflow/plugins_manager.py#L395) function from `airflow.plugins_manager`.

When Airflow attempts to prepare a template context, prior to running a task, it properly imports this function and invokes it in [taskinstance.py](https://github.com/apache/airflow/blob/2.0.0b3/airflow/models/taskinstance.py#L1483). However, in contrast to the old 1.10.x implementation, this function does not update the symbol table of `airflow.macros`. The result of this is that the macros from the plugin _will in fact_ be imported, but because `airflow.macros` symbol table itself is not being updated, the macros that are being added by the plugins can not be used in the template rendering context.

I believe this issue could be solved by ensuring that `integrate_macros_plugins` sets a reference to the `airflow.macros.jw_utils` as `jw_utils` on the `airflow.macros` module. Once that has been done I believe macros provided through plugins are functional again.

### PR DESCRIPTION
**Pull request by RikHeijdens**
This PR fixes an issue where macros that are being provided through plugins can not be used at template time because they are not accessible through the `airflow.macros` module.

This PR consists out of two commits. In the first commit I add a test-case that reproduces the issue as outlined in #12785, and the second commit introduces the fix which fixes the issue and allows the test-case to pass.

Fixes: #12785 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

File: tests/plugins/test_plugins_manager.py [hunk 1]
```diff
@@ -213,6 +214,34 @@ def test_entrypoint_plugin_errors_dont_raise_exceptions(self, caplog):
...
+            # Test whether the modules have been created as expected.
+            plugin_macros = importlib.import_module(f"airflow.macros.{MacroPlugin.name}")
+            for macro in MacroPlugin.macros:
+                # Verify that the macros added by the plugin are being set correctly
+                # on the plugin's macro module.
+                assert hasattr(plugin_macros, macro.__name__)
+            # Verify that the symbol table in airflow.macros has been updated with an entry for
+            # this plugin, this is necessary in order to allow the plugin's macros to be used when
+            # rendering templates.
+            assert hasattr(macros, MacroPlugin.name)
```
Comment (RikHeijdens) [inline tests/plugins/test_plugins_manager.py:255]: `integrate_macros_plugins()` has the side-effect that it modifies the `airflow.macros` module. Do we need to add additional cleanup logic to reset the contents of `airflow.macros` through a finalizer here?

File: airflow/plugins_manager.py [hunk 2]
```diff
@@ -419,4 +420,9 @@ def integrate_macros_plugins() -> None:
 
         if macros_module:
             macros_modules.append(macros_module)
-            sys.modules[macros_module.__name__] = macros_module  # pylint: disable=no-member
+            # pylint: disable=no-member
+            sys.modules[macros_module.__name__] = macros_module
+            # Register the newly created module on airflow.macros such that it
+            # can be accessed when rendering templates.
+            setattr(macros, macros_module.__name__.split('.')[-1], macros_module)
```
Comment (mik-laj) [inline airflow/plugins_manager.py]:
```suggestion
            setattr(macros, plugin.name, macros_module)
```

File: tests/plugins/test_plugins_manager.py (hunk 1 above)
Comment (mik-laj) [reply tests/plugins/test_plugins_manager.py:255]: Will [``importlib.reload``](https://docs.python.org/3/library/importlib.html#importlib.reload) help?

Comment (RikHeijdens) [reply tests/plugins/test_plugins_manager.py:255]: Simply reloading the module using `importlib.reload()` will not be sufficient as the module's symbol table (dictionary) is [retained](https://docs.python.org/3/library/importlib.html#importlib.reload).

> When a module is reloaded, its dictionary (containing the module’s global variables) is retained. Redefinitions of names will override the old definitions, so this is generally not a problem. If the new version of a module does not define a name that was defined by the old version, the old definition remains.

I think we'll have to delete the module from `sys.modules` and import it again in order to properly remove the entries that are being added by this test case.

File: airflow/plugins_manager.py (hunk 2 above)
Comment (RikHeijdens) [reply airflow/plugins_manager.py]: Fixed: https://github.com/apache/airflow/pull/12788/commits/84dc19e62f31ae1722005793029df53738f03eed

File: tests/plugins/test_plugins_manager.py (hunk 1 above)
Comment (RikHeijdens) [reply tests/plugins/test_plugins_manager.py:255]: I've implemented this in https://github.com/apache/airflow/pull/12788/commits/c2b5354addb6051f689061eeb9d7ea4d6d8965e3 -- I'm curious to your thoughts.

Comment (mik-laj) [reply tests/plugins/test_plugins_manager.py:255]: I love this change.😻  I'm just wondering if it's worth moving this code to the context manager mock_plugins_manager. This allows us to limit the side effects in other tests as well. What do you think?

Comment (RikHeijdens) [reply tests/plugins/test_plugins_manager.py:255]: I considered doing this, but the `__doc__` comment on the `mock_plugin_manager` seems to suggest that the scope of that mock is limited to the `airflow.plugins` module.

While that mock does in fact clear out the `macros_modules` variable in `airflow.plugins`, it does not actually attempt to reverse any (side) effects that are caused by invoking `integrate_macros_plugins()`. I did a bit of searching through the code base, and it doesn't really appear that there is any test coverage for this function beyond the test I've just added.

Because I want to avoid scope creep for the `mock_plugin_manager` fixture, and this is the only test case that actually appears to have to deal with side effects cause by calling `integrate_macros_plugins()`, I'm a bit hesitant to make changes beyond what's being proposed here.

**Review by mik-laj — APPROVED** [review]

**Review by TobKed — APPROVED** [review]

**Comment by mik-laj** [comment]
@RikHeijdens Can you do a rebase? I want to make sure that `importlib` tricks work on all versions of Python.

**Comment by RikHeijdens** [comment]
@mik-laj I've just rebased my branch on master.

**Comment by RikHeijdens** [comment]
@mik-laj I noticed the change proposed here causes the `TestPythonVirtualenvOperator.test_airflow_context` test to fail. I believe this is happening because `airflow.macros` is being serialized as part of the context which is passed to the underlying subprocess. 

The subprocess in which the Python callable runs however does not integrate the macros provided by plugins. I was able to get this test to pass locally by adding the following two lines of code to `airflow/utils/python_virtualenv_script.jinja2` (see https://github.com/RikHeijdens/airflow/commit/b2c035c87f9cfa95f6185b55c74a4b3d38d9fb63):

```python
# Ensure airflow.macros has been loaded properly.
import airflow.plugins_manager
airflow.plugins_manager.integrate_macros_plugins()
```

Doing this however, seems like a bit of a nasty solution to me and also causes additional test failures. I'm curious whether you have any thoughts on what would be a better solution? What is the use-case of allowing subprocess spawned by PythonVirtualenvOperator to access plugin-provided macros?

**Comment by mik-laj** [comment]
> Doing this however, seems like a bit of a nasty solution to me and also causes additional test failures

I guess this code should only be called if you have airflow installed in your environment.
https://github.com/apache/airflow/blob/39ea8722c04fb1c0b286b4248a52e8d974a47b30/airflow/operators/python.py#L536-L537

The use case is that we want to allow the user to perform any operation, but in a virtual environment. The virtual environment will allow they to use additional libraries.

File: airflow/utils/python_virtualenv_script.jinja2 [hunk 3]
```diff
@@ -20,6 +20,18 @@
 import {{ pickling_library }}
 import sys
 
+# Check whether Airflow is available in the environment.
+# If it is, we'll want to ensure that we integrate any macros that are being provided
+# by plugins prior to unpickling the task context.
+if int(sys.version[0]) >= 3:
```
Comment (mik-laj) [inline airflow/utils/python_virtualenv_script.jinja2]: Airflow 2.0 only supports Python 3.6 and up. https://github.com/apache/airflow#requirements

**Comment by RikHeijdens** [comment]
@mik-laj Got it. I've restored access to `airflow.macros` for subprocesses. However, in order to get the tests to pass I did have to implement an additional safe guard that would prevent `airflow.plugins_manager.integrate_macros_plugins` from being invoked on virtual environments that run Python 2. I don't see how this feature can be supported for any Py2 virtual environments any longer.

**Comment by mik-laj** [comment]
@RikHeijdens  Got it. Thanks for your work.

**Review by mik-laj — APPROVED** [review]

**Comment by ashb** [comment]
@RikHeijdens Can you document this py2 virtualenv limiation somewhere please? (VirtualEnvOperator docs?) LGTM after that.

File: airflow/utils/python_virtualenv_script.jinja2 (hunk 3 above)
Comment (RikHeijdens) [reply airflow/utils/python_virtualenv_script.jinja2]: I'll make the check a bit more strict, just in case :-)

Edit: This has been addressed in https://github.com/apache/airflow/pull/12788/commits/cee7686ab15b5acdc4967ed775b00af48cd5990c.

**Review by ashb — APPROVED** [review]

**Comment by RikHeijdens** [comment]
I've documented the limitation in https://github.com/apache/airflow/pull/12788/commits/d17e98f5b6e59aac572e9bfcf3889dd39a96ae2f, but I'm a bit skeptical as to whether any of the [`AIRFLOW_SERIALIZABLE_CONTEXT_KEYS`](https://github.com/apache/airflow/blob/master/airflow/operators/python.py#L434) can be used in a virtual environment that runs Python 2.

I believe anything that will require to import `airflow.*` no longer works, but there is also no test-coverage that confirms this. I also want to prevent any additional scope-creep with this PR, so I think it may be better to make a new issue for this.

**Comment by RikHeijdens** [comment]
@mik-laj It looks like the CI Build for https://github.com/apache/airflow/pull/12788/commits/d17e98f5b6e59aac572e9bfcf3889dd39a96ae2f failed due to an issue that appears to be unrelated to my proposed changes. Should I rebase my commits on master again in order to trigger a new build?

**Comment by mik-laj** [comment]
@RikHeijdens  Yes. Please, do it. That should fix the problem.

**Comment by ashb** [comment]
Almost there. It almost feels like someone is running a slowloris attack against GitHub actions today.

**Comment by ashb** [comment]
:heavy_check_mark:
