### PR TITLE
Add conf not importable from airflow rule

### LINKED ISSUE #13945: Add conf not importable from airflow rule
**Description**

A new rule should be added to Airflow upgrade check to verify that users import `conf` from proper place and their code will work with 2.0.

**Use case / motivation**

In 1.10 users can do:

```py
In [1]: from airflow import conf

In [2]: conf
Out[2]: <airflow.configuration.AirflowConfigParser at 0x7f6f28650f28>
```
in 2.0 it's not possible:
```py
In [1]: from airflow import conf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2cf28b1802b4> in <module>
----> 1 from airflow import conf

ImportError: cannot import name 'conf'
```

**Are you willing to submit a PR?**

Possibly if time allows 🕐 

**Related Issues**

N/A

### PR DESCRIPTION
**Pull request by digitalsimboja**
This rule checks to ensure user properly imports "conf" to be compatible with Airflow 2.0
closes: https://github.com/apache/airflow/issues/13945 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

File: airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py [hunk 1]
```diff
@@ -0,0 +1,29 @@
+
+from airflow.upgrade.rules.base_rule import BaseRule
+
+print(BaseRule)
+
+<<<<<<< HEAD
```
Comment (turbaszek) [inline airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]:
```suggestion

```

File: airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+        if conf:
+            return (
+                "Warning: Properly import conf to ensure your code works in AIrflow 2.0"
+                "From Airflow 2.0, you should use from airflow.Configuration import conf."
+            )
+
+
+=======
+class CustomExecutorsRequireFullPathRule(BaseRule):
+>>>>>>> 1caae81f64e7cb5307a43b218b836f7d7854f5db
```
Comment (turbaszek) [inline airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]:
```suggestion

```

File: airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py [hunk 3]
```diff
@@ -0,0 +1,29 @@
+
+from airflow.upgrade.rules.base_rule import BaseRule
+
+print(BaseRule)
```
Comment (turbaszek) [inline airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]:
```suggestion

```

File: airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+<<<<<<< HEAD
+
+class ConfImportFromAirflow(BaseRule):
+    """
+      ConfImportFromAirflow class to ensure proper import of conf from to work in Airflow 2.0
+      """
+    title = "Properly import conf from Airflow"
+    description = """\
+    In Airflow-2.0, it's not possible to import conf from airflow by using \'import conf from airflow\'
+    To ensure your code works in Airflow 2.0, you should use \'from airflow.Configuration import conf \'
```
Comment (turbaszek) [inline airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]:
```suggestion
    In Airflow-2.0, it's not possible to import `conf` from airflow by using `import conf from airflow`
    To ensure your code works in Airflow 2.0, you should use `from airflow.configuration import conf`.
```

File: airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+                      """
+
+    def check(self):
+        from airflow import conf
+        if conf:
+            return (
+                "Warning: Properly import conf to ensure your code works in AIrflow 2.0"
+                "From Airflow 2.0, you should use from airflow.Configuration import conf."
+            )
```
Comment (turbaszek) [inline airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]: What this rule should do is to scan all users DAGs and plugins and verify if they use `from airflow import conf` in their code. If yes, we should raise a warning for each file that is impacted by this issue. 

Here's an example how can we iterate through DAG files:
https://github.com/apache/airflow/blob/dbf2e302313580b6eaa85e9fcbcace8b6260c85a/airflow/upgrade/rules/import_changes.py#L138-L146

Same can be done for plugins using ` plugins_folder = conf.get("core", "plugins_folder")`.

Comment (digitalsimboja) [reply airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]: Got it. Thanks

Comment (digitalsimboja) [reply airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]: Hi Turbaszek, I have updated the patch. Kindly review. Thanks

File: airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+
+    wrong_conf_import = "from airflow import conf"
+    proper_conf_import = "from airflow.configuration import conf"
+
+    def _conf_import_info(self, file_path, line_number):
+        return "Warning: In Airflow 2.0, it's not possible to import `conf` by using `{}`. " \
+               "To ensure your code works in Airflow 2.0, you should use `{}`." \
+               " Affected file: {} (line {})".format(
+                self.wrong_conf_import, self.proper_conf_import, file_path, line_number
+                )
```
Comment (turbaszek) [inline airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]:
```suggestion
        return "Affected file: {} (line {})".format(
                self.wrong_conf_import, self.proper_conf_import, file_path, line_number
                )
```
All else will be displayed anyway as it is in rule description, right?

**Review by turbaszek — APPROVED** [review]
Looks good to me, only one comment about the message.

File: airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py (hunk 6 above)
Comment (digitalsimboja) [reply airflow/upgrade/rules/fix_conf_not_importable_from_airflow.py]: Yes that is correct. I will go ahead and return only the affected file and line in this section. Thanks

**Comment by digitalsimboja** [comment]
> Looks good to me, only one comment about the message.

Hi Turbaszek, 
Do you still want me to remove the lines you mentioned or it's okay to go?

**Comment by ephraimbuddy** [comment]
You have static check errors, please install pre-commit and run it. `pre-commit run --all-files`. Commit the result and push

**Comment by turbaszek** [comment]
> > Looks good to me, only one comment about the message.
> 
> Hi Turbaszek,
> Do you still want me to remove the lines you mentioned or it's okay to go?

Yes, it would be nice to simplify the final output

**Review by turbaszek — APPROVED** [review]

**Comment by turbaszek** [comment]
Thanks @digitalsimboja for the PR! 🎉

**Comment by digitalsimboja** [comment]
> Thanks @digitalsimboja for the PR! tada

Thanks for all the wonderful reviews. Looking forward on my next PR
