### ISSUE TITLE
GKEKubernetesAsyncHook missing `_event_polling_fallback` attribute

### ISSUE THREAD

**Issue by OscarLigthart** [apache/airflow#60600]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

19.3.0

### Apache Airflow version

3.1.6

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Other 3rd-party Helm chart

### What happened

After upgrading to 3.1.6, we started seeing the following error in our GKEStartPodOperator execution, running in `deferred` mode:

```
AttributeError: 'GKEKubernetesAsyncHook' object has no attribute '_event_polling_fallback'
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/triggers/pod.py", line 161 in run

File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/triggers/pod.py", line 262 in _wait_for_pod_start

File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 1018 in watch_pod_events

File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 1001 in watch_pod_events
```

After some research it looks like it's a result of the addition of the `_event_polling_fallback` in the [AsyncKubernetesHook](https://github.com/apache/airflow/blob/main/providers/cncf/kubernetes/src/airflow/providers/cncf/kubernetes/hooks/kubernetes.py#L818). This is never initialized in the `GKEKubernetesAsyncHook`, because the `AsyncKubernetesHook` init method is never called, due to disruption of the MRO chain.

With the current initialization of `GKEKubernetesAsyncHook`, the MRO is:

1. `GKEKubernetesAsyncHook`
2. `GoogleBaseAsyncHook` -> Doesn't call `super().__init__()`, so it stops here
3. `AsyncKubernetesHook`
4. `KubernetesHook`
5. `BaseHook`

As stated, the initialization stops after 2 due to a missing `super().__init__()` Hence, the `_event_polling_fallback` attribute is never added.

### What you think should happen instead

The `GKEKubernetesAsyncHook` should have an attribute `_event_polling_fallback`, as it is part of the initialization method of `AsyncKubernetesHook`. The attribute has recently been introduced [here](https://github.com/apache/airflow/blob/main/providers/cncf/kubernetes/src/airflow/providers/cncf/kubernetes/hooks/kubernetes.py#L818).

### How to reproduce

In our case, we run tasks with the GKEStartPodOperator in `deferred` mode. The pod runs without issues to completion, but tasks are marked as failed with the exception stated above.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
