### ISSUE TITLE
BigQuery connection does not working on 1.7.0 

### ISSUE THREAD

**Issue by WesleyBatista** [apache/airflow#1354]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow: 1.7.0
- Python Version: 2.7.10
- (Optional) Python packages: 
  - **airflow==1.7.0**
  - **pandas==0.18.0**

Now that you know a little about me, let me tell you about the issue I am having:
### Description of Issue
- What did you expect to happen?
  **see query results**
- What happened instead?
  **The following error message appears:**

> 'BigQueryPandasConnector' object has no attribute 'test_google_api_imports'
- Here is how you can reproduce this issue on your machine:
### Reproduction Steps
1. Setup a BigQuery Connection on **Admin** > **Connections** page
2. On **Data Profiling** > **Ad Hoc Query** page, try to run some query using the connection set on the step before.

![captura de tela 2016-04-12 as 10 05 18](https://cloud.githubusercontent.com/assets/755254/14462000/6296db84-009b-11e6-9882-3d682b363233.png)

**Comment by criccomini** [comment]
Can you:
1. Use 1.7.1 (https://github.com/airbnb/airflow/tree/1.7.1) instead of 1.7.0? 1.7.0 had a dependency issue for Google cloud that broke everything.
2. Verify that you've installed `airflow[gcp_api]`?

**Comment by r39132** [comment]
@WesleyBatista Actually, it looks like 1.7.1. is not good tag. cc/ @criccomini @jlowin @mistercrunch @bolkedebruin

**Comment by criccomini** [comment]
@r39132 I think this might be the same thing that I'm seeing. When I grep for `previously succeeded on`, I find a ton of entries after upgrading to 1.7.1.

**Comment by criccomini** [comment]
If 1.7.1 is bad, then I'd recommend dropping to 1.6.2, or waiting for the real 1.7.1 to be released (apparently the tag was pushed by accident).

**Comment by criccomini** [comment]
Haven't heard anything from @WesleyBatista. Does rolling back to 1.6.2 help?

**Comment by WesleyBatista** [comment]
Sorry guys, I could not try anything since I published the issue.
I want to try to do a downgrade to 1.6.2, but I am a little bit concerned about the issues with some database modification done on any commit.

**Comment by WesleyBatista** [comment]
Sorry not being able to be fully commited with this issue and not replying in time, but I will try your guesses :)

**Comment by criccomini** [comment]
@WesleyBatista you should be able to downgrade the DB if you need to. From the dir where Airflow is installed, run:

```
alembic downgrade <checksum>
```

Where <checksum> is the checksum that you want to downgrade to. Checksums can be viewed in the `migrations` directory.

**Comment by WesleyBatista** [comment]
Cool then! :) thanks very much for the tip. I will try this tomorrow as
soon as I can.

**Comment by criccomini** [comment]
Checking in.

**Comment by criccomini** [comment]
@WesleyBatista going to close this if I don't hear back within 24h.

**Comment by criccomini** [comment]
I have been able to reproduce this issue.

**Comment by criccomini** [comment]
I will fix it as part of AIRFLOW-16 (https://issues.apache.org/jira/browse/AIRFLOW-16).

**Comment by criccomini** [comment]
This is caused by backwards incompatible changes that Pandas made.

**Comment by criccomini** [comment]
This is fixed as part of:

https://issues.apache.org/jira/browse/AIRFLOW-16
