### PR TITLE
Handle non-compliant behaviour of Exasol cursor

### LINKED ISSUE #28731: AttributeError: 'ExaStatement' object has no attribute 'description'
### Apache Airflow Provider(s)

exasol

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.3.1
apache-airflow-providers-exasol==4.1.1

### Apache Airflow version

2.5.0

### Operating System

Rocky Linux 8.7 (like RHEL 8.7)

### Deployment

Other Docker-based deployment

### Deployment details

- Docker Images built using Python 3.9 and recommended constraints https://raw.githubusercontent.com/apache/airflow/constraints-2.5.0/constraints-3.9.txt
- Deployment to AWS ECS

### What happened

After upgrading from Airflow 2.4.3 to 2.5.0, the ExasolOperator stopped working even when executing simple SQL Statements.
See log snippet below for details.

It looks like the Exasol Hook fails due to a missing attribute.
It seems likely the issue was introduced in a refactoring of the Exasol Hook to use common DBApiHook https://github.com/apache/airflow/pull/28009/commits

### What you think should happen instead

_No response_

### How to reproduce

Any execution of ExasolOperator in Airflow built with the mentioned constraints should show the issue.

### Anything else

```console

[2023-01-04, 15:31:33 CET] {exasol.py:176} INFO - Running statement: EXECUTE SCRIPT mohn_fw.update_select_to_date_for_area('CORE'), parameters: None
[2023-01-04, 15:31:33 CET] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    output = hook.run(
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/exasol/hooks/exasol.py", line 178, in run
    result = handler(cur)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 62, in fetch_all_handler
    if cursor.description is not None:
AttributeError: 'ExaStatement' object has no attribute 'description'
[2023-01-04, 15:31:33 CET] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=MOH_DWH_DAILY_CORE, task_id=update_select_to_date_for_area, execution_date=20221225T210000, start_date=20230104T143132, end_date=20230104T143133
[2023-01-04, 15:31:33 CET] {standard_task_runner.py:100} ERROR - Failed to execute job 46137 for task update_select_to_date_for_area ('ExaStatement' object has no attribute 'description'; 7245)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
Exasol is not DBAPI-2 compliant, as described in:
https://github.com/exasol/pyexasol/blob/master/docs/DBAPI_COMPAT.md

This means that SQLOperator cannot be used for it and we should undeprecate the original operator and use specific Exasol handler as default for the returned values.

We also add explicit exception in case non-compliant DB2-API database (with missing description) is used with default Operator and handlers.

Fixes: #28731 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @kazanzhy

File: airflow/providers/exasol/operators/exasol.py [hunk 1]
```diff
@@ -17,12 +17,15 @@
...
 from __future__ import annotations
 
-import warnings
 from typing import Sequence
 
 from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
 
 
+def exasol_fetch_all_handler(cursor) -> list[tuple] | None:
+    return cursor.fetchall()
```
Comment (eladkal) [inline airflow/providers/exasol/operators/exasol.py]: I think this function should be in exasol hook rather than the operator?

BTW is this specific to exasol or may applied to other integrations ? if so maybe this needs to be in common.sql ?


I wonder what happens if using `SqlSensor` with exasol?

Comment (potiuk) [reply airflow/providers/exasol/operators/exasol.py]: Right. Might be good idea to make it a generic non-fully-dbapi compliant DB (but I am not sure if we have many :))

Comment (potiuk) [reply airflow/providers/exasol/operators/exasol.py]: Re: applying to others: Moving it now to common.sql though is an extra complication - because then it means that you can only rely on version >= 1.4.0 (?) for exasol. If there are other reasons to do it, we could make it "common" but if we do not need it now, we can leave it in exasol and move it to common when needed.

There is this nice saying "You have to make something usable first in order to make it reusable".

Comment (Taragolis) [reply airflow/providers/exasol/operators/exasol.py]: As far as I know at least Presto not implements all mandatory properties, for example [presto-python-client](https://github.com/prestodb/presto-python-client/blob/57b95549650aad5a647a768472bf6909320f1bf3/prestodb/dbapi.py#L37-L40) not implements [paramstyle](https://peps.python.org/pep-0249/#paramstyle) but for this case we manually set this value in [Hook](https://github.com/apache/airflow/blob/8290ade26deba02ca6cf3d8254981b31cf89ee5b/airflow/providers/presto/hooks/presto.py#L83) but technically we could get this value from DB-API compliant libraries.

Comment (potiuk) [reply airflow/providers/exasol/operators/exasol.py]: > I wonder what happens if using SqlSensor with exasol?

This will work fine because sensor uses "get_records" method of the hook and does not use handler - and the root cause of the problem was detection of whether the resultSet is returned based on presence of the "description" field. I am doing it differently now in the "exasol-specific" handler.

Comment (potiuk) [reply airflow/providers/exasol/operators/exasol.py]: > As far as I know at least Presto not implements all mandatory properties, for example [presto-python-client](https://github.com/prestodb/presto-python-client/blob/57b95549650aad5a647a768472bf6909320f1bf3/prestodb/dbapi.py#L37-L40) not implements [paramstyle](https://peps.python.org/pep-0249/#paramstyle) but for this case we manually set this value in [Hook](https://github.com/apache/airflow/blob/8290ade26deba02ca6cf3d8254981b31cf89ee5b/airflow/providers/presto/hooks/presto.py#L83) but technically we could get this value from DB-API compliant libraries.

I do not think this is a problem - we only really should care about the non-compliance if we are depending on it in our code - otherwise, it's up to the user to know that Presto is not fully db-api-2 compliant. In case of exasol, the root cause was that it does not set the ".description" property which we used to determine if we should fetch results or not, and I believe we have not used `paramstyle` in our "common.sql" code.

Comment (potiuk) [reply airflow/providers/exasol/operators/exasol.py]: > Re: applying to others: Moving it now to common.sql though is an extra complication - because then it means that you can only rely on version >= 1.4.0 (?) for exasol. If there are other reasons to do it, we could make it "common" but if we do not need it now, we can leave it in exasol and move it to common when needed.

BTW. This is not even possible now. We needed to implement "exasol-specific" handler. The way how we can check if the result set is present for the ExaStatement is different than for any other handler (`self.result_type == 'resultSet'`) - so this handler is not even a generic one.

Comment (potiuk) [reply airflow/providers/exasol/operators/exasol.py]: And anotther BTW. I think with this change, it's actually great verification that the common sql extraction of @kazanzhy works nicely, following the [open-closed](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle) principles. 

It turned out that we can implement exasol-specific behaviour without modifying the "common.sql" code which is precisely what "open for extensions and closed for modifications" is about.

Comment (Taragolis) [reply airflow/providers/exasol/operators/exasol.py]: >  do not think this is a problem - we only really should care about the non-compliance if we are depending on it in our code - otherwise, it's up to the user to know that Presto is not fully db-api-2 compliant. In case of exasol, the root cause was that it does not set the ".description" property which we used to determine if we should fetch results or not, and I believe we have not used paramstyle in our "common.sql" code.

Yep most agree with this with a small concern then we should use all attributes/methods of DB-API 2 first rather than implement our solution because there is always a risk that we reinvent sqlalchemy

If we potentially can use `paramstyle` it would allow us not reinvent the wheel. Right now we by default use  that by DB use `format` (ANSI C printf format codes, e.g. `...WHERE name=%s`) and if DB use different style than we overwrite this argument for specific hook

https://github.com/apache/airflow/blob/3eee33ac8cb74cfbb08bce9090e9c601cf98da44/airflow/providers/common/sql/hooks/sql.py#L126-L127 

Unfortunetly for some reason not all backends implement this attribute such as `presto-python-client` as well as `pyexasol` which also for some reason not implements params for [execute](https://github.com/exasol/pyexasol/blob/master/pyexasol/db2/__init__.py#L37-L38).

Reuse mandatory DB-API 2 parameters and methods would make our life easier in case of if Hook support different backends, for example MySqlHook could use `mysql-connector-python` and `mysqlclient` fortunately both of them use same param style. 

In some time in the future we would in position when we need support both `psycopg2` and `psycopg` (v3) for PostgresHook, but we also lucky with this backends, both of them support `pyformat` (specified in DB-API adapter) and `format`

**Comment by potiuk** [comment]
Fix verified by the user : https://github.com/apache/airflow/issues/28731#issuecomment-1375366853 - also fixed all the tests to reflect it.

**Review by eladkal — APPROVED** [review]

**Comment by eladkal** [comment]
I think should also increase minimum `common.sql` version in exasol provider as part of this PR

**Comment by potiuk** [comment]
> I think should also increase minimum `common.sql` version in exasol provider as part of this PR

No need. The only difference in common.sql is to raise better exception if someone wants to use directly common.sql operator on Exasol with default handler. All the rest will work regardless from common.sql version.
