### PR TITLE
Fixes AzureFileShare connection extras

### LINKED ISSUE #16254: Wasb connection to Azure Fileshareservice Hook not working
**Apache Airflow version**: 
Version: v2.1.0
Git Version: .release:2.1.0+304e174674ff6921cb7ed79c0158949b50eff8fe

**What happened**:
INFO - __init__() got an unexpected keyword argument 'extra__wasb__connection_string'

**What you expected to happen**:
We have used the extra field and populated the SAS token according to the documents on how to use wasb connection for fileshare and we should be able to login in using the SAS token. This has been working in 2.0.0

airflow_bug

### PR DESCRIPTION
**Pull request by potiuk**
The Azure File Share connection has not been creted in #15159 and it
caused an unexpected side effect as the default Azure Connection
passed service_options dictionary to FileService
with key that was unexpected.

This change fixes two things:

1) adds AzureFileShare connection that has separate conn_type
   and handles the extra_options specific for FileService Hook
   available in the Airflow UI.

2) handles the "deprecated" way of passing keys without UI prefix
   but raises a deprecation warning when such key is passed or
   when the Wasb connection is used with an empty extras rather
   than Azure File Share.

Fixes #16254

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @sunkickr @cvsekhar

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
I also changed the tests to fix the annoying behaviour of having to fix tests after every new connection (I am now just checking if the returned arrays have reasonable size > x) rather than exact content/list. That should be `good enough` and avoid the extra hoop of falling CI when you think you've added new connection/provider etc.

**Review by eladkal — APPROVED** [review]

**Comment by sunkickr** [comment]
@potiuk thanks for fixing this error!

**Comment by potiuk** [comment]
No problem. I am merging it in soon and that's last thing before releasing the providers (it's been delayed due to my unavailability but I am catching up).

**Comment by potiuk** [comment]
Good point. Yeah I think this needs fixing as well:
https://github.com/apache/airflow/blob/86b9d3b1e8b2513aa3f614b9a8eba679cdfd25e0/airflow/providers/microsoft/azure/hooks/azure_container_volume.py#L42

It will not crash, but it will not use the extra either

**Comment by potiuk** [comment]
I also noticed that howtos needs updating

**Comment by potiuk** [comment]
Added new connection type and updated the howtos in latest fixup @sunkickr  - would you mind taking a look ?
