### ISSUE TITLE
Mypy type checker fails after upgrading from 2.1.4 to 2.2.0

### ISSUE THREAD

**Issue by brain-buster** [apache/airflow#19002]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

Ubuntu 20.04.3 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.3.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-mongo==2.1.0
apache-airflow-providers-postgres==2.3.0
apache-airflow-providers-sqlite==2.0.1

### Deployment

Other 3rd-party Helm chart

### What happened

After updating to Apache Airflow 2.2.0 type checker Mypy completely fails with the following error:

./lib/python3.8/site-packages/airflow/_vendor/connexion/apis/abstract.py:16: note: In module imported here,
./lib/python3.8/site-packages/airflow/_vendor/connexion/apis/__init__.py:1: note: ... from here,
./lib/python3.8/site-packages/airflow/_vendor/connexion/__init__.py:5: note: ... from here,
./lib/python3.8/site-packages/airflow/api_connexion/exceptions.py:21: note: ... from here,
./lib/python3.8/site-packages/airflow/exceptions.py:26: note: ... from here,
./lib/python3.8/site-packages/airflow/__init__.py:63: note: ... from here,
./my_project/airflow_dags/my_file_with_dag_definition.py:5: note: ... from here:
./lib/python3.8/site-packages/airflow/_vendor/connexion/spec.py:169: error: invalid syntax  [syntax]
            spec.setdefault('consumes', ['application/json'])  # type: List[str]

### How to reproduce

Run 'mypy' command in recursively mode within project:

`mypy .`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
