### PR TITLE
Restore ``get_previous_dagrun`` functionality for task context

### LINKED ISSUE #53628: DagRun.get_previous_dagrun() was removed
### Apache Airflow version

3.0.3

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Previously, in 2.9.2, I used the dag_run available in the task context and called get_previous_dagrun on it, but from what I understand in Airflow 3 the context holds a stripped down version of the dag_run, which no longer has the get_previous_dagrun method.
Instead, in Airflow 3.0.2 the call fails with:
`AttributeError: 'DagRun' object has no attribute 'get_previous_dagrun'`

### What you think should happen instead?

I think there should be a get_previous_dagrun method as before. The reason I used this in 2.9.2 was to get the state of the previous DagRun and based on the current and previous state decided whether to send a notification or not (e.g.: if a DAG fails, we might only care to get a notification on the first failure or when it recovers, not in between)

### How to reproduce

For reference, the code that works in 2.9.2 looks like this:
`crt_dag_run = context["dag_run"]
 previous_dag_run = crt_dag_run.get_previous_dagrun(dag_run=crt_dag_run)`

In v3, the DagRun that I get is of type airflow.sdk.api.datamodels._generated.DagRun which doesn't contain the get_previous_dagrun method.

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes  10.6.1
apache-airflow-providers-standard         1.4.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kaxil**
Add `get_previous_dagrun` method to RuntimeTaskInstance to replace the removed `DagRun.get_previous_dagrun()` method from Airflow 2.x. This enables users to access previous DAG run information from task context for conditional logic like notifications on state changes.

Changes:
- Add `GetPreviousDagRun` message and `PreviousDagRunResult` response in comms
- Add `get_previous_dagrun` instance method to `RuntimeTaskInstance`
- Add `/dag-runs/{dag_id}/previous` API endpoint with optional state filtering
- Add `get_previous` method to DagRunOperations API client
- Update supervisor to handle `GetPreviousDagRun` messages

**ToDo**:
- [x] Add Cadwyn migration
- [ ] Remove defaults when sending serialized object to buffer

Usage:
```python
def my_task(context):
    ti = context["ti"]
    previous_run = ti.get_previous_dagrun()
    if previous_run:
        # Access previous run metadata
        print(f"Previous run: {previous_run.dag_run.run_id}")
```

or

```py
@dag
def a_dag():
    @task(task_id="print_the_context")
    def print_context(**kwargs):
        ctx = get_current_context()
        dr = ctx["dag_run"]
        print("Current dag run:")
        pprint(dr)
        print()
        print("Getting prev dag run...")
        gpd = ctx["ti"].get_previous_dagrun()
        print("Previous dag run:")
        pprint(gpd)


    run_this = print_context()
```

image

Fixes #53628

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/api_fastapi/execution_api/routes/dag_runs.py [hunk 1]
```diff
@@ -172,16 +177,45 @@ def get_dr_count(
...
+        select(DagRunModel)
+        .where(
+            DagRunModel.dag_id == dag_id,
+            DagRunModel.logical_date < logical_date,
+        )
+        .order_by(DagRunModel.logical_date.desc())
+        .limit(1)
+    )
+
+    if state:
```
Comment (amoghrajesh) [inline airflow-core/src/airflow/api_fastapi/execution_api/routes/dag_runs.py:214]: Validate if a valid state is sent for filtering? (check in `DagRunState`) 

Nothing stops me from sending "abcd" as state.

File: airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_08_10.py [hunk 2]
```diff
@@ -28,3 +28,20 @@ class AddDagVersionIdField(VersionChange):
...
+    instructions_to_migrate_to_previous_version = (
+        schema(DagRun).field("state").didnt_exist,
+        endpoint("/dag-runs/{dag_id}/previous", ["GET"]).didnt_exist,
+    )
+
+    @convert_response_to_previous_version_for(TIRunContext)  # type: ignore[arg-type]
+    def remove_state_from_dag_run(response: ResponseInfo = None) -> None:  # type: ignore
+        """Remove the `state` field from the dag_run object when converting to the previous version."""
+        if "dag_run" in response.body and isinstance(response.body["dag_run"], dict):
+            response.body["dag_run"].pop("state", None)
```
Comment (amoghrajesh) [inline airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_08_10.py]: Looks good.

File: airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_08_10.py [hunk 3]
```diff
@@ -28,3 +28,20 @@ class AddDagVersionIdField(VersionChange):
...
+
+    description = __doc__
+
+    instructions_to_migrate_to_previous_version = (
+        schema(DagRun).field("state").didnt_exist,
+        endpoint("/dag-runs/{dag_id}/previous", ["GET"]).didnt_exist,
+    )
+
+    @convert_response_to_previous_version_for(TIRunContext)  # type: ignore[arg-type]
+    def remove_state_from_dag_run(response: ResponseInfo = None) -> None:  # type: ignore
```
Comment (amoghrajesh) [inline airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_08_10.py]: Why are the type ignores needed?

**Review by amoghrajesh — APPROVED** [review]
Just a comment, looks good otherwise!

File: airflow-core/src/airflow/api_fastapi/execution_api/routes/dag_runs.py (hunk 1 above)
Comment (kaxil) [reply airflow-core/src/airflow/api_fastapi/execution_api/routes/dag_runs.py:214]: Fixed and added tests

File: airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_08_10.py (hunk 3 above)
Comment (kaxil) [reply airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_08_10.py]: Same as 

https://github.com/apache/airflow/blob/b8e44e78b44715f2c66f8194b690d2348fbd9a0f/airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_05_20.py#L34-L35

They address mypy's inability to fully understand Cadwyn's decorator type signatures, unfortunately.
