### PR TITLE
Fix/RE:Invalid uri created when extras contains non string elements

### PR DESCRIPTION
**Pull request by Pyasma**
RE:This PR fixes how Connection.get_uri() handles extras with non-string values (floats, booleans, nested dicts).

Extras are now stringified before encoding to produce valid, SQLAlchemy-compatible URIs.

Added a unit test test_get_uri_with_non_string_extras to verify the change.

All pre-commit checks passed.

Issue :https://github.com/apache/airflow/issues/55893

Original PR is closed -> https://github.com/apache/airflow/pull/57969

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Comment by Pyasma** [comment]
CodeQL workflow is awaiting maintainer approval (standard for PRs from forks). All unit tests pass locally.
@jason810496 
@Lee-W

**Comment by Pyasma** [comment]
> CodeQL workflow is awaiting maintainer approval (standard for PRs from forks). All unit tests pass locally. @jason810496 @Lee-W

Can you review this please

**Comment by Pyasma** [comment]
Hey @potiuk, thanks for re-running the tests. I’m a bit confused by these errors—do you have any advice on where I should start looking or how to approach fixing them?

**Comment by potiuk** [comment]
> Hey @potiuk, thanks for re-running the tests. I’m a bit confused by these errors—do you have any advice on where I should start looking or how to approach fixing them?

There was a flaky test in main - so it failed often in other PRs as well. This is now hopefully fixed in https://github.com/apache/airflow/pull/59394  so you should not worry about it.

**Comment by henry3260** [comment]
Same 🫠

**Comment by Pyasma** [comment]
test still failed though :smiling_face_with_tear: 
I will look at it later any advice for this one ?

**Comment by potiuk** [comment]
Yep. the `hopefully` part was unfortunatelly well placed.

**Comment by henry3260** [comment]
> test still failed though :smiling_face_with_tear: 
> 
> I will look at it later any advice for this one ?

Don't worry. It's not you fault

**Comment by potiuk** [comment]
Yeah. Not your fault for sure. I have a likely fix for the main issue: https://github.com/apache/airflow/pull/59406

**Comment by Pyasma** [comment]
Nice all test passed thanks @potiuk @henry3260 

The issue is solved now?

**Comment by henry3260** [comment]
> Nice all test passed thanks @potiuk @henry3260 
> 
> The issue is solved now? 

Yes 😀

**Comment by Pyasma** [comment]
@jason810496 Hey jason can you please review the PR

**Comment by Pyasma** [comment]
hey @Lee-W Can you please review the PR

File: airflow-core/tests/unit/models/test_connection.py [hunk 1]
```diff
@@ -148,6 +148,17 @@ def clear_fernet_cache(self):
...
+                "type://host?int_param=123&bool_param=true&float_param=1.5&str_param=some_str",
+                "type",
+                "host",
+                None,
+                None,
+                None,
+                "",
+                {"int_param": 123, "bool_param": True, "float_param": 1.5, "str_param": "some_str"},
+                None,
+            ),
```
Comment (jason810496) [inline airflow-core/tests/unit/models/test_connection.py:161]: Could we add another case that include `__extra__` in the URI to check whether the `parse_from_uri` are still able to parse the new encoding logic?

File: airflow-core/src/airflow/models/connection.py [hunk 2]
```diff
@@ -457,14 +470,14 @@ def get_extra_dejson(self, nested: bool = False) -> dict:
...
-                        extra[key] = value
+                    for key, value in extra.items():
                         if isinstance(value, str):
-                            with suppress(JSONDecodeError):
+                            try:
                                 extra[key] = json.loads(value)
-                else:
-                    extra = json.loads(self.extra)
+                            except (JSONDecodeError, TypeError):
+                                pass
```
Comment (jason810496) [inline airflow-core/src/airflow/models/connection.py]: Sorry for pointing you in the wrong direction in my last review.
After double-checking, we don’t need to change `get_extra_dejson` at all.

File: airflow-core/src/airflow/models/connection.py [hunk 3]
```diff
@@ -331,14 +335,23 @@ def get_uri(self) -> str:
...
-                query = None
-            if query and self.extra_dejson == dict(parse_qsl(query, keep_blank_values=True)):
-                uri += ("?" if self.schema else "/?") + query
-            else:
+                extra_dict = self.extra_dejson
+                can_flatten = True
+                for _, value in extra_dict.items():
+                    if not isinstance(value, str):
+                        can_flatten = False
+                        break
```
Comment (jason810496) [inline airflow-core/src/airflow/models/connection.py]: How about moving the `can_flatten` logic before the `try` block, as it _should_ not raise any `TypeError, AttributeError` exception.

File: airflow-core/src/airflow/models/connection.py [hunk 4]
```diff
@@ -331,14 +335,23 @@ def get_uri(self) -> str:
...
+
+                if can_flatten:
+                    query = urlencode(extra_dict)
+                    if extra_dict == dict(parse_qsl(query, keep_blank_values=True)):
+                        uri += ("?" if self.schema else "/?") + query
+                    else:
+                        uri += ("?" if self.schema else "/?") + urlencode({self.EXTRA_KEY: self.extra})
+                else:
+                    uri += ("?" if self.schema else "/?") + urlencode({self.EXTRA_KEY: self.extra})
+            except (TypeError, AttributeError):
```
Comment (jason810496) [inline airflow-core/src/airflow/models/connection.py]: It seems the whole flow could be simplify as:

```python
can_flatten = True
# the for loop to check whether could we flatten 

try:
    query: str | None = urlencode(self.extra_dejson)
except TypeError:
    query = None

# we just need to add can_flatten condition check
if can_flatten and query and self.extra_dejson == dict(parse_qsl(query, keep_blank_values=True)):
    uri += ("?" if self.schema else "/?") + query
else:
# fallback to nested EXTRA_KEY
    uri += ("?" if self.schema else "/?") + urlencode({self.EXTRA_KEY: self.extra})
```

which also minimized the change.

**Review by jason810496 — COMMENTED** [review]
Thanks for the update!

File: airflow-core/src/airflow/models/connection.py [hunk 5]
```diff
@@ -252,6 +251,11 @@ def _parse_from_uri(self, uri: str):
             if self.EXTRA_KEY in query:
                 self.extra = query[self.EXTRA_KEY]
             else:
+                for key, value in query.items():
+                    try:
+                        query[key] = json.loads(value)
+                    except (JSONDecodeError, TypeError):
+                        pass
```
Comment (Lee-W) [inline airflow-core/src/airflow/models/connection.py]: Worth adding a log here. probably debug or info

File: airflow-core/src/airflow/models/connection.py [hunk 6]
```diff
@@ -331,14 +335,23 @@ def get_uri(self) -> str:
...
             try:
-                query: str | None = urlencode(self.extra_dejson)
-            except TypeError:
-                query = None
-            if query and self.extra_dejson == dict(parse_qsl(query, keep_blank_values=True)):
-                uri += ("?" if self.schema else "/?") + query
-            else:
+                extra_dict = self.extra_dejson
+                can_flatten = True
+                for _, value in extra_dict.items():
```
Comment (Lee-W) [inline airflow-core/src/airflow/models/connection.py]:
```suggestion
                for value in extra_dict.values():
```

File: airflow-core/src/airflow/models/connection.py [hunk 7]
```diff
@@ -330,15 +334,22 @@ def get_uri(self) -> str:
...
+            extra_dict = self.extra_dejson
+            can_flatten = True
+            for value in extra_dict.values():
+                if not isinstance(value, str):
+                    can_flatten = False
+                    break
+
             try:
-                query: str | None = urlencode(self.extra_dejson)
+                query = urlencode(extra_dict)
```
Comment (Lee-W) [inline airflow-core/src/airflow/models/connection.py]: would like to know why did we remove type annotation

**Review by Lee-W — APPROVED** [review]
one nit, overall looks good

File: airflow-core/src/airflow/models/connection.py (hunk 2 above)
Comment (jason810496) [reply airflow-core/src/airflow/models/connection.py]: I think we could revert the change of `get_extra_dejson`, as  current change doesn't impact the behavior.Thanks!

**Comment by Pyasma** [comment]
sorry about this push i am gonna push one more time i forgot to do prek test

File: airflow-core/src/airflow/models/connection.py (hunk 7 above)
Comment (Pyasma) [reply airflow-core/src/airflow/models/connection.py]: sorry about this i added it again

**Review by jason810496 — APPROVED** [review]

**Comment by Pyasma** [comment]
@jason810496 @Lee-W Thanks for approving the PR can you merge this to main?

**Comment by jason810496** [comment]
Sorry that I forgot to add the backport label. @Pyasma, would you mind backporting this PR to the `v3-1-test` branch? Thanks!

We can backport the patch using the following command and resolve any conflicts if needed:

```bash
cherry_picker a377033 v3-1-test
```

**Comment by potiuk** [comment]
I cherry-picked it here https://github.com/apache/airflow/pull/60219 @jason810496

**Comment by Pyasma** [comment]
hey @jason810496  Sorry i missed the message and thanks @potiuk

**Comment by frodo2000** [comment]
After migration to 3.1.6 still having error:

`[2026-01-13 15:46:29] ERROR - Task failed with exception source=task loc=task_runner.py:1056
AirflowException: ('Entra Id processing error:', TypeError("connect() got an unexpected keyword argument '__extra__'"))
File "/home/airflow/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1004 in run

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1405 in _execute_task

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 417 in wrapper

File "/opt/airflow/plugins/com/softwaremind/transfers/entraid.py", line 148 in execute

TypeError: connect() got an unexpected keyword argument '__extra__'
File "/opt/airflow/plugins/com/softwaremind/transfers/entraid.py", line 133 in execute

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 97 in get_sqlalchemy_connection

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325 in connect

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96 in __init__

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404 in raw_connection

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371 in _wrap_pool_connect

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327 in connect

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894 in _checkout

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493 in checkout

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145 in _do_get

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70 in __exit__

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211 in raise_

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143 in _do_get

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273 in _create_connection

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388 in __init__

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690 in __connect

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70 in __exit__

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211 in raise_

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686 in __connect

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574 in connect

File "/home/airflow/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598 in connect`

When extra fields contains as_dict attribute:

`{
  "tds_version": "7.3",
  "as_dict": true
}`

**Comment by henry3260** [comment]
@frodo2000 Can you open an issue for that?
Thanks!
