### PR TITLE
Fix remote_task_handler_kwargs passing handler params to RemoteLogIO

### LINKED ISSUE #58770: Cannot configure FileTaskHandler max_bytes via remote_task_handler_kwargs in Airflow 3
### Apache Airflow version

3.1.3

### If "Other Airflow 2/3 version" selected, which one?

_No response_

### What happened?

We encountered a breaking change when upgrading from Airflow 2.11.0 to 3.1.3 related to remote_task_handler_kwargs in airflow_local_settings.py.

Issue:

In Airflow 2.x, remote_task_handler_kwargs configured the FileTaskHandler (or its subclasses like WasbTaskHandler). We successfully used this to set max_bytes for log file size limiting:

remote_task_handler_kwargs = {"max_bytes": 5000000, "backup_count": 5}

After upgrading to Airflow 3.x, this configuration raises:

TypeError: WasbRemoteLogIO.__init__() got an unexpected keyword argument 'max_bytes'

### What you think should happen instead?

Root cause:

PR https://github.com/apache/airflow/pull/48491 introduced separate RemoteLogIO classes for remote storage operations. The current implementation in airflow_local_settings.py now passes remote_task_handler_kwargs to WasbRemoteLogIO.__init__(), which only accepts base_log_folder, remote_base, delete_local_copy, and wasb_container.

Handler-level parameters like max_bytes and backup_count should go to FileTaskHandler, but are instead being consumed by the I/O layer, which doesn't support them.

Misleading naming:

The variable name remote_task_handler_kwargs suggests these parameters configure the handler, but the current code path applies them to the remote I/O abstraction.

Question:

How should max_bytes and similar FileTaskHandler parameters be configured in Airflow 3.x with the new RemoteLogIO architecture? Should there be separate config keys for I/O-layer vs handler-layer parameters, or should the current implementation be fixed to properly separate them?

Expected behavior:

Parameters like max_bytes, backup_count and delay should configure the FileTaskHandler instance, while WasbRemoteLogIO receives only its own relevant parameters.

### How to reproduce

Configure remote logging e.g. using WasbFileTaskHandler to upload logs to a blob stroage and add:
[logging]
remote_logging = True
remote_base_log_folder = wasb-<container>://<account>.blob.core.windows.net/<path>
remote_task_handler_kwargs = {"max_bytes": 5000000, "backup_count": 5}

and start application. And check for TypeError during init of the logging system:
TypeError: WasbRemoteLogIO.__init__() got an unexpected keyword argument 'max_bytes'

### Operating System

Debian GNU/Linux 12

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by mango766**
## Summary

When `remote_task_handler_kwargs` is configured with `FileTaskHandler` parameters like `max_bytes`, `backup_count`, or `delay`, these were incorrectly merged into `RemoteLogIO` constructors (S3, GCS, WASB, OSS, HDFS, CloudWatch), causing a `TypeError` because those classes don't accept handler-level parameters. After construction, `remote_task_handler_kwargs` was reset to `{}`, so the `FileTaskHandler` logging config update at the end of the file never received those parameters either.

This fix separates the kwargs upfront into two groups:
- **handler_kwargs**: `FileTaskHandler` parameters (`max_bytes`, `backup_count`, `delay`) applied to `DEFAULT_LOGGING_CONFIG["handlers"]["task"]`
- **remote_io_kwargs**: all other parameters passed to the `RemoteLogIO` constructor

This restores the Airflow 2.x behavior where `remote_task_handler_kwargs` could configure `FileTaskHandler` parameters like log file size limits.

closes: #58770

## Test plan

- [x] Added parametrized unit tests verifying the kwargs separation logic
- [ ] Manual verification: configure `remote_task_handler_kwargs = {"max_bytes": 5000000, "backup_count": 5}` with WASB remote logging and confirm no `TypeError` on startup

---

##### Was generative AI tooling used to co-author this PR?

- [X] Yes — Claude Code (claude-opus-4-6)

Generated-by: Claude Code (claude-opus-4-6) following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)

### CODE REVIEW

**Comment by Vamsi-klu** [comment]
Hey @mango766, nice catch on this one — the double problem (TypeError from RemoteLogIO getting unexpected kwargs + handler params being silently discarded via the `= {}` reset) is a real gotcha. The fix looks solid overall. A couple of things I wanted to flag:

**The tests don't exercise the actual code path.** Right now they re-implement the dictionary splitting logic in the test itself and assert it works — which is really just testing that Python dict comprehensions work. They don't import or execute anything from `airflow_local_settings.py`, so they won't catch wiring issues. Even a simple test that constructs, say, `S3RemoteLogIO` with `max_bytes` as a kwarg and asserts a `TypeError` would demonstrate the bug exists and prove the fix prevents it.

**The `_HANDLER_LEVEL_KWARGS` set is coupled to `FileTaskHandler.__init__`.** If that class ever gains new parameters, this set needs manual updating. Not a blocker since the signature has been stable for years, but maybe a short comment noting the coupling would help future readers.

**Missing newsfragment** — since this is a user-visible bugfix (configuring `remote_task_handler_kwargs` with handler-level params was broken), it should have a newsfragment per project conventions.

**One edge case to consider:** if someone happens to have a custom RemoteLogIO that uses a parameter named `max_bytes`, `backup_count`, or `delay`, those would now get silently routed to the handler config instead. Unlikely in practice, but worth being aware of.

The removal of the `remote_task_handler_kwargs = {}` resets across all branches is a nice cleanup — that pattern was masking the real issue. Good work tracking this down.

**Comment by potiuk** [comment]
@mango766 This PR has been converted to **draft** because it does not yet meet our [Pull Request quality criteria](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-quality-criteria).

**Issues found:**
- :x: **Pre-commit / static checks**: Failing: CI image checks / Static checks. Run `prek run --from-ref main` locally to find and fix issues. See [Pre-commit / static checks docs](https://github.com/apache/airflow/blob/main/contributing-docs/08_static_code_checks.rst).

> **Note:** Your branch is **453 commits behind `main`**. Some check failures may be caused by changes in the base branch rather than by your PR. Please rebase your branch and push again to get up-to-date CI results.

**What to do next:**
- The comment informs you what you need to do.
- Fix each issue, then mark the PR as "Ready for review" in the GitHub UI - but only after making sure that all the issues are fixed.
- There is no rush — take your time and work at your own pace. We appreciate your contribution and are happy to wait for updates.
- Maintainers will then proceed with a normal review.

Converting a PR to draft is **not** a rejection — it is an invitation to bring the PR up to the project's standards so that maintainer review time is spent productively. There is no rush — take your time and work at your own pace. We appreciate your contribution and are happy to wait for updates. If you have questions, feel free to ask on the [Airflow Slack](https://s.apache.org/airflow-slack).

---

_Note: This comment was drafted by an AI-assisted triage tool and may contain mistakes. Once you have addressed the points above, an Apache Airflow maintainer — a real person — will take the next look at your PR. We use this [two-stage triage process](https://github.com/apache/airflow/blob/main/contributing-docs/25_maintainer_pr_triage.md#why-the-first-pass-is-automated) so that our maintainers' limited time is spent where it matters most: the conversation with you._

**Comment by potiuk** [comment]
@mango766 This draft PR has been inactive for 20 days since the last triage comment and no response from the author. Closing to keep the queue clean.

You are welcome to reopen this PR when you resume work, or to open a new one addressing the issues previously raised. There is no rush — take your time.

---

_Note: This comment was drafted by an AI-assisted triage tool and may contain mistakes. Once you have addressed the points above, an Apache Airflow maintainer — a real person — will take the next look at your PR. We use this [two-stage triage process](https://github.com/apache/airflow/blob/main/contributing-docs/25_maintainer_pr_triage.md#why-the-first-pass-is-automated) so that our maintainers' limited time is spent where it matters most: the conversation with you._
