### ISSUE TITLE
Airflow dag parsing error is not refreshed

### ISSUE THREAD

**Issue by NagaSurya11** [apache/airflow#55121]
### Apache Airflow version

3.0.6

### What happened?

On developing a dag i had a compilation error. once i fixed the error in dag it is available for execution. But the error on ui is not cleared.

This issue is found on <= 3.0.4.

### What you think should happen instead?

The errors in dags if fixed it should be cleared.

### How to reproduce

Create a dag with some errors.

Identify in airflow UI.

Fix the error.

Dag will be available for execution. But error message in UI is not cleared

### Operating System

all linux

### Versions of Apache Airflow Providers

3.0.6

i have downgraded each version it is working fine in 3.0.3

### Deployment

Docker-Compose

### Deployment details

official file from airflow documentation 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vatsrahul1001** [comment]
@atul-astronomer can you try to reproduce this in main?

**Comment by atuls4441** [comment]
Not able to reproduce this on latest main, also tried with airflow version 3.0.4 as mentioned by the reporter
@vatsrahul1001

**Comment by vatsrahul1001** [comment]
@NagaSurya11 can you share your DAG ?

**Comment by aayushbisen** [comment]
I also tried to reproduce the issue in main & 3.0.4 branch and it is not happening as described in description.

The DAG I used for triggering error in the UI

<img width="1918" height="995" alt="Image" src="https://github.com/user-attachments/assets/22b3d327-a366-4339-8de2-3b706f93598f" />


It showed the error in the UI

<img width="1918" height="907" alt="Image" src="https://github.com/user-attachments/assets/328047d1-6017-4fdf-a80c-e14f4a3315dd" />

After correcting the error and refreshing the page the DAG was available for execution and the error disappeared

<img width="1918" height="907" alt="Image" src="https://github.com/user-attachments/assets/d812f11a-62f9-412f-8227-0765f74c0685" />

**Comment by NagaSurya11** [comment]
hi @vatsrahul1001  i have organized dags folder as per my organization.

this is the structure 

dags/org/common/….
dags/org/pipelines/….

common folder has custom hooks and operators 

common folder is added in .airflowignore

that is not a problem

but pipelines folder has config.py as well as dag.py

dag.py uses config.py python variables and also some operators on custom

if i done some errors in config.py variables like declaring dict key values with = instead of : 
first time dag is not loaded and shown error

next time i fixed the syntax issues and reloaded the dag the error is not cleared

here config.py is not a dag file which has only variables reproducable in all 3x  versions

if i clear airflow metadata db and restarted the airflow error is cleared if no errors in config.py file

dag.py is working fine if errors in dag.py which is cleared

**Comment by NagaSurya11** [comment]
once i added it under airflow ignore it is working fine. I hope dag processor only scans dag files properly instead of all sub modules
