### PR TITLE
Fix CLI connections import and migrate logic from secrets to Connection model

### LINKED ISSUE #9855: Import connections/variables from a file
Hello,

We have a new local file system secret backend that allows us to load connections and variables from files. We support 3 file formats: YAML, JSON, ENV.
https://airflow.readthedocs.io/en/latest/howto/use-alternative-secrets-backend.html#local-filesystem-secrets-backend
https://github.com/apache/airflow/blob/master/airflow/secrets/local_filesystem.py
I think we can use the same code to create new commands for the CLI that allow us o import connections or variables. 

Best regards,
Kamil

### PR DESCRIPTION
**Pull request by natanweinberger**
This is a bug fix for the CLI command `connections_import`. I originally added this CLI functionality in #15177. The bug was reported by @mudravrik [here](https://github.com/apache/airflow/pull/15177#issuecomment-822056108).

## Bug summary
Running `airflow connections import <filepath>` results in an AttributeError.

```
Traceback (most recent call last):
...
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/connection_command.py", line 244, in connections_import
    _import_helper(args.file)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/connection_command.py", line 272, in _import_helper
    key: value for key, value in conn_values.items() if key in allowed_fields
AttributeError: 'Connection' object has no attribute 'items'
```

## Root cause
I called the existing function `load_connections_dict` to get the contents of the target file, thinking it returned a list of dictionaries. When I later looped through the list, I called the dictionary method `.items()` on each connection. However, each connection was actually stored into a `Connection` model instance rather than a dictionary, so the call I made to `.items()` resulted in an AttributeError.

## Solution
In taking a closer look at this issue, I realized the code block that contained the bug can be removed altogether. Having a list of `Connection` models to begin with (rather than dictionaries) eliminated the need to even examine the keys and values of the dictionaries. I had only done that to safely load the data into `Connection` models in the first place.

## Preventing future issues
To avoid future issues, I also changed how the tests work for providing sample data. Before, a dictionary of sample data was set as the return value of `load_connections_dict`, which actually returns an object of type `List[Connection]`. Now, that dictionary of sample data is set to be the return value of a lower level function, `_parse_secrets_file`, which does no heavy lifting outside of parsing a JSON, YAML or env file and returns a dictionary.

Bug originally introduced in #15177, which closed #9855.

### CODE REVIEW

File: airflow/cli/commands/connection_command.py [hunk 1]
```diff
@@ -29,7 +29,7 @@
 from airflow.exceptions import AirflowNotFoundException
 from airflow.hooks.base import BaseHook
 from airflow.models import Connection
-from airflow.secrets.local_filesystem import _create_connection, load_connections_dict
+from airflow.secrets.local_filesystem import load_connections_dict
```
Comment (mik-laj) [inline airflow/cli/commands/connection_command.py:31]: What do you think to add this method as a static method to the Connection class - `Connection.from_dict`? I don't think CLI should depend on a backend secret.

Comment (mik-laj) [reply airflow/cli/commands/connection_command.py:31]: Ahhh. You don't want to change the visibility of this method, but you are using a different public method. We should therefore still create the `Connection.from_dict` method but as a separate PR.

Comment (natanweinberger) [reply airflow/cli/commands/connection_command.py:31]: Thanks for taking a look. I can add `Connection.from_dict`.

For the implementation, in order to avoid any dependencies on `secrets`, I'll need to move several helper functions. The existing function `load_connections_dict` accepts a filepath and relies on `_parse_secret_file`, which calls `_parse_[json,yaml,env]_file` to read the file contents and deserialize them.

I can either:
- move all these helper functions outside of `secrets/local_filesystem.py` (if so, into a utils file perhaps)
- duplicate the same functionality in the cli module (seems like a bad idea)
- create the method in the Connection class, but still import from `secrets` (doesn't eliminate the dependency)

What do you have in mind?

Comment (mik-laj) [reply airflow/cli/commands/connection_command.py:31]: Yes. We should avoid dependency on secrets. We already have a lot of recursive imports between various connection modules, secret and others, so creating new modules will cure those situations a bit.

> move all these helper functions outside of secrets/local_filesystem.py

I think it is the best solution.

Comment (natanweinberger) [reply airflow/cli/commands/connection_command.py:31]: Sounds good, I'll move this logic elsewhere. Do you still want that as a separate PR then or included in this one?

Comment (mik-laj) [reply airflow/cli/commands/connection_command.py:31]: You can do it in this PR.

**Comment by natanweinberger** [comment]
I've refactored the functionality that reads data from a file and creates connections from it.

- the helper functions to parse JSON, YAML and env files are now located in `airflow/utils/parse.py`
- there is a new method `Connection.from_dict`
- the connections import CLI function uses the util functions and `Connection.from_dict` to import connections from a file

I was as conservative as possible in refactoring the secrets backend in this PR, but it seems like there's not much that uses it. I'd be open to doing some broader clean up there as a follow-up PR.

@mik-laj

File: airflow/cli/commands/connection_command.py (hunk 1 above)
Comment (natanweinberger) [reply airflow/cli/commands/connection_command.py:31]: This change is now implemented.

**Comment by natanweinberger** [comment]
@mik-laj I've incorporated your feedback, can you re-review when you have a chance? 🙏

File: airflow/models/connection.py [hunk 2]
```diff
@@ -364,3 +364,14 @@ def get_connection_from_secrets(cls, conn_id: str) -> 'Connection':
...
+    @classmethod
+    def from_dict(cls, conn_dict: Dict) -> 'Connection':
+        """
+        Create a connection from a dictionary.
+
+        :param conn_dict: dictionary representing a connection's attributes
+            e.g., {'conn_id': '', 'conn_type': '', 'login': '', ...}
+        :return: connection
+        """
+        return Connection(**conn_dict)
```
Comment (mik-laj) [inline airflow/models/connection.py]: We have a function that has a similar purpose but is more complex and supports more input parameters. See: airflow.secrets.local_filesystem._create_connection  Can you move it here?

Comment (natanweinberger) [reply airflow/models/connection.py]: Sure, will do.

Comment (natanweinberger) [reply airflow/models/connection.py]: All set!

File: airflow/utils/parse.py [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+
+
+FILE_PARSERS = {
+    "env": _parse_env_file,
+    "json": _parse_json_file,
+    "yaml": _parse_yaml_file,
+}
+
+
+def _parse_file(file_path: str) -> Dict[str, Any]:
```
Comment (ashb) [inline airflow/utils/parse.py]: Since this is used outside of this module it should be "non-private"

```suggestion
def parse_file(file_path: str) -> Dict[str, Any]:
```

File: airflow/utils/parse.py [hunk 4]
```diff
@@ -0,0 +1,168 @@
...
+    contents_dict, parse_errors = FILE_PARSERS[ext](file_path)
+
+    log.debug(
+        "Parsed file: len(parse_errors)=%d, len(contents_dict)=%d", len(parse_errors), len(contents_dict)
+    )
+
+    if parse_errors:
+        raise AirflowFileParseException(
+            "Failed to load the file.", file_path=file_path, parse_errors=parse_errors
+        )
```
Comment (ashb) [inline airflow/utils/parse.py]: Just make the format specific parsers throw the errors directly?

File: airflow/utils/parse.py [hunk 5]
```diff
@@ -0,0 +1,168 @@
...
+        content = f.read()
+
+    if not content:
+        return {}, [FileSyntaxError(line_no=1, message="The file is empty.")]
+    try:
+        contents_dict = json.loads(content)
+    except JSONDecodeError as e:
+        return {}, [FileSyntaxError(line_no=int(e.lineno), message=e.msg)]
+    if not isinstance(contents_dict, dict):
+        return {}, [FileSyntaxError(line_no=1, message="The file should contain the object.")]
```
Comment (ashb) [inline airflow/utils/parse.py]:
```suggestion
        return {}, [FileSyntaxError(line_no=1, message="The file should contain an object.")]
```

File: airflow/utils/parse.py [hunk 6]
```diff
@@ -0,0 +1,168 @@
...
+    """
+    with open(file_path) as f:
+        content = f.read()
+
+    contents_dict: Dict[str, List[str]] = defaultdict(list)
+    errors: List[FileSyntaxError] = []
+    for line_no, line in enumerate(content.splitlines(), 1):
+        if not line:
+            # Ignore empty line
+            continue
```
Comment (ashb) [inline airflow/utils/parse.py]: This loads the whole file in to memory, which is slightly wasteful. Instead we should do something like this:

```python
    with open(file_path) as f:
        for line_no, line in enumerate(f, 1):
            if not line.strip():
               continue
```

File: airflow/secrets/local_filesystem.py [hunk 7]
```diff
@@ -263,19 +71,32 @@ def load_connections_dict(file_path: str) -> Dict[str, Any]:
...
+            elif secret_values:
+                secret_values = secret_values[0]
+
+        if isinstance(secret_values, dict):
+            connection_by_conn_id[key] = Connection.from_dict(key, secret_values)
+        elif isinstance(secret_values, str):
+            connection_by_conn_id[key] = Connection(uri=secret_values)
         else:
-            connection_by_conn_id[key] = _create_connection(key, secret_values)
+            raise AirflowException(f"Unexpected value type: {type(secret_values)}.")
```
Comment (ashb) [inline airflow/secrets/local_filesystem.py]:
```suggestion
            raise AirflowException(f"Unexpected value type: {type(secret_values).__name__}.")
```

File: airflow/secrets/local_filesystem.py [hunk 8]
```diff
@@ -263,19 +71,32 @@ def load_connections_dict(file_path: str) -> Dict[str, Any]:
...
                 raise ConnectionNotUnique(f"Found multiple values for {key} in {file_path}.")
 
-            for secret_value in secret_values:
-                connection_by_conn_id[key] = _create_connection(key, secret_value)
+            # secret_values must be of length one, so unpack it
+            elif secret_values:
+                secret_values = secret_values[0]
+
+        if isinstance(secret_values, dict):
+            connection_by_conn_id[key] = Connection.from_dict(key, secret_values)
```
Comment (ashb) [inline airflow/secrets/local_filesystem.py]: Do we need a method for this? Isn't it the same as

```suggestion
            connection_by_conn_id[key] = Connection(key, **secret_values)
```

**Review by ashb — CHANGES_REQUESTED** [review]
I'm not that happy about adding more files/modules under airflow.utils (as it's a bit of a dumping ground) but I guess it makes sense here.

**Comment by natanweinberger** [comment]
Hey @ashb, thanks for taking a look! I appreciate it.

I want to point out that most changes here are based on the feedback from @mik-laj above in this PR. I can change or undo some of these things, but it'll be undoing some of the work that was based on that feedback, so I just want to make sure we're all on the same page.

Moving the secrets parsing logic to a utils file: https://github.com/apache/airflow/pull/15425#discussion_r625638195
I haven't changed much (if any) code in the parsing, just moved it to a new file (`utils/parse.py`) so that it's not coupled to the secrets backend. Effectively, copied and pasted. I can commit those suggested changes that improve efficiency or wording of it here though.

Add a method `Connection.from_dict()`: https://github.com/apache/airflow/pull/15425#discussion_r615929569

What do you think? Do you want me to revert anything?

File: airflow/utils/parse.py (hunk 4 above)
Comment (natanweinberger) [reply airflow/utils/parse.py]: No problem for me to do this, but heads up that this is not new code, just cut from `secrets/local_filesystem.py`. Not sure if there was a reason to do it this way when it was originally committed.

File: airflow/utils/parse.py (hunk 6 above)
Comment (natanweinberger) [reply airflow/utils/parse.py]: Same as above. Can do this, but it's existing code from `local_filesystem.py`. Just a heads up in case it had been originally committed this way intentionally, I don't have much context.

File: airflow/secrets/local_filesystem.py (hunk 8 above)
Comment (natanweinberger) [reply airflow/secrets/local_filesystem.py]: Creating a method `Connection.from_dict` was a suggestion from @mik-laj: https://github.com/apache/airflow/pull/15425#discussion_r615929569

File: airflow/secrets/local_filesystem.py (hunk 7 above)
Comment (natanweinberger) [reply airflow/secrets/local_filesystem.py]: ✅

File: airflow/utils/parse.py (hunk 5 above)
Comment (natanweinberger) [reply airflow/utils/parse.py]: ✅

File: airflow/utils/parse.py (hunk 3 above)
Comment (natanweinberger) [reply airflow/utils/parse.py]: ✅

File: airflow/models/connection.py [hunk 9]
```diff
@@ -377,3 +378,50 @@ def get_connection_from_secrets(cls, conn_id: str) -> 'Connection':
...
+                f"Unexpected conn_dict type: {type(conn_dict)}. "
+                "The connection must be defined as a dictionary."
+            )
+
+        connection_parameter_names = cls.get_connection_parameter_names() | {"extra_dejson"}
+        current_keys = set(conn_dict.keys())
+        if not current_keys.issubset(connection_parameter_names):
+            illegal_keys = current_keys - connection_parameter_names
+            illegal_keys_list = ", ".join(sorted(illegal_keys))
+            raise AirflowException(
```
Comment (ashb) [inline airflow/models/connection.py]:
```suggestion
            raise TypeError(
```

File: airflow/models/connection.py [hunk 10]
```diff
@@ -377,3 +378,50 @@ def get_connection_from_secrets(cls, conn_id: str) -> 'Connection':
...
+        """
+        Create a connection from a dictionary.
+
+        :param conn_dict: dictionary representing a connection's attributes
+            e.g., {'conn_id': '', 'conn_type': '', 'login': '', ...}
+        :return: connection
+        """
+        if not isinstance(conn_dict, dict):
+            raise AirflowException(
+                f"Unexpected conn_dict type: {type(conn_dict)}. "
```
Comment (ashb) [inline airflow/models/connection.py]:
```suggestion
            raise TypeError(
                f"Unexpected conn_dict type: {type(conn_dict).__name__}. "
```

File: airflow/models/connection.py [hunk 11]
```diff
@@ -377,3 +378,50 @@ def get_connection_from_secrets(cls, conn_id: str) -> 'Connection':
...
+                "The connection must be defined as a dictionary."
+            )
+
+        connection_parameter_names = cls.get_connection_parameter_names() | {"extra_dejson"}
+        current_keys = set(conn_dict.keys())
+        if not current_keys.issubset(connection_parameter_names):
+            illegal_keys = current_keys - connection_parameter_names
+            illegal_keys_list = ", ".join(sorted(illegal_keys))
+            raise AirflowException(
+                f"The object have illegal keys: {illegal_keys_list}. "
```
Comment (ashb) [inline airflow/models/connection.py]:
```suggestion
                f"The connection dict has illegal keys: {illegal_keys_list}. "
```

**Review by ashb — COMMENTED** [review]
These are just some changes I had pending.

A full review coming on Monday

File: airflow/utils/parse.py (hunk 6 above)
Comment (ashb) [reply airflow/utils/parse.py]: > in case it had been originally committed this way intentionally

Very unlikely to have been intentional.

File: airflow/models/connection.py (hunk 9 above)
Comment (natanweinberger) [reply airflow/models/connection.py]: Agreed with the same change on line 397, but this particular case shouldn't be a TypeError. It indicates that some keys in the dictionary aren't allowed. Maybe it can be a different type of exception though, what do you think?

File: airflow/models/connection.py (hunk 10 above)
Comment (natanweinberger) [reply airflow/models/connection.py]: Implemented 👍

File: airflow/models/connection.py (hunk 11 above)
Comment (natanweinberger) [reply airflow/models/connection.py]: Implemented 👍

File: airflow/utils/parse.py (hunk 6 above)
Comment (natanweinberger) [reply airflow/utils/parse.py]: Ok, will make this change then!

Comment (natanweinberger) [reply airflow/utils/parse.py]: I've been poking around on this and running into an issue with the existing tests.

The tests are using `unittest.mock.mock_open` to patch the call to `open` ([example](https://github.com/apache/airflow/blob/a73ba4b3af65ff392a05fe09f656a91b51401c4d/tests/secrets/test_local_filesystem.py#L36)). This works when you want to mock reading data from a file using `read()` or `readlines()`, which is the existing implementation.

However, `unittest.mock.mock_open` doesn't add compatibility for iterating over the lines of a file lazily until version 3.8. So, the `__iter__` method doesn't properly allow us to read the lines lazily in tests.

See here: https://docs.python.org/3/library/unittest.mock.html#mock-open
```
Changed in version 3.8: Added __iter__() to implementation so that iteration (such as in for loops) correctly consumes read_data.
```

Given that this is a minor enhancement, I'd suggest punting on it for the time being. It will expand the scope of this PR and should be done separately.

File: airflow/models/connection.py (hunk 9 above)
Comment (ashb) [reply airflow/models/connection.py]: Oh, ValueError perhaps then?

Comment (natanweinberger) [reply airflow/models/connection.py]: Sounds good 👍

File: airflow/utils/parse.py [hunk 12]
```diff
@@ -0,0 +1,168 @@
...
+import json
+import logging
+import os
+from collections import defaultdict
+from json import JSONDecodeError
+from typing import Any, Dict, List, Tuple
+
+import airflow.utils.yaml as yaml
+from airflow.exceptions import AirflowException, AirflowFileParseException, FileSyntaxError
+from airflow.utils.file import COMMENT_PATTERN
```
Comment (ashb) [inline airflow/utils/parse.py]:
```suggestion
from airflow.exceptions import AirflowException, AirflowFileParseException, FileSyntaxError
from airflow.utils import yaml
from airflow.utils.file import COMMENT_PATTERN
```

File: airflow/cli/commands/connection_command.py [hunk 13]
```diff
@@ -28,9 +28,9 @@
 from airflow.exceptions import AirflowNotFoundException
 from airflow.hooks.base import BaseHook
 from airflow.models import Connection
-from airflow.secrets.local_filesystem import _create_connection, load_connections_dict
 from airflow.utils import cli as cli_utils, yaml
 from airflow.utils.cli import suppress_logs_and_warning
+from airflow.utils.parse import parse_file
```
Comment (ashb) [inline airflow/cli/commands/connection_command.py]: Hmmmm, I'm not really happy with this module name -- it doesn't _really_ tell me what its doing, not in specific enough terms.

We've already got `airflow.utils.file` that we could include this in -- I think I prefer that over a new file.

"parse_file" is also a bit ambigious, but I can't think of a better name.

File: airflow/secrets/local_filesystem.py (hunk 8 above)
Comment (ashb) [reply airflow/secrets/local_filesystem.py]: Oh, this handles the extra to, which `**secret_values` wouldn't.

**Review by ashb — CHANGES_REQUESTED** [review]
Sorry for not getting around to this pre-2.1.

Why did we even move load_connections_dict from where it was? Your Vault PR doesn't need to use this parsing, so I think this PR would be simpler if we _only_ extract out the `_create_connection` function in to the `Connection.from_dict` and leave the file parsing where it was.

**Comment by ashb** [comment]
And another idea: we possibly don't even need a new `from_dict` method.

Instead we could make the Connection constructor take an `extra_dejson` argument:

```python
    def __init__(  # pylint: disable=too-many-arguments
        self,
        ...
        extra: Optional[str] = None,
        uri: Optional[str] = None,
        extra_dejson: Optional[str] = None,
    ):
        super().__init__()

        ...

        if extra_dejson:
            self.extra = json.dumps(extra_dejson)
```

Though the "de" part of this name is wrong/confusing.

Another options would be to have `Connection()` accept a dict as extra and jsonify it:

```python
    def __init__(  # pylint: disable=too-many-arguments
        self,
        ...
        extra: Union[str,dict] = None,
        uri: Optional[str] = None,

    ):
        super().__init__()

        ...

        if not isinstance(extra, str):
            extra = json.dumps(extra)
```

File: airflow/utils/parse.py (hunk 12 above)
Comment (natanweinberger) [reply airflow/utils/parse.py]: Got rid of utils/parse.py.

File: airflow/cli/commands/connection_command.py (hunk 13 above)
Comment (natanweinberger) [reply airflow/cli/commands/connection_command.py]: Got rid of `utils/parse.py` and left the functionality where it was in `secrets/local_filesystem.py`.

**Comment by natanweinberger** [comment]
@ashb Thanks for the feedback. As we discussed, simplified this PR a lot by reverting some of the changes and focusing on the bugfix.

Here's a summary of the changes:

- the `Connection` constructor handles non-strings in the `extra` kwarg connections import functionality
- the connections import function uses the existing file parsing logic and passes the loaded dicts to `Connection.__init__()`
- fixed a test to catch the issue that slipped through originally (root cause is summarized in the first comment in this PR)

Much simpler!

File: airflow/cli/commands/connection_command.py [hunk 14]
```diff
@@ -238,39 +238,24 @@ def connections_delete(args):
...
-                'port',
-                'uri',
-                'extra_dejson',
-            ]
-            filtered_connection_values = {
-                key: value for key, value in conn_values.items() if key in allowed_fields
-            }
-            connection = _create_connection(conn_id, filtered_connection_values)
+            # Add the connection to the DB
+            connection = Connection(conn_id, **dict(conn_dict.items()))
```
Comment (ashb) [inline airflow/cli/commands/connection_command.py]:
```suggestion
            connection = Connection(conn_id, **conn_dict)
```

File: airflow/cli/commands/connection_command.py [hunk 15]
```diff
@@ -238,39 +238,24 @@ def connections_delete(args):
...
-                'schema',
-                'port',
-                'uri',
-                'extra_dejson',
-            ]
-            filtered_connection_values = {
-                key: value for key, value in conn_values.items() if key in allowed_fields
-            }
-            connection = _create_connection(conn_id, filtered_connection_values)
+            # Add the connection to the DB
```
Comment (ashb) [inline airflow/cli/commands/connection_command.py]: For compat we should add this

```suggestion
            if "extra_dejson" in conn_dict:
                conn_dict["extra"] = conn_dict.pop("extra_dejson")
            # Add the connection to the DB
```

File: airflow/cli/commands/connection_command.py [hunk 16]
```diff
@@ -238,39 +238,24 @@ def connections_delete(args):
...
         _import_helper(args.file)
     else:
         raise SystemExit("Missing connections file.")
 
 
 def _import_helper(file_path):
-    """Helps import connections from a file"""
-    connections_dict = load_connections_dict(file_path)
+    """Load connections from a file and save them to the DB. On collision, skip."""
+    connections_dict = _parse_secret_file(file_path)
```
Comment (ashb) [inline airflow/cli/commands/connection_command.py]: Wait, this shouldn't change, it should still call `load_connections_dict`, but we should change _that_ function to call.


_wait_. Looking at load_connections_dict, I see it is _already_ returning a dict with values of Connection objects!

Did this cli command actually work?!

Comment (natanweinberger) [reply airflow/cli/commands/connection_command.py]: Nope, I introduced a bug at the last minute. The values of the dict were indeed Connection objects, but I was treating them as dictionaries (and my test didn't catch it). I can change this back to `load_connections_dict`, but I thought this was more straightforward.

**Comment by natanweinberger** [comment]
@ashb I've switched back to using `load_connections_dict`, which handles the logic for loading the connection values into the Connection model. So, the import function just loops through the dicts and and adds those to the session and commits them.

This should be very similar now to the first iteration of this PR, just a bugfix for properly treating the `load_connections_dict` result as a `Connection` instance instead of a dict (and updating the tests).

**Comment by ashb** [comment]
> (by the way, taking a closer look at `connections export` function - it will never export a field `extra_dejson`, so it might be ok to let the import function assume it will never be present. It can only be present if someone manually edits the export to include it)

Yeah, some people use connections import as a way to create it, so given that it _used_ to accept it if they manually created the file we should carry on accepting it.

**Review by ashb — APPROVED** [review]
