### PR TITLE
Adding ability to automatically set DAG to off after X times it failed sequentially

### LINKED ISSUE #36239: Add ability to automatically set DAG to off after X times it failed sequentially
### Body

This idea may raise some edge cases but the core concept of it is: If a DAG fails more than X times sequentially then it probably needs some manual action thus there is no point in keeping as active. When running large deployment of Airflow I discovered that many of the DAGs were some experiments/ad hoc/tests that were leftovers and no one noticed or needed.

The value of this feature is that it helps to reduce load from the scheduler and workers. This can be very helpful for large Airflow deployments with many DAG authors that share the same instance.

This should be optional functionality with default as -1 (which means feature is off - for backward compatibility)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by pateash**
closes: #36239

## Description
This PR adds ability to automatically turn off DAG after X number of consecutive failures.

There are 2 ways to configure this
1. in DAG() using **max_consecutive_failed_dag_runs** parameter this will override any config (as below)
2. Using core config inside airflow.cfg or variable AIRFLOW__CORE_MAX_CONSECUTIVE_FAILED_DAG_RUNS_PER_DAG 
environment variable.

### CODE REVIEW

File: airflow/models/dagrun.py [hunk 1]
```diff
@@ -498,6 +498,37 @@ def fetch_task_instances(
...
+        number_of_dag_runs: int,
+        session: Session
+    ):
+        """Check if last N dags failed."""
+        dag_runs = session.query(DagRun).filter(DagRun.dag_id == dag_id) \
+            .order_by(DagRun.execution_date.desc()) \
+            .limit(number_of_dag_runs).all()
+
+        """ Marking dag as paused, if needed"""
+        toBePaused = all(dag_run.state == DagRunState.FAILED for dag_run in dag_runs)
```
Comment (dirrao) [inline airflow/models/dagrun.py]: To ensure the correct behavior, we need to check the count of failures as well.

**Review by dirrao — CHANGES_REQUESTED** [review]
Great work. Can you add the test cases for this feature?

File: airflow/config_templates/config.yml [hunk 2]
```diff
@@ -116,6 +116,15 @@ core:
       type: string
       example: ~
       default: "16"
+    max_failure_runs_per_dag:
```
Comment (BasPH) [inline airflow/config_templates/config.yml]:
```suggestion
    max_consecutive_failed_dag_runs:
```

Would add "consecutive" for clarity

File: airflow/config_templates/config.yml [hunk 3]
```diff
@@ -116,6 +116,15 @@ core:
...
+      description: |
+        The maximum number of consecutive DAG failures before DAG is turned off. The scheduler will disable the DAG
+        if it reaches the limit. This is configurable at the DAG level with ``max_failure_runs``,
+        which is defaulted as ``max_failure_runs_per_dag``.
```
Comment (BasPH) [inline airflow/config_templates/config.yml]:
```suggestion
        The maximum number of consecutive failed DAG runs before a DAG is automatically paused. This is also configurable per DAG with the argument ``max_consecutive_failed_dag_runs``.
```

WDYT of having the same name for the global config and per-DAG config for clarity? This avoids config name sprawl.

File: airflow/models/dag.py [hunk 4]
```diff
@@ -611,12 +614,18 @@ def __init__(
...
         if self.timetable.active_runs_limit is not None:
             if self.timetable.active_runs_limit < self.max_active_runs:
                 raise AirflowException(
                     f"Invalid max_active_runs: {type(self.timetable)} "
                     f"requires max_active_runs <= {self.timetable.active_runs_limit}"
                 )
+        if self.max_failure_runs is not None and self.max_failure_runs < 0:
+            raise AirflowException(
+                f"Invalid max_failure_runs: {str(self.max_failure_runs)}"
+                f"requires max_failure_runs >= 0"
```
Comment (BasPH) [inline airflow/models/dag.py]:
```suggestion
                f"Invalid max_failure_runs: {self.max_failure_runs}. "
                "Requires max_failure_runs >= 0"
```

Don't believe string conversion is required here. Also adding whitespace between sentences + remove unnecessary f-string.

File: airflow/models/dagrun.py [hunk 5]
```diff
@@ -498,6 +498,37 @@ def fetch_task_instances(
             tis = tis.where(TI.task_id.in_(task_ids))
         return session.scalars(tis).all()
 
+    @internal_api_call
+    def _check_last_N_dagruns_failed(
```
Comment (BasPH) [inline airflow/models/dagrun.py]:
```suggestion
    def _check_last_n_dagruns_failed(
```

Just keep everything lowercase

File: airflow/models/dagrun.py [hunk 6]
```diff
@@ -498,6 +498,37 @@ def fetch_task_instances(
...
+        dag_id: str,
+        number_of_dag_runs: int,
+        session: Session
+    ):
+        """Check if last N dags failed."""
+        dag_runs = session.query(DagRun).filter(DagRun.dag_id == dag_id) \
+            .order_by(DagRun.execution_date.desc()) \
+            .limit(number_of_dag_runs).all()
+
+        """ Marking dag as paused, if needed"""
```
Comment (BasPH) [inline airflow/models/dagrun.py:574]:
```suggestion
        """ Marking DAG as paused, if needed"""
```

File: airflow/models/dagrun.py (hunk 1 above)
Comment (BasPH) [inline airflow/models/dagrun.py]:
```suggestion
        to_be_paused = all(dag_run.state == DagRunState.FAILED for dag_run in dag_runs)
```

File: airflow/models/dagrun.py [hunk 7]
```diff
@@ -498,6 +498,37 @@ def fetch_task_instances(
...
+        toBePaused = all(dag_run.state == DagRunState.FAILED for dag_run in dag_runs)
+        if toBePaused:
+            from airflow.models.dag import DagModel
+            self.log.info("Marking Dag %s paused", self.dag_id)
```
Comment (BasPH) [inline airflow/models/dagrun.py]:
```suggestion
            self.log.info("Pausing DAG %s because last %s DAG runs failed.", self.dag_id, number_of_dag_runs)
```

Simplify wording + add rationale for an event, this helps debugging.

File: airflow/models/dagrun.py [hunk 8]
```diff
@@ -498,6 +498,37 @@ def fetch_task_instances(
             tis = tis.where(TI.task_id.in_(task_ids))
         return session.scalars(tis).all()
 
+    @internal_api_call
+    def _check_last_N_dagruns_failed(
+        self,
+        dag_id: str,
+        number_of_dag_runs: int,
```
Comment (BasPH) [inline airflow/models/dagrun.py]: Can we just give this argument the same name as the config to avoid variable naming sprawl? E.g. `max_consecutive_failed_dag_runs`, this helps code readability.

File: airflow/models/dagrun.py [hunk 9]
```diff
@@ -498,6 +498,37 @@ def fetch_task_instances(
...
+                DagModel.root_dag_id == self.dag_id  # for sub-dags
+            ]
+            session.execute(
+                update(DagModel)
+                .where(or_(*filter_query))
+                .values(is_paused=True)
+                .execution_options(synchronize_session="fetch")
+            )
+        else:
+            self.log.info("Limit of consecutive dag failed is not reached, Dag %s is not being paused.",
```
Comment (BasPH) [inline airflow/models/dagrun.py]:
```suggestion
            self.log.info("Limit of consecutive failed DAG runs is not reached, DAG %s will not be paused.",
```

File: airflow/models/dagrun.py [hunk 10]
```diff
@@ -724,6 +755,13 @@ def recalculate(self) -> _UnfinishedStates:
                     msg="task_failure",
                 )
 
+            # checking if the max_failure_runs has been provided and last consecutivate failures are more
```
Comment (BasPH) [inline airflow/models/dagrun.py]:
```suggestion
            # Check if the max_failure_runs has been provided and last consecutive failures are more
```

File: airflow/models/dagrun.py [hunk 11]
```diff
@@ -724,6 +755,13 @@ def recalculate(self) -> _UnfinishedStates:
...
+            # than this number if so we have to mark this dag as off
```
Comment (BasPH) [inline airflow/models/dagrun.py]:
```suggestion
            # than this number if so we have to pause this DAG
```

Lets use the same wording for everything for readability, so instead of "marking off" -> "pausing".

File: airflow/models/dagrun.py [hunk 12]
```diff
@@ -724,6 +755,13 @@ def recalculate(self) -> _UnfinishedStates:
...
+            if bool(dag.max_failure_runs):
+                self.log.info("Checking consecutive failed dags for %s, limit is %s", self.dag_id,
```
Comment (BasPH) [inline airflow/models/dagrun.py]:
```suggestion
                self.log.info("Checking consecutive failed DAG runs for DAG %s, limit is %s", self.dag_id,
```

**Review by BasPH — COMMENTED** [review]
I think this would be a helpful feature. Left a few comments around naming conventions

File: airflow/models/dagrun.py (hunk 1 above)
Comment (pateash) [reply airflow/models/dagrun.py]: We are checking last N dagruns and checking if all the failed,
this will make sure we have the required count.
please highlight if I am missing some edge case here.

Comment (dirrao) [reply airflow/models/dagrun.py]: I am referring to the limit query might give less records. So we need cross check the failed count.

Comment (pateash) [reply airflow/models/dagrun.py]: ohh, yeah
thanks for pointing it out.
fixed this edgecase.

**Comment by pateash** [comment]
### TODO:
- [ ] adding test for core config
- [ ] adding test for environment variable

**Comment by potiuk** [comment]
> The Test failures look like are coming from other changes cc. @eladkal @potiuk

Yes. Usually rebasing helps. Those errors were found and fixed earlier today

**Comment by potiuk** [comment]
This time I rebased it, but you can usually do it yourself without calling maintainers -> generally I recommend to rebase eaarly, often, and especially when you see you are behind and see unrelated errors.

File: airflow/api_connexion/schemas/dag_schema.py [hunk 13]
```diff
@@ -69,6 +69,7 @@ class Meta:
     tags = fields.List(fields.Nested(DagTagSchema), dump_only=True)
     max_active_tasks = auto_field(dump_only=True)
     max_active_runs = auto_field(dump_only=True)
+    max_consecutive_failed_dag_runs = auto_field(dump_only=True)
```
Comment (eladkal) [inline airflow/api_connexion/schemas/dag_schema.py:72]: I wonder about the name. `max_consecutive_failed_dag_runs` might be interpreted as not allowing scheduling after the X failures but this is not really a hard limit - user can override it by enabling the dag. For the other max properties user can't really override them.

**Review by eladkal — COMMENTED** [review]
Looks good!

I have a question about edge case.
Say that I set max_consecutive_failed_dag_runs=3.
After 3 failures the DAG is set to off, if I set it to on manually and the next run also failed what will happen? will it also set the dag to off or the count restart?

Basically the question is if we should count only the failed dags or also take into account events that might rest the count like setting from off to on.

File: airflow/api_connexion/schemas/dag_schema.py (hunk 13 above)
Comment (pateash) [reply airflow/api_connexion/schemas/dag_schema.py:72]: @eladkal,
with current logic,
If a user wants they can manually enable the dag, but if it fails again, then the dag will automatically be disabled, as we are counting last N failed which will again be true.
if user wants to restart counting again, they will have add to add a non-failed dag_run for now.

Comment (pateash) [reply airflow/api_connexion/schemas/dag_schema.py:72]: for naming, 
yeah its a good point.
happy to rename it , please suggest if we can come up with better naming for messaging.

Comment (eladkal) [reply airflow/api_connexion/schemas/dag_schema.py:72]: I need to think about the name.

> if user wants to restart counting again, they will have add to add a non-failed dag_run for now

That might be problematic however I think we can avoid deciding right now.
We can mark this feature as experimintal thus it allows the flexability of changing the behavior if needed.

Comment (amoghrajesh) [reply airflow/api_connexion/schemas/dag_schema.py:72]: I thought a bit about this and what about: `max_allowed_dag_failures_in_row` or just `max_dag_failures_in_row`?

File: airflow/config_templates/config.yml [hunk 14]
```diff
@@ -116,6 +116,17 @@ core:
       type: string
       example: ~
       default: "16"
+    max_consecutive_failed_dag_runs_per_dag:
+      description: |
+        The maximum number of consecutive DAG failures before DAG is automatically paused.
+        This is also configurable per DAG level with ``max_consecutive_failed_dag_runs``,
+        which is defaulted as ``max_consecutive_failed_dag_runs_per_dag``.
+        If not specified, then the value is considered as None,
+        meaning that the dags are never paused out by default.
```
Comment (eladkal) [inline airflow/config_templates/config.yml]: Lets mention this as experimental feature.

We need also:
1. News fragment entry for feature (that gives 2-3 sentences about this capability and explain this is experimental one)
2. Doc entry that explain this feature and explain this is experimental one


After these LGTM

File: airflow/config_templates/config.yml [hunk 15]
```diff
@@ -321,12 +332,12 @@ core:
     default_task_execution_timeout:
       description: |
         The default task execution_timeout value for the operators. Expected an integer value to
-        be passed into timedelta as seconds. If not specified, then the value is considered as None,
+        be passed into timedelta as seconds. If not specified, then the value is considered as 0,
```
Comment (uranusjr) [inline airflow/config_templates/config.yml]: Is this related?

File: airflow/models/dag.py [hunk 16]
```diff
@@ -454,6 +456,7 @@ def __init__(
         concurrency: int | None = None,
         max_active_tasks: int = airflow_conf.getint("core", "max_active_tasks_per_dag"),
         max_active_runs: int = airflow_conf.getint("core", "max_active_runs_per_dag"),
+        max_consecutive_failed_dag_runs: int | None = None,
```
Comment (uranusjr) [inline airflow/models/dag.py]: It’s better to call `getint` here as the default instead. The None type can go away too.

File: airflow/models/dag.py [hunk 17]
```diff
@@ -615,6 +618,16 @@ def __init__(
...
         self.safe_dag_id = dag_id.replace(".", "__dot__")
         self.max_active_runs = max_active_runs
+        self.max_consecutive_failed_dag_runs = max_consecutive_failed_dag_runs
+        if self.max_consecutive_failed_dag_runs is None:
+            self.max_consecutive_failed_dag_runs = airflow_conf.getint(
+                "core", "max_consecutive_failed_dag_runs_per_dag"
+            )
+        if self.max_consecutive_failed_dag_runs < 0:
+            raise AirflowException(
+                f"Invalid max_consecutive_failed_dag_runs: {str(self.max_consecutive_failed_dag_runs)}."
```
Comment (uranusjr) [inline airflow/models/dag.py]:
```suggestion
                f"Invalid max_consecutive_failed_dag_runs: {self.max_consecutive_failed_dag_runs}."
```

File: airflow/models/dag.py [hunk 18]
```diff
@@ -3574,6 +3588,7 @@ class DagModel(Base):
 
     max_active_tasks = Column(Integer, nullable=False)
     max_active_runs = Column(Integer, nullable=True)
+    max_consecutive_failed_dag_runs = Column(Integer, nullable=True)
```
Comment (uranusjr) [inline airflow/models/dag.py]: Don’t need to be nullable.

File: airflow/models/dag.py [hunk 19]
```diff
@@ -3922,6 +3942,7 @@ def dag(
     concurrency: int | None = None,
     max_active_tasks: int = airflow_conf.getint("core", "max_active_tasks_per_dag"),
     max_active_runs: int = airflow_conf.getint("core", "max_active_runs_per_dag"),
+    max_consecutive_failed_dag_runs: int | None = None,
```
Comment (uranusjr) [inline airflow/models/dag.py]: Same

File: airflow/models/dagrun.py [hunk 20]
```diff
@@ -561,6 +561,45 @@ def fetch_task_instances(
...
+            .filter(DagRun.dag_id == dag_id)
+            .order_by(DagRun.execution_date.desc())
+            .limit(max_consecutive_failed_dag_runs)
+            .all()
+        )
+
+        """ Marking dag as paused, if needed"""
+        to_be_paused = len(dag_runs) >= max_consecutive_failed_dag_runs and all(
+            dag_run.state == DagRunState.FAILED for dag_run in dag_runs
+        )
```
Comment (uranusjr) [inline airflow/models/dagrun.py]:
```suggestion
        dag_run_states = session.scalars(
            select(DagRun.state)
            .where(DagRun.dag_id == dag_id)
            .order_by(DagRun.execution_date.desc())
            .limit(max_consecutive_failed_dag_runs)
        ).all()

        to_be_paused = len(dag_runs) >= max_consecutive_failed_dag_runs and all(
            state == DagRunState.FAILED for state in dag_run_states
        )
```

It’s likely possible to not even do the `.all()` part, but let’s keep this simple.

File: airflow/models/dagrun.py [hunk 21]
```diff
@@ -561,6 +561,45 @@ def fetch_task_instances(
...
+                update(DagModel)
+                .where(or_(*filter_query))
+                .values(is_paused=True)
+                .execution_options(synchronize_session="fetch")
+            )
+        else:
+            self.log.info(
+                "Limit of consecutive DAG failed dag runs is not reached, DAG %s will not be paused.",
+                self.dag_id,
+            )
```
Comment (uranusjr) [inline airflow/models/dagrun.py]: I don’t think this should be `info`; `debug` is probably good enough.

File: airflow/models/dagrun.py [hunk 22]
```diff
@@ -561,6 +561,45 @@ def fetch_task_instances(
...
+        )
+
+        """ Marking dag as paused, if needed"""
+        to_be_paused = len(dag_runs) >= max_consecutive_failed_dag_runs and all(
+            dag_run.state == DagRunState.FAILED for dag_run in dag_runs
+        )
+        if to_be_paused:
+            from airflow.models.dag import DagModel
+
+            self.log.warning(
```
Comment (uranusjr) [inline airflow/models/dagrun.py]: This should be `info` since the operation is not inherently a problem in the scheduler.

File: airflow/models/dagrun.py [hunk 23]
```diff
@@ -787,6 +826,16 @@ def recalculate(self) -> _UnfinishedStates:
                     msg="task_failure",
                 )
 
+            # Check if the max_consecutive_failed_dag_runs has been provided and not 0
+            # and last consecutive failures are more
+            if bool(dag.max_consecutive_failed_dag_runs):
```
Comment (uranusjr) [inline airflow/models/dagrun.py]:
```suggestion
            if dag.max_consecutive_failed_dag_runs > 0:
```

File: airflow/models/dagrun.py [hunk 24]
```diff
@@ -787,6 +826,16 @@ def recalculate(self) -> _UnfinishedStates:
...
+                self.log.info(
```
Comment (uranusjr) [inline airflow/models/dagrun.py]: Also shouldn’t be `info` IMO.

Comment (pateash) [reply airflow/models/dagrun.py]: sure, marking this as debug

File: airflow/config_templates/config.yml (hunk 15 above)
Comment (pateash) [reply airflow/config_templates/config.yml]: No, fixed.

File: airflow/config_templates/config.yml [hunk 25]
```diff
@@ -116,6 +116,17 @@ core:
       type: string
       example: ~
       default: "16"
+    max_consecutive_failed_dag_runs_per_dag:
+      description: |
+        The maximum number of consecutive DAG failures before DAG is automatically paused.
```
Comment (eladkal) [inline airflow/config_templates/config.yml]:
```suggestion
        (experimental) The maximum number of consecutive DAG failures before DAG is automatically paused.
```

**Comment by eladkal** [comment]
We are still missing doc entry that explain this feature and explain this is experimental one.
Simply adding a short paragraph about it `DAG pausing, deactivation and deletion` paragraph:
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#dag-pausing-deactivation-and-deletion

File: airflow/config_templates/config.yml [hunk 26]
```diff
@@ -326,7 +337,7 @@ core:
       version_added: 2.3.0
       type: integer
       example: ~
-      default: ""
+      default: None
```
Comment (eladkal) [inline airflow/config_templates/config.yml]: Why did you change this?
It causes tests to fail
`airflow.exceptions.AirflowConfigException: Failed to convert value to int. Please check "default_task_execution_timeout" key in "core" section. Current value: "None".`

Comment (pateash) [reply airflow/config_templates/config.yml]: this is unrelated, reverting back
looks like a merge error.

**Comment by pateash** [comment]
> We are still missing doc entry that explain this feature and explain this is experimental one. Simply adding a short paragraph about it `DAG pausing, deactivation and deletion` paragraph: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#dag-pausing-deactivation-and-deletion

Thanks @eladkal 
added this section here,
image

File: airflow/config_templates/config.yml [hunk 27]
```diff
@@ -116,6 +116,17 @@ core:
...
       example: ~
       default: "16"
+    max_consecutive_failed_dag_runs_per_dag:
+      description: |
+        (experimental) The maximum number of consecutive DAG failures before DAG is automatically paused.
+        This is also configurable per DAG level with ``max_consecutive_failed_dag_runs``,
+        which is defaulted as ``max_consecutive_failed_dag_runs_per_dag``.
+        If not specified, then the value is considered as 0,
+        meaning that the dags are never paused out by default.
+      version_added: ~
```
Comment (eladkal) [inline airflow/config_templates/config.yml]:
```suggestion
      version_added: 2.9.0
```

File: airflow/models/dag.py [hunk 28]
```diff
@@ -364,6 +364,8 @@ class DAG(LoggingMixin):
     :param max_active_runs: maximum number of active DAG runs, beyond this
         number of DAG runs in a running state, the scheduler won't create
         new active DAG runs
+    :param max_consecutive_failed_dag_runs:(experimental) maximum number of consecutive failed DAG runs,
```
Comment (eladkal) [inline airflow/models/dag.py]:
```suggestion
    :param max_consecutive_failed_dag_runs: (experimental) maximum number of consecutive failed DAG runs,
```

**Comment by eladkal** [comment]
Doc build now works
The failing tests are because of breaking main branch due to https://github.com/apache/airflow/pull/38123 once resolving in main rebase should fix it and we should have green build here

**Review by eladkal — APPROVED** [review]
LGTM
Will merge once CI is green

File: airflow/models/dag.py (hunk 28 above)
Comment (eladkal) [reply airflow/models/dag.py]: cc @pateash this missing space is the cause of the failing doc build

**Comment by pateash** [comment]
@eladkal some myPy checks are failing due to issues in azure/cosmos provider
```
airflow/providers/microsoft/azure/hooks/cosmos.py:228: error: Argument
"partition_key" to "create_container" of "DatabaseProxy" has incompatible type
"Optional[str]"; expected "PartitionKey"  [arg-type]
                    collection_name, partition_key=partition_key
                                                   ^~~~~~~~~~~~~
airflow/providers/microsoft/azure/hooks/cosmos.py:339: error: Argument
"partition_key" to "delete_item" of "ContainerProxy" has incompatible type
"Optional[str]"; expected
"Union[str, int, float, bool, Sequence[Union[str, int, float, bool, None]], Type[NonePartitionKeyValue]]"
 [arg-type]
                .delete_item(document_id, partition_key=partition_key)
```

**Comment by eladkal** [comment]
> @eladkal some myPy checks are failing due to issues in azure/cosmos provider
> 
> ```
> airflow/providers/microsoft/azure/hooks/cosmos.py:228: error: Argument
> "partition_key" to "create_container" of "DatabaseProxy" has incompatible type
> "Optional[str]"; expected "PartitionKey"  [arg-type]
>                     collection_name, partition_key=partition_key
>                                                    ^~~~~~~~~~~~~
> airflow/providers/microsoft/azure/hooks/cosmos.py:339: error: Argument
> "partition_key" to "delete_item" of "ContainerProxy" has incompatible type
> "Optional[str]"; expected
> "Union[str, int, float, bool, Sequence[Union[str, int, float, bool, None]], Type[NonePartitionKeyValue]]"
>  [arg-type]
>                 .delete_item(document_id, partition_key=partition_key)
> ```

Fixed in https://github.com/apache/airflow/pull/38175

**Comment by eladkal** [comment]
🎉 🎉 🎉

**Comment by o-nikolas** [comment]
Looks like the diagrams weren't updated along with this migration? When you run precommit locally now, diagram changes are made for code that is unrelated.
