### ISSUE TITLE
Status of testing Providers that were prepared on April 21, 2026

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#65702]
### Body

I have a kind request for all the contributors to the latest provider distributions release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDERS.md#verify-the-release-candidate-by-contributors)

Let us know in the comments, whether the issue is addressed.

These are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 9.26.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/9.26.0rc1)
   - [ ] [fix(amazon): Support AWS China region endpoints in RedshiftSQLHook OpenLineage identifier parsing (#65483)](https://github.com/apache/airflow/pull/65483): @jun09
   - [ ] [Update SecretsManagerBackend to support multi-team (#65395)](https://github.com/apache/airflow/pull/65395): @justinpakzad
     Linked issues:
       - [Linked Issue #65372](https://github.com/apache/airflow/issues/65372): @vincbeck
   - [ ] [Update SystemsManagerParameterStoreBackend to support multi-team (#65396)](https://github.com/apache/airflow/pull/65396): @justinpakzad
     Linked issues:
       - [Linked Issue #65373](https://github.com/apache/airflow/issues/65373): @vincbeck
   - [x] [fix(amazon): correct AWS China SQS regex to use amazonaws.com.cn (#65299)](https://github.com/apache/airflow/pull/65299): @alliasgher
     Linked issues:
       - [Linked Issue #65128](https://github.com/apache/airflow/issues/65128): @crazy-canux
       - [Linked Issue #65173](https://github.com/apache/airflow/pull/65173): @alliasgher
   - [ ] [fix(amazon): extend SQS QUEUE_REGEXP to match AWS China endpoints (#65173)](https://github.com/apache/airflow/pull/65173): @alliasgher
     Linked issues:
       - [Linked Issue #65128](https://github.com/apache/airflow/issues/65128): @crazy-canux
   - [ ] [Update AwsAuthManager to support multi-team #65371 (#65393)](https://github.com/apache/airflow/pull/65393): @haseebmalik18
   - [ ] [fix RedshiftSQLHook._get_conn_params connection mutation with IAM (#64991)](https://github.com/apache/airflow/pull/64991): @justinpakzad
     Linked issues:
       - [Linked Issue #64985](https://github.com/apache/airflow/issues/64985): @iancsg
   - [ ] [Fix SQS CreateQueue type error by casting attributes to string (#65649)](https://github.com/apache/airflow/pull/65649): @mscsy0104
     Linked issues:
       - [Linked Issue #65592](https://github.com/apache/airflow/issues/65592): @nicolamarangoni
## Provider [apache.kafka: 1.13.3rc1](https://pypi.org/project/apache-airflow-providers-apache-kafka/1.13.3rc1)
   - [ ] [Add cleanup to Kafka AwaitMessageTrigger for consumer management (#64612)](https://github.com/apache/airflow/pull/64612): @jason810496
     Linked issues:
       - [Linked Issue #64205](https://github.com/apache/airflow/issues/64205): @spencerhuang
## Provider [celery: 3.19.0rc1](https://pypi.org/project/apache-airflow-providers-celery/3.19.0rc1)
   - [ ] [Add SSL_MUTUAL_TLS config option to Celery provider for one-way TLS support (#64767)](https://github.com/apache/airflow/pull/64767): @dandanseo123
   - [ ] [Widen BaseExecutor method signatures to accept WorkloadKey (#65392)](https://github.com/apache/airflow/pull/65392): @anishgirianish
   - [ ] [Move ExecutorCallback execution into a supervised process (#62645)](https://github.com/apache/airflow/pull/62645): @ferruzzi
## Provider [cncf.kubernetes: 10.16.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/10.16.1rc1)
   - [x] [KPO: treat registry 5xx errors as transient during pod startup (#65490)](https://github.com/apache/airflow/pull/65490): @potiuk
   - [ ] [Fix KubernetesPodOperator to forward pod log levels to Airflow task logs (#64829)](https://github.com/apache/airflow/pull/64829): @Vishwaspatel2401
     Linked issues:
       - [Linked Issue #64820](https://github.com/apache/airflow/issues/64820): @barunpuri
   - [ ] [Catch TypeError for non-datetime since_time in _write_logs (#65232)](https://github.com/apache/airflow/pull/65232): @karenbraganz
   - [ ] [Do not cache kubeconfig for exec based auth in AsyncKubernetesHook (#65212)](https://github.com/apache/airflow/pull/65212): @amoghrajesh
   - [ ] [Consider XCOM sidecar container during pod cleanup (#64962)](https://github.com/apache/airflow/pull/64962): @wolfdn
   - [ ] [Kubernetes Pod Operator: handle unknown pod phase (#65202)](https://github.com/apache/airflow/pull/65202): @johnhoran
   - [ ] [Allow string conversion to datetime for since_time in KPO logs (#65498)](https://github.com/apache/airflow/pull/65498): @karenbraganz
     Linked issues:
       - [Linked Issue #65232](https://github.com/apache/airflow/pull/65232): @karenbraganz
## Provider [common.ai: 0.1.1rc1](https://pypi.org/project/apache-airflow-providers-common-ai/0.1.1rc1)
   - [x] [fix: update dependencies to fix dependabot alarms in providers.common.ai (#65048)](https://github.com/apache/airflow/pull/65048): @jscheffl
## Provider [common.sql: 1.35.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.35.0rc1)
   - [ ] [Add `accept_none` to `SQLTableCheckOperator` (#63210)](https://github.com/apache/airflow/pull/63210): @jroachgolf84
     Linked issues:
       - [Linked Issue #30082](https://github.com/apache/airflow/issues/30082): @mag3141592
## Provider [databricks: 7.13.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/7.13.0rc1)
   - [ ] [Implement on_kill() trigger hook for Databricks triggers (#65672)](https://github.com/apache/airflow/pull/65672): @amoghrajesh
   - [x] [Cleanup databricks docs for `DatabricksWorkflowTaskGroup` (#65135)](https://github.com/apache/airflow/pull/65135): @eladkal
## Provider [edge3: 3.5.0rc1](https://pypi.org/project/apache-airflow-providers-edge3/3.5.0rc1)
   - [x] [Add extended sysinfo for Edge worker (#65472)](https://github.com/apache/airflow/pull/65472): @jscheffl
   - [ ] [Add the bulk support for maint and exit maint mode for edge worker (#65015)](https://github.com/apache/airflow/pull/65015): @shubhamraj-git
   - [x] [Bugfix/bump vite to 8 in edge fix (#65387)](https://github.com/apache/airflow/pull/65387): @jscheffl
   - [x] [Bump vite in Edge Provider to 8.0 (#65175)](https://github.com/apache/airflow/pull/65175): @jscheffl
   - [ ] [Move ExecutorCallback execution into a supervised process (#62645)](https://github.com/apache/airflow/pull/62645): @ferruzzi
   - [x] [Keep DualStatsManager as a try/except import as it is soon going to be removed (#65676)](https://github.com/apache/airflow/pull/65676): @ashb
     Linked issues:
       - [Linked Issue #65472](https://github.com/apache/airflow/pull/65472): @jscheffl
       - [Linked Issue #63932](https://github.com/apache/airflow/pull/63932): @xBis7
## Provider [elasticsearch: 6.5.3rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/6.5.3rc1)
   - [ ] [Strip userinfo from OpenSearch host URL before using it as task-log label (#65509)](https://github.com/apache/airflow/pull/65509): @potiuk
     Linked issues:
       - [Linked Issue #65349](https://github.com/apache/airflow/pull/65349): @potiuk
   - [ ] [Strip userinfo from ES host URL before using it as task-log label (#65349)](https://github.com/apache/airflow/pull/65349): @potiuk
   - [ ] [Fix elasticsearch provider to use SDK imports for Airflow 3.2+ (#64931)](https://github.com/apache/airflow/pull/64931): @potiuk
## Provider [fab: 3.6.2rc1](https://pypi.org/project/apache-airflow-providers-fab/3.6.2rc1)
   - [x] [fix(fab): use naming_convention for 02ca36b0235b batch_alter_table on SQLite (#65540)](https://github.com/apache/airflow/pull/65540): @Lee-W
   - [ ] [fix: invalidate cached user permissions after LDAP role sync to prevent intermittent 403s (#64539)](https://github.com/apache/airflow/pull/64539): @Pranaykarvi
     Linked issues:
       - [Linked Issue #64533](https://github.com/apache/airflow/issues/64533): @vikrams12
   - [ ] [fix(providers/fab): lazily initialize flask_app in FastAPI routes (#64908)](https://github.com/apache/airflow/pull/64908): @kalluripradeep
     Linked issues:
       - [Linked Issue #64418](https://github.com/apache/airflow/pull/64418): @kalluripradeep
       - [Linked Issue #64151](https://github.com/apache/airflow/issues/64151): @barunpuri
   - [ ] [Fix duplicate Date headers in Flask WSGI responses (#64726)](https://github.com/apache/airflow/pull/64726): @abhijeets25012-tech
## Provider [google: 21.2.0rc1](https://pypi.org/project/apache-airflow-providers-google/21.2.0rc1)
   - [x] [Add quota project id support to Google cloud base hook (#56324)](https://github.com/apache/airflow/pull/56324): @Ankurdeewan
   - [x] [Return list of destination URIs from S3ToGCSOperator (#64851)](https://github.com/apache/airflow/pull/64851): @yuseok89
     Linked issues:
       - [Linked Issue #11323](https://github.com/apache/airflow/issues/11323): @FHoffmannCode
   - [x] [Fix passing labels from Airflow connections to BQ jobs (#65663)](https://github.com/apache/airflow/pull/65663): @VladaZakharova
   - [x] [Fix Google Dataflow hook failing import when apache-beam not installed (#65659)](https://github.com/apache/airflow/pull/65659): @shahar1
   - [x] [Rename Cloud Composer service in the operator docs (#64257)](https://github.com/apache/airflow/pull/64257): @olegkachur-e
   - [x] [Add TPC (Trusted Partner Cloud) guidance for Compute SSH (#65662)](https://github.com/apache/airflow/pull/65662): @VladaZakharova
## Provider [hashicorp: 4.6.0rc1](https://pypi.org/project/apache-airflow-providers-hashicorp/4.6.0rc1)
   - [x] [Add multi team secret support to VaultBackend (#65493)](https://github.com/apache/airflow/pull/65493): @stephen-bracken
     Linked issues:
       - [Linked Issue #65372](https://github.com/apache/airflow/issues/65372): @vincbeck
## Provider [jdbc: 5.4.4rc1](https://pypi.org/project/apache-airflow-providers-jdbc/5.4.4rc1)
   - [x] [Set per-Python-version lower bounds for jpype1 in JDBC provider (#65572)](https://github.com/apache/airflow/pull/65572): @potiuk
     Linked issues:
       - [Linked Issue #65532](https://github.com/apache/airflow/pull/65532): @potiuk
   - [x] [Work around jpype1 1.7.0 missing macOS arm64 wheels in jdbc provider (#65532)](https://github.com/apache/airflow/pull/65532): @potiuk
## Provider [microsoft.azure: 13.1.2rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/13.1.2rc1)
   - [ ] [Fix Azure provider hooks ignoring cloud_environment connection extra (#65320)](https://github.com/apache/airflow/pull/65320): @sfirke
     Linked issues:
       - [Linked Issue #65319](https://github.com/apache/airflow/issues/65319): @sfirke
## Provider [openlineage: 2.15.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/2.15.0rc1)
   - [x] [feat: Add rendered map_index template to OL events (#65529)](https://github.com/apache/airflow/pull/65529): @kacpermuda
   - [x] [Fix DetachedInstanceError in OpenLineage listener when accessing DagRun note (#65579)](https://github.com/apache/airflow/pull/65579): @Subham-KRLX
     Linked issues:
       - [Linked Issue #65577](https://github.com/apache/airflow/issues/65577): @alamashir
## Provider [opensearch: 1.9.1rc1](https://pypi.org/project/apache-airflow-providers-opensearch/1.9.1rc1)
   - [ ] [Strip userinfo from OpenSearch host URL before using it as task-log label (#65509)](https://github.com/apache/airflow/pull/65509): @potiuk
     Linked issues:
       - [Linked Issue #65349](https://github.com/apache/airflow/pull/65349): @potiuk
   - [ ] [Fix opensearch provider to use SDK imports for Airflow 3.2+ (#65076)](https://github.com/apache/airflow/pull/65076): @wjddn279
   - [ ] [Document OpenSearch logging override needed on Airflow 3.0.0 – 3.2.0 (#65209)](https://github.com/apache/airflow/pull/65209): @potiuk
## Provider [papermill: 3.13.0rc1](https://pypi.org/project/apache-airflow-providers-papermill/3.13.0rc1)
   - [x] [Support `log_output` for PapermillOperator (#65170)](https://github.com/apache/airflow/pull/65170): @nailo2c
     Linked issues:
       - [Linked Issue #35408](https://github.com/apache/airflow/issues/35408): @wno-xyt
## Provider [sendgrid: 4.2.3rc1](https://pypi.org/project/apache-airflow-providers-sendgrid/4.2.3rc1)
   - [ ] [Bump sendgrid>=6.12.5 (#65635)](https://github.com/apache/airflow/pull/65635): @eladkal
## Provider [sftp: 5.7.4rc1](https://pypi.org/project/apache-airflow-providers-sftp/5.7.4rc1)
   - [ ] [Add Vespa provider (#63988)](https://github.com/apache/airflow/pull/63988): @radu-gheorghe
## Provider [smtp: 3.0.0rc1](https://pypi.org/project/apache-airflow-providers-smtp/3.0.0rc1)
   - [x] [Validate SMTP server certificate on STARTTLS upgrade (#65346)](https://github.com/apache/airflow/pull/65346): @potiuk
## Provider [snowflake: 6.12.2rc1](https://pypi.org/project/apache-airflow-providers-snowflake/6.12.2rc1)
   - [ ] [Fix ``SnowflakeHook`` transaction support: multi-statement SQL and `AUTOCOMMIT` (#65040)](https://github.com/apache/airflow/pull/65040): @kaxil
     Linked issues:
       - [Linked Issue #48233](https://github.com/apache/airflow/issues/48233): @set92
   - [ ] [Mark Snowflake connection form `Proxy Port` field optional (#65444)](https://github.com/apache/airflow/pull/65444): @nikhilcss97
     Linked issues:
       - [Linked Issue #65443](https://github.com/apache/airflow/issues/65443): @nikhilcss97
       - [Linked Issue #62116](https://github.com/apache/airflow/pull/62116): @amoghrajesh
       - [Linked Issue #59078](https://github.com/apache/airflow/issues/59078): @mansfieldj3
       - [Linked Issue #60432](https://github.com/apache/airflow/pull/60432): @mansfieldj3
       - [Linked Issue #63486](https://github.com/apache/airflow/issues/63486): @mansfieldj3
## Provider [ssh: 5.0.1rc1](https://pypi.org/project/apache-airflow-providers-ssh/5.0.1rc1)
   - [ ] [Add Vespa provider (#63988)](https://github.com/apache/airflow/pull/63988): @radu-gheorghe

## Provider [vespa: 0.1.0rc1](https://pypi.org/project/apache-airflow-providers-vespa/0.1.0rc1) **:tada: New provider**
   - [x] Initial release does not list PR references in changelog. Please run smoke tests.

All users involved in the PRs:
@nailo2c @ashb @Vishwaspatel2401 @shubhamraj-git @alliasgher @sfirke @haseebmalik18 @VladaZakharova @kalluripradeep @wolfdn @nikhilcss97 @abhijeets25012-tech @yuseok89 @jroachgolf84 @justinpakzad @radu-gheorghe @olegkachur-e @dandanseo123 @amoghrajesh @Pranaykarvi @Ankurdeewan @kacpermuda @wjddn279 @eladkal

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by shahar1** [comment]
@radu-gheorghe  @thomasht86 - please make sure that Vespa provider is ready :)

**Comment by aaron-y-chen** [comment]
Hi, I've tested my part of the change (#65170), and it looks good :)

**Comment by Subham-KRLX** [comment]
I tested my fix (#65579) for the OpenLineage provider the safe_getattr logic is working as expected and handles the DetachedInstanceError when accessing note or deadlines on detached objects this should stop the listener crashes we were seeing in Airflow 3.2+. Looks good for the 2.15.0rc1 release!

**Comment by radu-gheorghe** [comment]
Hi. Thanks for the nudge!

Since it's the first time I do this, allow me to be verbose :) 

I've started Airflow like so:
```
breeze start-airflow --use-airflow-version 3.2.0 --python 3.12 --backend postgres \
    --load-example-dags --load-default-connections
```

Then installed the Vespa provider in it:
```
pip install apache-airflow-providers-vespa==0.1.0rc1
```

Then restarted everything, logged into the UI, created a Vespa connection that pointed to a local Vespa, ran the example DAG (which is a reasonable smoke test for everything), worked.

Is this OK, or should I do other things as well? Like the sftp and ssh providers which are touched by my PR?

**Comment by kacpermuda** [comment]
#65529 working well, thanks

**Comment by VladaZakharova** [comment]
Google provider is tested and working good
**+1 for Google**

**Comment by stephen-bracken** [comment]
No issues with #65493 , thanks

**Comment by jscheffl** [comment]
Tested all my contributions, looks good!

**Comment by alliasgher** [comment]
Tested #65299 against 9.26.0rc1, AWS China regex works as expected. +1.

**Comment by Lee-W** [comment]
Tested #65540 and the migration finally works now.

**Comment by anishgirianish** [comment]
Tested Celery 3.19.0rc1,  task are failing on airflow 3.2.0 with `ImportError: cannot import name 'ExecutorWorkload' from 'airflow.executors.workloads'` at celery_executor_utils.py:213. Both `ExecutorWorkload` and `BaseExecutor.run_workload` only exist on main (3.3+),  but the gate is `AIRFLOW_V_3_2_PLUS`, regression from #62645. Fix in #65752.  

cc: @ferruzzi  @shahar1

**Comment by mscsy0104** [comment]
I have tested and verified Amazon Provider (9.26.0rc1).

- Checks: Signature, Checksum, and RAT check passed.
- Functional Test: Successfully installed and ran example DAGs in Breeze (Python 3.13).
- Compatibility: Confirmed it works fine in Python 3.13 as requested in the issue.

Thanks!

**Comment by potiuk** [comment]
> Is this OK, or should I do other things as well? Like the sftp and ssh providers which are touched by my PR?

All good there :)

**Comment by shahar1** [comment]
> Tested Celery 3.19.0rc1,  task are failing on airflow 3.2.0 with `ImportError: cannot import name 'ExecutorWorkload' from 'airflow.executors.workloads'` at celery_executor_utils.py:213. Both `ExecutorWorkload` and `BaseExecutor.run_workload` only exist on main (3.3+),  but the gate is `AIRFLOW_V_3_2_PLUS`, regression from #62645. Fix in #65752.  
> 
> cc: @ferruzzi  @shahar1  

Thanks! Excluding celery from this release, RC2 will include the patch.

**Comment by justinpakzad** [comment]
Shortly after #65395 and #65396 were merged, it was pointed out that there could be a potential security concern where a caller without team context could access the team variables/connections. I opened a PR (#65703) to address those issues.

**Comment by molcay** [comment]
Hi,
Since RC2 also completed, can we close this one as well?
