### ISSUE TITLE
Wasb connection to Azure Fileshareservice Hook not working

### ISSUE THREAD

**Issue by cvsekhar** [apache/airflow#16254]
**Apache Airflow version**: 
Version: v2.1.0
Git Version: .release:2.1.0+304e174674ff6921cb7ed79c0158949b50eff8fe

**What happened**:
INFO - __init__() got an unexpected keyword argument 'extra__wasb__connection_string'

**What you expected to happen**:
We have used the extra field and populated the SAS token according to the documents on how to use wasb connection for fileshare and we should be able to login in using the SAS token. This has been working in 2.0.0

<img width="416" alt="airflow_bug" src="https://user-images.githubusercontent.com/1429314/120696017-a85dcc00-c471-11eb-925d-05794e33d40b.png">

**Comment by cvsekhar** [comment]
When we try to enter key-value pairs in JSON format for file service in the wasb connection those key-value pairs are not being stored and get replaced with {"extra__wasb__connection_string": "", "extra__wasb__sas_token": "", "extra__wasb__shared_access_key": "", "extra__wasb__tenant_id": ""}

**Comment by potiuk** [comment]
When using the UI, you should not configure extras but you can now place the values in the right fields - instead of manually adding "extras" via JSON dict: 

You have those fields (as you can see in your screenshot):
 
* SAS token
* Tenant ID
* Shared access key 

Which should be used for that purpose.

This has been fixed in The Microsoft Azure Provider 2.0.0 (as a breaking change):

https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html#id1

The detailed commit:
https://github.com/apache/airflow/commit/1a85ba9e93d44601a322546e31814bd9ef11c125

**Comment by potiuk** [comment]
Closing for now unless it does not solve your problem (please let us know if it did/did not).

**Comment by cvsekhar** [comment]
This has not addressed the issue, I was using those fields and getting an error when I try to use this hook. 

<img width="697" alt="filesharehook" src="https://user-images.githubusercontent.com/1429314/121081223-05bf8900-c7a2-11eb-9958-3727e40815f0.png">

**Comment by cvsekhar** [comment]
Can you help me as the wasb connection with those fields is not working for fileshare.

**Comment by potiuk** [comment]
OK. I see the problem @cvsekhar . It seems that the AzureFileServerHook was wrongly defined and the way extras were used there was wrong. Passing extras this way is not how airlfow works with connection extras - all extras are always prefixed with `extra__conn__`  and your extras (and they way how the FileServerHook works). 

The AzureFileServerHook has been missing in the change and it does not rally work the same way - on one hand you have no dedicated hook, and on the other hand - the other "Azure" related hooks have some extras defined which are not properly configured. 

There are few ways you can mitigate the problem:

1) downgrade apache-airflow-providers-microsoft-azure to 1.3.0  - that is the most "certain" fix for you I think.

2) You can try to use the "Azure" connection instead in 2.0.0. Though it will likely fail with "extra__azure__tenantId" missing - looking at the code.

3) As a quick workaround, you should be able to use any "generic" connection. For example you can use HTTP connection and fill in the extras the way you used it. It **should** work just fine (though it is an abuse of how Airlfow connections work). This is probably the "fastest" workaround if it works for you

Let me know if those work.

In the meantime I might implement a quick fix - I am just about to release a new version of all providers but I think I can quickly fix this one in that upcoming version. I will ask you to test the RC version then OK ?

**Comment by cvsekhar** [comment]
Sure will test the RC
