### PR TITLE
Import ldap.filter in security_manager override

### LINKED ISSUE #68224: LDAP Giving 500 Error
### Under which category would you file this issue?

Providers

### Apache Airflow version

3.2.2

### What happened and how to reproduce it?

When configuring LDAP authentication in Airflow 3, login attempts failed with an exception indicating that the ldap.filter module could not be found. The LDAP provider code imports and uses ldap.filter.escape_filter_chars(), but the ldap.filter submodule is not automatically imported by the python-ldap package in some environments.

As a result, LDAP authentication fails even though the python-ldap package is installed and functional.

Additionally, it was working on 3.6.2 but not working for 3.6.5

### How to reproduce it?

1. Install Airflow 3 with LDAP authentication enabled.
2. Install python-ldap (e.g. version 3.4.7).
3. Configure LDAP authentication according to the Airflow documentation.
4. Start the Airflow webserver.
5. Attempt to log in using an LDAP user.
6. Observe that authentication fails with:
`AttributeError: module 'ldap' has no attribute 'filter'`

The issue is resolved by explicitly importing ldap.filter before LDAP authentication code is executed. This suggests the provider should explicitly import ldap.filter rather than assuming it is available as an attribute of the ldap module.

### What you think should happen instead?

LDAP authentication should work successfully when the supported python-ldap package is installed and configured correctly.

The LDAP provider should explicitly import any required submodules (such as ldap.filter) instead of assuming they are automatically available as attributes of the top-level ldap package.

If a required dependency is missing, Airflow should fail gracefully with a clear error message indicating the missing module, rather than raising:

AttributeError: module 'ldap' has no attribute 'filter'

Users should be able to configure and use LDAP authentication following the documented setup steps without needing to manually modify provider code or add additional imports.

### Operating System

Rocky linux

### Deployment

Virtualenv installation

### Apache Airflow Provider(s)

fab

### Versions of Apache Airflow Providers

3.6.5

### Official Helm Chart version

Not Applicable

### Kubernetes Version

_No response_

### Helm Chart configuration

_No response_

### Docker Image customizations

_No response_

### Anything else?

# webserver.py (redacted)

from airflow.providers.fab.auth_manager.auth_manager import FabAuthManager

AUTH_TYPE = AUTH_LDAP

AUTH_LDAP_SERVER = "ldaps://ldap.example.com"
AUTH_LDAP_SEARCH = "OU=Users,DC=example,DC=com"
AUTH_LDAP_BIND_USER = "svc.airflow"
AUTH_LDAP_BIND_PASSWORD = "***REDACTED***"

SECURITY_MANAGER_CLASS = "CustomSecurityManager"

# Login fails with:
# AttributeError: module 'ldap' has no attribute 'filter'

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by litesh1998**
### Fix LDAP login failure caused by missing `ldap.filter` import

closes: #68224

When LDAP authentication is enabled, Airflow may return a 500 Internal Server Error during login.

The failure occurs in the LDAP search path where `ldap.filter.escape_filter_chars()` is called without importing the `ldap.filter` submodule first. With recent versions of `python-ldap`, importing `ldap` alone does not automatically expose the `filter` module, resulting in:

```python
AttributeError: module 'ldap' has no attribute 'filter'
```

This change explicitly imports `ldap.filter` before it is used by the LDAP authentication flow.

### Reproduction

1. Configure Airflow with LDAP authentication.
2. Install a recent version of `python-ldap` (e.g. 3.4.7).
3. Attempt to log in using an LDAP user.
4. Airflow returns HTTP 500 with:

```python
AttributeError: module 'ldap' has no attribute 'filter'
```

### Root Cause

`ldap.filter.escape_filter_chars()` is referenced during LDAP user lookup, but the `ldap.filter` module is not imported. Recent versions of `python-ldap` require the submodule to be imported explicitly.

### Fix

Import `ldap.filter` before using `ldap.filter.escape_filter_chars()`.

### Testing

* Reproduced the issue on:

  * Apache Airflow 3.2.2
  * apache-airflow-providers-fab 3.6.5
  * python-ldap 3.4.7
  * Python 3.12

* Verified that LDAP authentication succeeds after the change.

* Verified that the 500 Internal Server Error no longer occurs during login.

### CODE REVIEW

**Review by vincbeck — APPROVED** [review]

**Comment by dheerajturaga** [comment]
I just hit this issue on 3.2.2. Thanks for the fix @litesh1998 and congrats on your first contribution!
