### PR TITLE
Load Example Plugins with Example DAGs

### PR DESCRIPTION
**Pull request by jscheffl**
I noticed that we have some example plugins we ship in our source code, but so far we are limited not being able to "eat our own dog-food" with the example DAGs. Plugins so far needed to be deployed by deployment manager.

This PR improves the plugin manager slightly in the way that plugins contained in example DAGs folder in source are loaded as well when example DAGs are loaded.

This enables us(in separate PRs in future... soon?) to really use timetables in the example DAGs and not only have code examples linked in documentation.

FYI @hussein-awala I remember you also had a hard time making an example working in our PR #36029

### CODE REVIEW

**Comment by potiuk** [comment]
Some serialization tests are failing but I like it :)

File: tests/plugins/workday.py [hunk 1]
```diff
@@ -23,6 +23,9 @@
 
 from __future__ import annotations
 
-from airflow.example_dags.plugins.workday import AfterWorkdayTimetable, WorkdayTimetablePlugin
+from airflow.example_dags.plugins.workday import (
+    AfterWorkdayTimetable as TestAfterWorkdayTimetable,
+    WorkdayTimetablePlugin as TestWorkdayTimetablePlugin,
+)
```
Comment (uranusjr) [inline tests/plugins/workday.py]: Why are these renames needed?

Comment (jscheffl) [reply tests/plugins/workday.py]: That renaming was needed as in my first commit the serialization failed with error:
`airflow.exceptions.SerializationError: Failed to serialize DAG 'example_workday_timetable': Timetable class 'workday.AfterWorkdayTimetable' is not registered or you have a top level database access that disrupted the session. Please check the airflow best practices documentation.`

See first pipeline run in https://github.com/apache/airflow/actions/runs/9333722920/job/25691073318

If you have a "better" idea or know why the serialization test failed if the name from the re-import fails when examples are loaded as well... seems to be a clash in serialization somewhere.

Comment (jscheffl) [reply tests/plugins/workday.py]: Okay, in the attempt to fix all problems with pytests I reverted this and moved the examples and the test base all to example DAGs, this is no needed anymore.

File: tests/cli/commands/test_dag_command.py [hunk 2]
```diff
@@ -425,37 +425,37 @@ def test_cli_backfill_depends_on_past_run_backwards(self, mock_run, cli_arg: str
...
         start_date = DEFAULT_DATE + timedelta(days=1)
         end_date = start_date + timedelta(days=1)
-        workdays = [
+        mock_next_workday = [
             start_date,
             start_date + timedelta(days=1),
             start_date + timedelta(days=2),
         ]
-        mock_get_next_workday.side_effect = workdays
+        from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
```
Comment (jscheffl) [inline tests/cli/commands/test_dag_command.py:443]: Need to change decorator to load patch on manually imported module inside the pytest. don't ask me why but with the decorator as it was before it gets a `AttributeError: module 'airflow.example_dags.plugins' has no attribute 'workday'` in Python 3.8 - works in 3.12...

**Review by potiuk — APPROVED** [review]
LGTM. @uranusjr ?

File: airflow/plugins_manager.py [hunk 3]
```diff
@@ -262,28 +264,38 @@ def load_plugins_from_plugin_directory():
...
-            log.debug("Importing plugin module %s", file_path)
-
-            for mod_attr_value in (m for m in mod.__dict__.values() if is_valid_plugin(m)):
-                plugin_instance = mod_attr_value()
-                plugin_instance.source = PluginsDirectorySource(file_path)
-                register_plugin(plugin_instance)
-        except Exception as e:
-            log.exception("Failed to import plugin %s", file_path)
-            import_errors[file_path] = str(e)
+        example_plugins_folder = next(iter(plugins.__path__))
```
Comment (uranusjr) [inline airflow/plugins_manager.py:274]: Is the example plugins folder guaranteed to be the first item? Not sure where that came from. Not I’m surprised it is, just that retrieving it this way seems a bit too magical.

**Review by uranusjr — APPROVED** [review]
Looks good to me, one minor thought.

File: airflow/plugins_manager.py (hunk 3 above)
Comment (potiuk) [reply airflow/plugins_manager.py:274]: It's the only one I think :). Plugins is imported one line above `from airflow.example_dags` - so I believe it will always be single-element array.

Comment (potiuk) [reply airflow/plugins_manager.py:274]: (Which BTW migh be cleaner as `plugins.__path__[0]` indeed.

Comment (jscheffl) [reply airflow/plugins_manager.py:274]: Yes, exactly. I made it like this to prevent mypy and other linter complaints and did not want to loop over an array with a single element.

**Comment by zachliu** [comment]
Sorry for commenting on a merged PR. Just wanna make sure this is a real issue before i create an issue :sweat_smile: 

The PR does make sure the plugin is loaded when `load_examples = True`. And the DAG itself runs ok. No loading errors or anything. The UI -> Admin -> Plugins shows the 3 plugins from the `example_dags/plugins`

However, both the `sync-perm` cli and the `plugins` cli don't agree with it. When executing `airflow sync-perm --include-dags -v`, it always errors out on this example dag:
```
{serialized_dag.py:200} DEBUG - Deserializing DAG: example_workday_timetable
{plugins_manager.py:351} DEBUG - Plugins are already loaded. Skipping.
{plugins_manager.py:484} DEBUG - Initialize extra timetables plugins
{cli_action_loggers.py:98} DEBUG - Calling callbacks: []
Traceback (most recent call last):
  File "/usr/local/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/fab/auth_manager/cli_commands/sync_perm_command.py", line 39, in sync_perm
    appbuilder.sm.create_dag_specific_permissions()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1072, in create_dag_specific_permissions
    dagbag.collect_dags_from_db()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 628, in collect_dags_from_db
    self.dags = SerializedDagModel.read_all_dags()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/serialized_dag.py", line 201, in read_all_dags
    dag = row.dag
          ^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/serialized_dag.py", line 235, in dag
    return SerializedDAG.from_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/serialization/serialized_objects.py", line 1776, in from_dict
    return cls.deserialize_dag(serialized_obj["dag"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/serialization/serialized_objects.py", line 1704, in deserialize_dag
    v = decode_timetable(v)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/serialization/serialized_objects.py", line 329, in decode_timetable
    raise _TimetableNotRegistered(importable_string)
airflow.serialization.serialized_objects._TimetableNotRegistered: Timetable class 'airflow.example_dags.plugins.workday.AfterWorkdayTimetable' is not registered or you have a top level database access that disrupted the session. Please check the airflow best practices documentation.
```
and when executing `airflow plugins -o table -v`, the 3 plugins from `example_dags/plugins` are not in the output table.

of course if I set `load_examples = False`, the `sync-perm` and `plugin` work fine without any errors

the only way that I can run both this example and the cli commands is:
1. copy the source code `airflow/example_dags/plugins/workday.py` to my own `airflow/plugins` (in my `airflow.cfg`, i have `plugins_folder = /usr/local/airflow/plugins`)
2. re-create the example as one of my own dags but import from my own plugins: `from workday import AfterWorkdayTimetable`

**Comment by jscheffl** [comment]
> Sorry for commenting on a merged PR. Just wanna make sure this is a real issue before i create an issue 😅

That is okay. And I assume we have not tried the CLI after the change applied with example DAGs being loaded. Can you raise a new bug for this? (related to this PR?)

Did you set "load examples=True" in your config or did you see this error after running with examples loaded once? Because if the CLI runs w/o examples explicitly turned-on but DAGs have been parsed to DB with examples, this might be a config mis-match.

**Comment by zachliu** [comment]
> > Sorry for commenting on a merged PR. Just wanna make sure this is a real issue before i create an issue 😅
> 
> That is okay. And I assume we have not tried the CLI after the change applied with example DAGs being loaded. Can you raise a new bug for this? (related to this PR?)
> 
> Did you set "load examples=True" in your config or did you see this error after running with examples loaded once? Because if the CLI runs w/o examples explicitly turned-on but DAGs have been parsed to DB with examples, this might be a config mis-match.

Yes, I've been setting `load_examples=True`. I'll create a new issue today.
