### ISSUE TITLE
celery_executor got an unexpected keyword argument 'remove_running'

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#40097]
### Discussed in https://github.com/apache/airflow/discussions/39980

<div type='discussions-op-text'>

<sup>Originally posted by **weitang2022** May 31, 2024</sup>
I upgraded to Airflow 2.9.1. It's been running well for a week, but today I see the error below. I tried to downgrade to 2.8.3, but I still see the issue. All tasks are stuck in "scheduled" status. Any idea how to get around it? Thank you for your help!

May 31, 2024 at 13:51 (UTC-4:00)	[[34m2024-05-31T17:51:01.889+0000[0m] {[34mcelery_executor.py:[0m370} ERROR[0m - Error syncing the Celery executor, ignoring it.[0m	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	Traceback (most recent call last):	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	File "/usr/local/lib/python3.11/site-packages/airflow/providers/celery/executors/celery_executor.py", line 362, in update_task_state	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	self.success(key, info)	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	File "/usr/local/lib/python3.11/site-packages/airflow/executors/base_executor.py", line 332, in success	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	self.change_state(key, TaskInstanceState.SUCCESS, info)	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	File "/usr/local/lib/python3.11/site-packages/airflow/providers/celery/executors/celery_executor.py", line 351, in change_state	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	super().change_state(key, state, info, remove_running=remove_running)	airflow_scheduler
May 31, 2024 at 13:51 (UTC-4:00)	TypeError: BaseExecutor.change_state() got an unexpected keyword argument 'remove_running'	airflow_scheduler

The code here is actually throwing a TypeError:
```
    def change_state(
        self, key: TaskInstanceKey, state: TaskInstanceState, info=None, remove_running=True
    ) -> None:
        try:
            super().change_state(key, state, info, remove_running=remove_running)
        except AttributeError:
            # Earlier versions of the BaseExecutor don't accept the remove_running parameter for this method
            # TODO: Remove when min airflow version >= 2.9.2
            super().change_state(key, state, info)
        self.tasks.pop(key, None)
```</div>

**Comment by o-nikolas** [comment]
#40035 (this one is just a unit test, but it links to the other issues and PR that fixes it as wel. That was merged a couple days ago)

**Comment by potiuk** [comment]
@o-nikolas -> but I think the problem is that the new executor interface does not work with old celery provider.

**Comment by potiuk** [comment]
(or the other way round - maybe the celery executor 3.7.1 does not work with 2.9.2 - and likely 2.8, 2.9 in general - not sure as I am on a meeting today).

**Comment by potiuk** [comment]
Marked them to be included in 2.9.2rc2

**Comment by vincbeck** [comment]
I marked it to be in 2.9.2 but it got removed :( But anyway, yes #40012 is the fix to this issue

**Comment by potiuk** [comment]
Actually - it's not a full fix. It will only work with "fufure" celery provider when it is released. The older versions of celery providers will not work with it @vincbeck @o-nikolas. I guess that means that we

1) have to wait with 2.9.2 until new celery provider is released
2) have to yank celery provider 3.7.1 because #39212 essentially broke the executor for all past versions of Airflow, where #40012 fixes it in the future celery provider

cc: @eladkal @ephraimbuddy

**Comment by potiuk** [comment]
This might actually justify slightly acceleratte celery /k8s provider voting, because we won't be able to effectively test 2.9.1rc1 until celery/k8s providers are released cc: @eladkal .

**Comment by eladkal** [comment]
1. Celery provider 3.7.2rc1 will be released before Airflow 2.9.2
2. Celery provider 3.7.1 is yanked

I guess we can close this issue?

**Comment by potiuk** [comment]
Yep.
