### PR TITLE
Fix AttributeError: module 'ldap' has no attribute 'filter'

### LINKED ISSUE #67534: AttributeError: module 'ldap' has no attribute 'filter'
### Under which category would you file this issue?

Airflow Core

### Apache Airflow version

3.2.1

### What happened and how to reproduce it?

I have an Airflow deployment using LDAP. When updating to version 3.2.1 (from 3.1.8) I get the following error during login
```Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/flask_appbuilder/security/decorators.py", line 36, in wrapped_view
    response = make_response(view(*args, **kwargs))
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/flask_appbuilder/security/views.py", line 649, in login
    user = self.appbuilder.sm.auth_user_ldap(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1981, in auth_user_ldap
    user_dn, user_attributes = self._search_ldap(ldap, con, username)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 2473, in _search_ldap
    escaped_username = ldap.filter.escape_filter_chars(username)
                       ^^^^^^^^^^^
AttributeError: module 'ldap' has no attribute 'filter'
```

### What you think should happen instead?

Successful login.

### Operating System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)" VERSION_CODENAME=bookworm ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### Deployment

None

### Apache Airflow Provider(s)

_No response_

### Versions of Apache Airflow Providers

_No response_

### Official Helm Chart version

Not Applicable

### Kubernetes Version

Not Applicable

### Helm Chart configuration

Not Applicable

### Docker Image customizations

Not Applicable

### Anything else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by m-rossi**
* closes: #67534

---

##### Was generative AI tooling used to co-author this PR?

- [ ] Yes (please specify the tool below)

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

**Comment by eladkal** [comment]
can you add a unit test to avoid regression?
I assume we don't have a test that covers `_search_ldap` which resulted in this bug not being detected

**Comment by potiuk** [comment]
I think it's mostly hallucinated.  Can you explain (in human words) why this would work ? It seem to me that you have some badly name module called `ldap` in your deployment and this is your problem (and we warn against it in https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/modules_management.html

**Comment by m-rossi** [comment]
@potiuk You can simply test that my fix works by starting a Python shell where [python-ldap](https://github.com/python-ldap/python-ldap) is installed (for example your Airflow deployment of choice) and try
```python
>>> import ldap
>>> ldap.filter.escape_filter_chars
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ldap' has no attribute 'filter'
```
once you do my proposal, it works
```python
>>> import ldap.filter
>>> ldap.filter.escape_filter_chars
<function escape_filter_chars at 0x7f469e678c20>
```
I found this solution in https://github.com/python-ldap/python-ldap/issues/469 and it is related how the package `python-ldap` is structured.

I dig a little bit in the code and it seems like the `ldap.filter.escape_filter_chars` was introduced in https://github.com/apache/airflow/pull/66417 and seems we have no testing on this ldap-part of the code which may have caught this?

So I ask you to reopen the PR and we should discuss about testing like @eladkal mentioned.

**Comment by m-rossi** [comment]
For those of you who are looking for a workaround, you can put
```python
import ldap.filter
```
in your `airflow_local_settings.py` while we wait for feedback from @potiuk or @eladkal (I don't want to clutter the PRs by opening another one).

**Comment by pcorliss** [comment]
Confirming that @m-rossi 's workaround above fixes the issue for us. I'd love to see this simple straightforward fix be re-opened and merged to fix this issue in mainline.

**Comment by pcorliss** [comment]
Looks like this PR was just merged in today with the same changes.

https://github.com/apache/airflow/pull/68226
