### ISSUE TITLE
Testing Providers prepared 2021.04.07

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#15241]
Since you were providing the fixes,I  kindly ask for help :) . 

Could you please help testing the providers?  Please comment below if you tested `your` part:

## New providers

- [x] airbyte: @marcosmarxm  https://pypi.org/project/apache-airflow-providers-airbyte/1.0.0rc1/ 
- [x]  trino: @potiuk https://pypi.org/project/apache-airflow-providers-trino/1.0.0rc1/ 

## Providers with fixes

- [x] apache.hive: @XD-DENG https://pypi.org/project/apache-airflow-providers-apache-hive/1.0.3rc1/
- [x] hashicorp: @SangwanP  https://pypi.org/project/apache-airflow-providers-hashicorp/1.0.2rc1/
## Providers with new features
- [x] amazon: @dstandish, @uranusjr  @blcksrx @markhopson @Visya @JavierLopezT @mmoyses  @ferruzzi https://pypi.org/project/apache-airflow-providers-amazon/1.3.0rc1/
- [x] apache.livy: @dsynkov  https://pypi.org/project/apache-airflow-providers-apache-livy/1.1.0rc1/
- [x] cncf.kubernetes: @ashb @akrava @dimberman @SamWheating https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/1.1.0rc1/
- [x] docker: @mzaforas https://pypi.org/project/apache-airflow-providers-docker/1.1.0rc1/
- [x] google: @SamWheating @TobKed @fhoda @sschaetz @jmcarp @radim94 https://pypi.org/project/apache-airflow-providers-google/2.2.0rc1/
- [x] microsoft.azure: @gmcrocetti https://pypi.org/project/apache-airflow-providers-microsoft-azure/1.3.0rc1/
- [x] microsoft.winrm: @shizidushu  https://pypi.org/project/apache-airflow-providers-microsoft-winrm/1.1.0rc1/
- [x] mysql: @potiuk https://pypi.org/project/apache-airflow-providers-mysql/1.1.0rc1/
- [x] salesforce: @jyotidhiman0610  https://pypi.org/project/apache-airflow-providers-salesforce/2.0.0rc2/
- [x] snowflake:  @sunkickr https://pypi.org/project/apache-airflow-providers-snowflake/1.2.0rc1/

## Providers with trivial changes 

Templated fields, using cached_property, type hints - no need to test:

* facebook  https://pypi.org/project/apache-airflow-providers-facebook/1.1.0rc1/
* grpc https://pypi.org/project/apache-airflow-providers-grpc/1.1.0rc1/
* oracle https://pypi.org/project/apache-airflow-providers-oracle/1.1.0rc1/
* opsgenie https://pypi.org/project/apache-airflow-providers-opsgenie/1.0.2rc1/
* singularity https://pypi.org/project/apache-airflow-providers-singularity/1.1.0rc1/
* ssh https://pypi.org/project/apache-airflow-providers-ssh/1.3.0rc1/

Note the links to documentation from PyPI packages are not working until we merge
the changes to airflow site after releasing the packages officially.

**Comment by blcksrx** [comment]
@potiuk I did mine, but you mean there are some sorts of methods or etc that have no test for it?

**Comment by XD-DENG** [comment]
Hi @potiuk , the most recent fix for `apache.hive` was a docstring fix. I have marked it as test done.

**Comment by potiuk** [comment]
> @potiuk I did mine, but you mean there are some sorts of methods or etc that have no test for it?

Thanks!

It is mostly about testing the part you added/modfied. We do not (yet) have automated system testing of everything so this is mosty about verification if the change you've done works as expected.

**Comment by fhoda** [comment]
@potiuk I tested mine.

**Comment by potiuk** [comment]
Hello everyone here - I'd appreciate more feedback on those provoders :)

**Comment by shizidushu** [comment]
@potiuk Do you mean use the operator to check if there is any problem? In this case, I will do it.

**Comment by potiuk** [comment]
> @potiuk Do you mean use the operator to check if there is any problem? In this case, I will do it.

yep :)

**Comment by mzaforas** [comment]
Hi @potiuk I have tested docker operator, it works as expected :)

Note that I have to applied the workaround described here https://github.com/apache/airflow/issues/13487 to test docker operator because I was getting and issue related to xcom serialization with Docker Operator. This issue is independant of my changes and I saw there is another PR to fix it.

Thanks!

**Comment by marcosmarxm** [comment]
@potiuk I tested mine, it works

**Comment by shizidushu** [comment]
@potiuk Just tested mine, it works.

**Comment by dsynkov** [comment]
@potiuk Tested just now with Spark 3.0.1 on EMR 6.2.0. Thanks!

**Comment by potiuk** [comment]
Hey everyone. Thanks to all who've already smoke-tested 9 of those providers :). We are progressing :)

While it is not necessary and is not a blocker, I'd love to get at least some thumbs-up for just a basic testing of the changes for the remaining providers. We can't test them ourselves as we have no external services, but I thin it's much for you just installing it at whatever you have them and rough "looks good" should be ok (it's not a "stamp of approval", it's more "smoke test"). I'd love some comments on those: 

* hashicorp: @SangwanP https://pypi.org/project/apache-airflow-providers-hashicorp/1.0.2rc1/
* amazon: @dstandish, @uranusjr @blcksrx @markhopson @Visya @JavierLopezT @mmoyses @ferruzzi https://pypi.org/project/apache-airflow-providers-amazon/1.3.0rc1/
* cncf.kubernetes: @ashb @akrava @dimberman @SamWheating https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/1.1.0rc1/
* microsoft.azure: @gmcrocetti https://pypi.org/project/apache-airflow-providers-microsoft-azure/1.3.0rc1/
* salesforce: @jyotidhiman0610 https://pypi.org/project/apache-airflow-providers-salesforce/2.0.0rc2/
* snowflake: @sunkickr https://pypi.org/project/apache-airflow-providers-snowflake/1.2.0rc1/

The google one was smoke tested by @fhoda (thanks!), but there were some other changes so if anyone has a chance I'd love some thumbs up (or down) from others as well:
 
* google: @SamWheating @TobKed @sschaetz @jmcarp @radim94 https://pypi.org/project/apache-airflow-providers-google/2.2.0rc1/

**Comment by akrava** [comment]
@potiuk I've tested mine, it works.

**Comment by potiuk** [comment]
Thanks @akrava !

**Comment by sschaetz** [comment]
@potiuk I tested the GCS timespan transform operator, it works.

**Comment by potiuk** [comment]
> @potiuk I tested the GCS timespan transform operator, it works.
Thanks @sschaetz !

**Comment by potiuk** [comment]
I have enough votes to release, but if anyone else would still come back with some smoke test results during the weekend - I'd appreciate it :)

**Comment by SangwanP** [comment]
@potiuk -- I tested the Hashicorp fix, it works as expected.

**Comment by potiuk** [comment]
Thanks @SangwanP

**Comment by potiuk** [comment]
Last chance today to take a look :)

* amazon: @dstandish, @uranusjr @blcksrx @markhopson @Visya @JavierLopezT @mmoyses @ferruzzi https://pypi.org/project/apache-airflow-providers-amazon/1.3.0rc1/
* microsof.azure @gmcrocetti https://pypi.org/project/apache-airflow-providers-microsoft-azure/1.3.0rc1/
* salesforce: @jyotidhiman0610 https://pypi.org/project/apache-airflow-providers-salesforce/2.0.0rc2/
* snowflake: @sunkickr https://pypi.org/project/apache-airflow-providers-snowflake/1.2.0rc1/

If some of you could just take a quick look and confirm that the last 4 packages are looking good (basically install and passes some basic smoke tests), that would be fantastic.

**Comment by dstandish** [comment]
Sorry @potiuk I have been a bit  swamped... my change was just changing log level from info to debug

**Comment by uranusjr** [comment]
The Amazon package looks right to me.

**Comment by potiuk** [comment]
Thanks @uranusjr !

> Sorry @potiuk I have been a bit swamped... my change was just changing log level from info to debug

Perfectly understand :). No problem

**Comment by sunkickr** [comment]
@ptiuk -- I have attempted to "smoke tested" the snowflake connection. In
my local 2.0.0 airflow, values entered into the new Snowflake connection
form fields do not seem to save. They disappear after saving the
connection. I upgraded to 2.0.1(airflow) and everything works fine.  I do
not know why the new feature works in 2.0.1 and not in 2.0.0

**Comment by SamWheating** [comment]
Hey there, I'm hoping to test my changes to the dataproc operators sometime today or tomorrow. The CNCF changes are harder to test as the issue in question only surfaces occasionally and only when running large workflows on a kubernetes cluster. In the original PR I did a pretty thorough test, I hope this will suffice. 

While setting up my local environment to test the google provider, the initial installation broke because of the introduction of `plyvel` which depends on a preexisting `leveldb` installation. 
```
  plyvel/_plyvel.cpp:632:10: fatal error: 'leveldb/db.h' file not found
  #include "leveldb/db.h"
           ^~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
```

It was easy to fix with a simple `brew install leveldb`, but I just wanted to check that you were aware of a new dependency which could break some people's builds.

**Comment by potiuk** [comment]
> @ptiuk -- I have attempted to "smoke tested" the snowflake connection. In my local 2.0.0 airflow, values entered into the new Snowflake connection form fields do not seem to save. They disappear after saving the connection. I upgraded to 2.0.1(airflow) and everything works fine. I do not know why the new feature works in 2.0.1 and not in 2.0.0

It was a bug fixed in 2.0.1 : https://github.com/apache/airflow/issues/13597 so all as expected! Thanks @sunkickr !

**Comment by potiuk** [comment]
> Hey there, I'm hoping to test my changes to the dataproc operators sometime today or tomorrow. The CNCF changes are harder to test as the issue in question only surfaces occasionally and only when running large workflows on a kubernetes cluster. In [the original PR](https://github.com/apache/airflow/pull/15137) I did a pretty thorough test, I hope this will suffice.

Sure that's perfect. I am going to release it as is. 

> While setting up my local environment to test the google provider, the initial installation broke because of the introduction of `plyvel` (added in https://github.com/apache/airflow/pull/14105/files) which depends on a preexisting `leveldb` installation.

Very Good point. Usually we do not consider "dependency" changes as breaking (you generally find out when you try upgrade whether this is a problem or not). For the only "production" supported environment (linux) `plyvel` has binary releases available for manylinux: https://pypi.org/project/plyvel/#files so it should "just work" for those. 

This is a major release with new feature/new dependency clearly marked in the documentation, so this should be fine.

hanks for pointing it out !

**Comment by potiuk** [comment]
Just adding more comments:
- I looked at microsoft.azure and the changes are fairly trivial - tested that azure_data_factory hook is there
-  salesforce provider includes tableu separation - it's been tested before but we have not released salesforce provider back then (copy&paste mistake)

**Comment by potiuk** [comment]
Thanks everyone. Preparing official release now.
