### PR TITLE
[AIRFLOW-2707] Validate task_log_reader on upgrade from <=1.9

### PR DESCRIPTION
**Pull request by ashb**
We changed the default logging config and config from 1.9 to 1.10, but
anyone who upgrades and has an existing airflow.cfg won't know they need
to change this value - instead they will get nothing displayed in the UI
(ajax request fails) and see "'NoneType' object has no attribute 'read'"
in the error log.

This validates that config section at start up, and seamlessly upgrades
the old previous value.

Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-2707

### Description

- [x] Someone in the slack channel was having trouble viewing logs after updating to 1.10, and we eventually tracked it down to this config setting which changed in default from 1.9 to 1.10, but their deploy still had the old value in it.

### Tests

- [x] Added

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] None added

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
Quick fixes are never that are they.

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
We should definitely include this in 1.10.1

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @ashb for fixing this.

@kaxil Good point. I've just cherry-picked it onto 1.10.1
