### PR TITLE
Fix DockerOperator init crash on dict mount entries

### LINKED ISSUE #66345: Issue in Docker Provider when using mounts parameter
Hi, I am getting following exception in `Dag Import` section in UI, that I think is related to this [change](https://github.com/apache/airflow/pull/52451#issuecomment-4369589257) 

```python
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.14/site-packages/airflow/sdk/bases/operator.py", line 548, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.14/site-packages/airflow/providers/docker/operators/docker.py", line 309, in __init__
    mount.template_fields = ("Source", "Target", "Type")
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'template_fields' and no __dict__ for setting new attributes
```
I was using a dict object for mounts like this

```python
    write_to_dst_task = MyOperator(
        ...
        mounts=[
            {
                "type": "volume",
                "source": "{{ params.dst_volume }}",
                "target": "/data/",
                "read_only": False,
            }
        ],
        ...
    )
```

And I added `mounts` to template_fields of MyOperator, It was working but after upgrading to latest version it failed, even using docker.types.Mount instead of dict didn't solve it

```python
    write_to_dst_task = MyOperator(
        ...
        mounts=[
            types.Mount(
                target="/data/",
                source="{{ params.dst_volume }}",
                type="volume",
                read_only=False,
            ),
        ],
        ...
    )
```

_Originally posted by @mfatemipour in https://github.com/apache/airflow/issues/52451#issuecomment-4369589257_

### PR DESCRIPTION
**Pull request by bdsoha**
`DockerOperator` won't construct if you pass a plain dict in `mounts`:

> AttributeError: 'dict' object has no attribute 'template_fields' and no dict for setting new attributes                                                                                        

It's the loop added in #52451, it does `mount.template_fields = (...)` on every entry, and that doesn't work on a plain dict. `docker.types.Mount` is a dict subclass that has `__dict__`, so it slips through.                                               

Fix is to coerce each entry to `Mount` first: `Mount` instances pass through, dicts go through `Mount(**entry)`. Type hint and docstring updated, plus two new tests.

Closes: #66345

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM — clean fix for the regression introduced in #52451. Coercing dict entries to `Mount` at `__init__` time is the right call, since `docker.types.Mount` is a `dict` subclass with `__dict__` (which is exactly why setting `mount.template_fields` worked for `Mount` instances but blew up on plain dicts). Both new tests (mixed dict+Mount input, dict templating) are focused on the bug and minimal.

Tiny optional nit: the parameter type could be `list[Mount | dict[str, Any]] | None` for slightly more precision, but `list[Mount | dict]` works fine — feel free to ignore.

---

> *This review was drafted by an AI-assisted tool and
> confirmed by an Apache Airflow maintainer. The maintainer
> approving this PR has read the findings and signed off. If
> something feels off, please reply on the PR and a maintainer
> will follow up.*
>
> *More on how Apache Airflow handles maintainer review:*
> [contributing-docs/05_pull_requests.rst](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst).
