### PR TITLE
[AIRFLOW-3862] Check types with mypy.

### PR DESCRIPTION
**Pull request by jmcarp**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3862
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

File: airflow/bin/cli.py [hunk 1]
```diff
@@ -1665,9 +1665,17 @@ def sync_perm(args):
             dag.access_control)
 
 
-Arg = namedtuple(
-    'Arg', ['flags', 'help', 'action', 'default', 'nargs', 'type', 'choices', 'metavar'])
-Arg.__new__.__defaults__ = (None, None, None, None, None, None, None)
+class Arg(object):
```
Comment (ashb) [inline airflow/bin/cli.py:1667]: What was wrong with this as a named tuple? Does mypy have trouble with namedtouples?

File: airflow/config_templates/airflow_local_settings.py [hunk 2]
```diff
@@ -19,6 +19,8 @@
 
 import os
 
+from typing import Dict, Any
```
Comment (ashb) [inline airflow/config_templates/airflow_local_settings.py:21]: How does this play out on Python2?

Comment (ashb) [reply airflow/config_templates/airflow_local_settings.py:21]: Actually, can we put this behind the `if TYPE_CHECKING:` (or whatever the right if is)?

File: airflow/contrib/example_dags/example_gcs_to_bq_operator.py [hunk 3]
```diff
@@ -18,46 +18,42 @@
 # under the License.
 
 import airflow
-try:
-    from airflow.contrib.operators import gcs_to_bq
-except ImportError:
```
Comment (ashb) [inline airflow/contrib/example_dags/example_gcs_to_bq_operator.py]: This needs to stay, otherwise the example dags with only a sub-set of extras installs gets nosiy and confusing on the CLI.

File: airflow/contrib/operators/adls_list_operator.py [hunk 4]
```diff
@@ -46,7 +48,7 @@ class AzureDataLakeStorageListOperator(BaseOperator):
                 azure_data_lake_conn_id='azure_data_lake_default'
             )
     """
-    template_fields = ('path',)
+    template_fields = ('path',)  # type: Sequence[str]
```
Comment (ashb) [inline airflow/contrib/operators/adls_list_operator.py]: Do we need to do this on every operator? :(

File: airflow/contrib/operators/azure_container_instances_operator.py [hunk 5]
```diff
@@ -98,7 +106,6 @@ class AzureContainerInstancesOperator(BaseOperator):
     """
 
     template_fields = ('name', 'environment_variables')
```
Comment (ashb) [inline airflow/contrib/operators/azure_container_instances_operator.py:107]: Why no type comment on this one?

File: airflow/contrib/operators/qubole_check_operator.py [hunk 6]
```diff
@@ -73,8 +73,8 @@ class QuboleCheckOperator(CheckOperator, QuboleOperator):
 
     """
 
-    template_fields = QuboleOperator.template_fields + CheckOperator.template_fields
-    template_ext = QuboleOperator.template_ext
+    template_fields = tuple(QuboleOperator.template_fields) + tuple(CheckOperator.template_fields)
+    template_ext = tuple(QuboleOperator.template_ext)
```
Comment (ashb) [inline airflow/contrib/operators/qubole_check_operator.py]: Does this make it this:

```
    template_ext = (('.txt',),)
```
i.e. you've made it a tuple-of-tuple-of-strings

File: airflow/models/__init__.py [hunk 7]
```diff
@@ -1014,9 +1019,8 @@ def are_dependents_done(self, session=None):
         count = ti[0][0]
         return count == len(task.downstream_task_ids)
 
-    @property
     @provide_session
-    def previous_ti(self, session=None):
+    def get_previous_ti(self, session=None):
```
Comment (ashb) [inline airflow/models/__init__.py]: Why the extra method?

File: airflow/models/__init__.py [hunk 8]
```diff
@@ -3085,6 +3094,7 @@ def __init__(
         self.partial = False
         self.on_success_callback = on_success_callback
         self.on_failure_callback = on_failure_callback
+        self.doc_md = doc_md
```
Comment (ashb) [inline airflow/models/__init__.py:3071]: Where did this change come from?

File: airflow/www/views.py [hunk 9]
```diff
@@ -82,7 +83,7 @@
 
 PAGE_SIZE = conf.getint('webserver', 'page_size')
 if os.environ.get('SKIP_DAGS_PARSING') != 'True':
-    dagbag = models.DagBag(settings.DAGS_FOLDER)
+    dagbag = models.DagBag(settings.DAGS_FOLDER)  # type: Any
```
Comment (ashb) [inline airflow/www/views.py]: Why Any and not `airflow.models.DagBag`?

File: setup.py [hunk 10]
```diff
@@ -319,6 +318,7 @@ def do_setup():
             'sqlalchemy>=1.1.15, <1.3.0',
             'tabulate>=0.7.5, <=0.8.2',
             'tenacity==4.12.0',
+            'typing',
```
Comment (ashb) [inline setup.py]: -1 - not a fan of needing typing at run time if we can avoid it.

**Review by ashb — CHANGES_REQUESTED** [review]
Typing at CI would be ace.

The template_fields/exts don't seem to be typed universally. Do we need to apply it to every sub-class? Type hints aren't inherited from parent attributes?

File: airflow/models/__init__.py (hunk 8 above)
Comment (jmcarp) [reply airflow/models/__init__.py:3071]: Some of the example DAGs set `doc_md`, which was raising errors from `mypy`. And it looks like we check this attribute in `views.py`.

File: airflow/www/views.py (hunk 9 above)
Comment (jmcarp) [reply airflow/www/views.py]: I agree that this *should* be type `DagBag`, but the `else` block below defines this variable as the class `DagBag`, not an instance, which `mypy` reasonably complains about. I'm actually not sure why (or if) this works. Maybe instead of setting `dagbag` to be a class, we should pass `skip_dag_parsing` to the `DagBag` constructor so that this variable is always an instance. What do you think?

File: airflow/models/__init__.py (hunk 7 above)
Comment (jmcarp) [reply airflow/models/__init__.py]: `mypy` raises an error when a property has arity >1 (which makes sense) or when a property is decorated (which might make less sense). I got around those errors by factoring those methods into a non-property that uses the `provide_session` decorator and takes a `session` argument and a property that invokes the non-property.

Alternatively, we could ignore the `mypy` warnings and revert these changes, or not use the decorator here and explicitly create a session instead.

File: airflow/contrib/operators/adls_list_operator.py (hunk 4 above)
Comment (jmcarp) [reply airflow/contrib/operators/adls_list_operator.py]: Seems like we need to set types explicitly for classes that we subclass elsewhere. Defining `template_fields` here gives it a type of `Tuple[str]`, which is incompatible with the type `Tuple[str, str]` in the subclass.

File: airflow/bin/cli.py (hunk 1 above)
Comment (jmcarp) [reply airflow/bin/cli.py:1667]: `mypy` doesn't understand `namedtuple` default arguments set via `__new__.__defaults`, so when we instantiate `Arg` below with missing arguments, `mypy` complains. I think `mypy` understands the `namedtuple` default syntax in python >=3.6, but not this syntax.

File: airflow/config_templates/airflow_local_settings.py (hunk 2 above)
Comment (jmcarp) [reply airflow/config_templates/airflow_local_settings.py:21]: This is basically the same in python 2 and 3. In python >=3.5, the `typing` module is part of the standard library; otherwise, we install the backport.

File: setup.py (hunk 10 above)
Comment (jmcarp) [reply setup.py]: We only need this for python <3.5. I can extract `install_requires` into a variable and append this for legacy runtimes.

File: airflow/contrib/operators/adls_list_operator.py (hunk 4 above)
Comment (ashb) [reply airflow/contrib/operators/adls_list_operator.py]: What if we define the type on the base class as `List[str]` -- it doesn't need to explicitly be a tuple, just an iterable of strings. Does that help?

(It feels like for the type to be "right" since it is used in the base class we shouldn't re-define the type in the subclass)

File: setup.py (hunk 10 above)
Comment (ashb) [reply setup.py]: There's a built in syntax for that:

https://github.com/apache/airflow/blob/69e9e9729cb26aaed3c5c4c290d26f3eb40c72fd/setup.py#L294

Can we not use the `if TYPE_CHECKING:` in the code base to not even import the module at run time though?

File: airflow/www/views.py (hunk 9 above)
Comment (ashb) [reply airflow/www/views.py]: Oh I suspect that this only "works" because this flagis only set in very few cases and most of the code path isn't exercised when it is set.

How about making the else be `dagbag = models.DagBag(os.devnull, include_examples=False)` to make it load no DAGs?

File: airflow/contrib/operators/adls_list_operator.py (hunk 4 above)
Comment (jmcarp) [reply airflow/contrib/operators/adls_list_operator.py]: I think that would work, but I've been trying not to change the code more than I have to, so I didn't want to change tuples to lists in every operator. Do you think that would be a useful change?

File: setup.py (hunk 10 above)
Comment (jmcarp) [reply setup.py]: Thanks, updated to install conditional on python version.

I don't see why we couldn't check a flag before importing, but what's the benefit? The `typing` module is trivially fast to import, it's in the standard library for versions of python that aren't soon to be EOL, and for older versions, the wheel is ~25kb.

File: airflow/contrib/operators/adls_list_operator.py (hunk 4 above)
Comment (ashb) [reply airflow/contrib/operators/adls_list_operator.py]: Oh I was thinking List was an abstract type (cos I call them arrays in my head). Maybe I mean `Iterable[str]` then? 

Not changing code sounds like an idea

File: setup.py (hunk 10 above)
Comment (techalchemy) [reply setup.py]: hey, random stranger here -- I found this issue because I was trying to typecheck my own airflow implementation and found that airflow itself doesn't have published stubs, so that caused some issues.  Just wanted to chime in and say that type checking actually can be pretty slow, which is why python 3.7 even introduced a `__future__` import to perform lazy typechecking imports.  See [PEP 563](https://www.python.org/dev/peps/pep-0563) for reference.

What's more, you can't put typechecking imports behind a conditional unless you actually have `typing` installed in the first place to check whether the typechecker is running.  The conventional approach is to just use `'typing;python_version<"3.5"'` as your constraint.

The alternative approach is to do this (I actually do both personally but in theory you can pick one):

```python
def is_type_checking():
    try:
        from typing import TYPE_CHECKING
    except ImportError:
        return False
    return TYPE_CHECKING

MYPY_RUNNING = is_type_checking()
```

Comment (jmcarp) [reply setup.py]: Thanks @techalchemy. This patch installs `typing` conditional on python version like you described. Conditionally importing expensive modules for type checking makes sense, but as far as I can tell, the only imports I'm doing for type checking here are from the `typing` module: `Sequence`, `Optional`, etc. Those aren't expensive to import, and we have to import `typing` anyway to figure out if we're type checking, like you pointed out--so I'm not sure we need conditional imports yet. What do you think?

**Comment by jmcarp** [comment]
@ashb: thanks for reviewing! I think I addressed your comments--sorry if I missed anything. Have time to take another look?

**Comment by mik-laj** [comment]
Why is this process taking over 4 minutes? i because of this line?
`Docker-compose -f scripts/ci/docker-compose.yml pull --quiet --parallel`
maybe it can be speeded up?

**Comment by jmcarp** [comment]
Thanks @mik-laj. Looks like travis was using the same install steps for all pre-test stages. I updated those stages to just install their requirements and skip docker-compose.

**Comment by jmcarp** [comment]
Conflicts resolved @ashb.

**Comment by jmcarp** [comment]
Conflicts resolved again 😅

**Comment by jmcarp** [comment]
Conflicts resolved. PTAL when you have time @ashb; cc @XD-DENG @feng-tao @Fokko. I'd like to start adding type annotations to new PRs going forward, but want to get this merged first.

File: airflow/contrib/operators/azure_container_instances_operator.py [hunk 11]
```diff
@@ -18,6 +18,9 @@
 # under the License.
 
 from time import sleep
+from collections import namedtuple
+
+from typing import Dict, Sequence
```
Comment (XD-DENG) [inline airflow/contrib/operators/azure_container_instances_operator.py:22]: Frankly I'm not very familiar with `mypy`, so can not give useful comment here.

A minor question here: why the packages are not imported in alphabetic order? And given `typing` is a standard library since Py3.5, we can group these three (`collections`, `time`, `typing`) together?

Reference: https://github.com/reddit-archive/reddit/wiki/PythonImportGuidelines

**Review by XD-DENG — COMMENTED** [review]
nit

File: airflow/contrib/operators/azure_container_instances_operator.py (hunk 11 above)
Comment (XD-DENG) [reply airflow/contrib/operators/azure_container_instances_operator.py:22]: Understand this practice is not really followed very well in this project along the way. But we can start to follow it in the new code added at least.

Comment (jmcarp) [reply airflow/contrib/operators/azure_container_instances_operator.py:22]: Updated. We might want to consider https://github.com/timothycrosley/isort or similar to do this consistently.

File: setup.py (hunk 10 above)
Comment (techalchemy) [reply setup.py]: The point of the function-based approach with the safety net of handling the `ImportError` is to provide some flexibility if it's desired -- typechecking is _very_ slow, and by always performing the requisite imports, you basically ensure that annotations are going to be evaluated at runtime no matter what.  This approach allows you a few options:

1. You can set this up as a configuration parameter and toggle it
2. You can make typing an extra that has a builtin failsafe if it's not installed
3. Even if you do only what I pasted above, you ensure that annotations won't be evaluated at runtime if you put all of your typing imports inside an `if MYPY_RUNNING:` block.

The imports themselves aren't slow, it's the consequence of performing them that causes a performance hit.

Comment (jmcarp) [reply setup.py]: I don't follow--are you saying that importing values from `typing` affects performance at runtime? What are the consequences of importing those values at runtime, when we're not type checking?

File: airflow/contrib/operators/adls_list_operator.py (hunk 4 above)
Comment (ashb) [reply airflow/contrib/operators/adls_list_operator.py]: @jmcarp What about this comment? If we change this type to `Iterable[str]` can we avoid having to change code or add comment to every operator?

**Comment by ashb** [comment]
https://github.com/apache/airflow/pull/4685/files#r262035094 still to do/respond to.

File: airflow/contrib/operators/adls_list_operator.py (hunk 4 above)
Comment (jmcarp) [reply airflow/contrib/operators/adls_list_operator.py]: We don't have to add type annotations for every operator--we have to add annotations on operators that are later subclassed. Changing the annotation to `Iterable[str]` doesn't change this. The issue is that a subclass defining `template_fields` as e.g. `("path", )` overrides its type from `Sequence[str]` to `Tuple[str]`; when the subclass of the subclass overrides the value to e.g. `("src_adls", "dest_gcs")`, its new type of `Tuple[str, str]` is incompatible with `Tuple[str]`. We could also set the types in `BaseOperator` to be `List[str]` like we talked about earlier, but that would mean changing all operators to use lists, which I think we agree we shouldn't do.

Here's a simplified example, using python3-style annotations for convenience:

```python
from typing import Iterable

class A:
    a: Iterable[str] = ("a", )

class B(A):
    a = ("a", "b")

class C(B):
    a = ("a", "b", "c")
```

This isn't valid, because the class variable gets typed as `Tuple[str, str]` in `B` but `Tuple[str, str, str]` in `C`:

```
error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "B" defined the type as "Tuple[str, str]")
```

If we annotate `B.a` with `Iterable[str]`, then mypy passes.

Altogether, the annotations we have so far are the simplest solution that I can think of without a larger refactor: we only have to annotate variables in a handful of classes (`BaseOperator` and other operators that are later subclassed), and we don't have to change tuples to lists for all operators.

**Comment by feng-tao** [comment]
side question, I thought mypy doesn't work with python 2.7? Or we won't do mypy when it is in py2.7?

File: airflow/contrib/operators/adls_list_operator.py (hunk 4 above)
Comment (ashb) [reply airflow/contrib/operators/adls_list_operator.py]: Whaaaaat. That strikes me as a bug in mypy - since there is no type annotation on B.a it should keep the one from A. Oh well.

Thanks for the explanation.

Still, let's change for `Iterable[Str]` where we do have to have an  annotation (over `Sequence`) - I reported/asked about this in https://github.com/python/mypy/issues/6511

**Comment by jmcarp** [comment]
@ashb: switched from `Sequence[str]` to `Iterable[str]` like you suggested.
@feng-tao: python 2.7 doesn't have type annotations, so we have to define them using comments: https://mypy.readthedocs.io/en/latest/python2.html. If we drop python 2.x support in the future, we can update to use type annotations.

File: airflow/models/__init__.py [hunk 12]
```diff
@@ -1021,9 +1027,8 @@ def are_dependents_done(self, session=None):
         count = ti[0][0]
         return count == len(task.downstream_task_ids)
 
-    @property
     @provide_session
-    def previous_ti(self, session=None):
+    def get_previous_ti(self, session=None):
```
Comment (ashb) [inline airflow/models/__init__.py]: Actually, since the property is the "preferred" way could we name the method `_get_previous_ti` please? (otherwise this might show up in generated API docs and cause confusion as which one is the "recommended" one to call)

Or do you think it's okay to have both?

Comment (jmcarp) [reply airflow/models/__init__.py]: I agree, revised to make the new methods private and put docstrings in the public properties.

**Comment by jmcarp** [comment]
Conflicts resolved.

**Comment by jmcarp** [comment]
Conflicts resolved, helper methods made private. Ready for another look when you have time @ashb.

**Comment by jmcarp** [comment]
Ping @ashb. Let me know if this needs more revisions.

**Review by ashb — APPROVED** [review]

**Comment by ashb** [comment]
Nice work @jmcarp - sorry it took so long, and thanks for sticking with it!
