### ISSUE TITLE
DagRun.get_previous_dagrun() was removed

### ISSUE THREAD

**Issue by cristian-fatu** [apache/airflow#53628]
### Apache Airflow version

3.0.3

### What happened?

Previously, in 2.9.2, I used the dag_run available in the task context and called get_previous_dagrun on it, but from what I understand in Airflow 3 the context holds a stripped down version of the dag_run, which no longer has the get_previous_dagrun method.
Instead, in Airflow 3.0.2 the call fails with:
`AttributeError: 'DagRun' object has no attribute 'get_previous_dagrun'`

### What you think should happen instead?

I think there should be a get_previous_dagrun method as before. The reason I used this in 2.9.2 was to get the state of the previous DagRun and based on the current and previous state decided whether to send a notification or not (e.g.: if a DAG fails, we might only care to get a notification on the first failure or when it recovers, not in between)

### How to reproduce

For reference, the code that works in 2.9.2 looks like this:
`crt_dag_run = context["dag_run"]
 previous_dag_run = crt_dag_run.get_previous_dagrun(dag_run=crt_dag_run)`

In v3, the DagRun that I get is of type airflow.sdk.api.datamodels._generated.DagRun which doesn't contain the get_previous_dagrun method.

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes  10.6.1
apache-airflow-providers-standard         1.4.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nrnavaneet** [comment]
Would like to work on this :)

**Comment by potiuk** [comment]
> Would like to work on this :)

I am not sure if this is "easy" or whether we want to do much with it.  There is a number of methods that have been deliberately removed from "context" objects because they were never intended to be a "public interface" - they were used by people "accidentally" but when we finalized spit of the workers from database - direct DB access (that was needed by this method) is gone and our general recommendation is to use REST API (which was intended for such usage since the beginning of Airlfow 2 - so for about 4 years now).

So I am quite sure we are not going to "fix it" in the sense that this method is not coming back.

I think however that we might think to make some kind of easier replacements for some "common" methods that people used to use - there are a few methods (including get_previous_dag_run) that keeps on repeating and for me this is a signal that we might need to do **something** about it - either to have such methods in Task SDK directly or making it easier to use REST API from within the tasks. 

I will mark it as "affects 3.0" and likely we should discuss it @ashb @kaxil @amoghrajesh -> tagging those who worked most on the task-sdk.

**Comment by potiuk** [comment]
Ah .. I see @ashb already marked it as "3.0.4" - likely with similar ideas

**Comment by nrnavaneet** [comment]
Ah alright , got it  ! I can migrate the logic to use the REST API instead of relying on get_previous_dagrun(). What do u say? If there are any specifics lmk :). Ill try my best to incorporate them

**Comment by potiuk** [comment]
> Ah alright , got it ! I can migrate the logic to use the REST API instead of relying on get_previous_dagrun(). What do u say? If there are any specifics lmk :). Ill try my best to incorporate them

Well. it requires the user to change it - nothing in Airflow code can be done to change it. User neds to change their code in the Dag currently to use REST API.

**Comment by nrnavaneet** [comment]
Oh learnt smntg new :)

**Comment by kaxil** [comment]
>The reason I used this in 2.9.2 was to get the state of the previous DagRun and based on the current and previous state decided whether to send a notification or not (e.g.: if a DAG fails, we might only care to get a notification on the first failure or when it recovers, not in between)

@cristian-fatu There is a `context["ti"].get_dagrun_state()` state method already available -- which you could use in AF 3.0

https://github.com/apache/airflow/blob/3dc4cd2e01209efbb555b35debeb115367cbeb6d/task-sdk/src/airflow/sdk/execution_time/task_runner.py#L519-L526

and

https://github.com/apache/airflow/blob/3dc4cd2e01209efbb555b35debeb115367cbeb6d/task-sdk/src/airflow/sdk/execution_time/task_runner.py#L496-L516

**Comment by cristian-fatu** [comment]
@kaxil that would still leave the issue of getting the id of the previous run

**Comment by kaxil** [comment]
> [@kaxil](https://github.com/kaxil) that would still leave the issue of getting the id of the previous run

That is true, it is currently generic. We will add something more convenient.

**Comment by ashb** [comment]
It was certainly an "unintentional or not thought out" breaking of the python interface from 2 to 3. We should see if we can fix it nicely, but make not guarantees that we will be able to nicely.

**Comment by kaxil** [comment]
I have a PR (with a couple of TODOs): https://github.com/apache/airflow/pull/53655 . The access pattern is a little different, but it give you the data you need

**Comment by kaxil** [comment]
@cristian-fatu Could you check with the solution in https://github.com/apache/airflow/pull/53655
