### PR TITLE
Revert "enhance spark_k8s_operator (#29977)"

### LINKED ISSUE #31183: SparkKubernetesSensor: 'None' has no attribute 'metadata'
### Apache Airflow version

2.6.0

### What happened

After upgrading to 2.6.0 version, pipelines with SparkKubernetesOperator -> SparkKubernetesSensor stopped working correctly.

[this PR](https://github.com/apache/airflow/pull/29977) introduces some enhancement into Spark Kubernetes logic, now SparkKubernetesOperator receives the log from spark pods (which is great), but it doesn't monitor the status of a pod, which means if spark application fails - a task in Airflow finishes successfully. 
On the other hand, using previous pipelines (Operator + Sensor) is impossible now, cause SparkKubernetesSensor fails with `jinja2.exceptions.UndefinedError: 'None' has no attribute 'metadata'` as SparkKubernetesOperator is no longer pushing info to xcom. 

### What you think should happen instead

Old pipelines should be compatible with Airflow 2.6.0, even though the log would be retrieved in two places - operator and sensor. 
OR remove the sensor completely and implement all the functionality in the operator (log + status)

### How to reproduce

Create a DAG with two operators

```
t1 = SparkKubernetesOperator(
        kubernetes_conn_id='common/kubernetes_default',
        task_id=f"task-submit",
        namespace="namespace",
        application_file="spark-applications/app.yaml",
        do_xcom_push=True,
        dag=dag,
    )

    t2 = SparkKubernetesSensor(
        task_id=f"task-sensor",
        namespace="namespace",
        application_name=f"{{{{ task_instance.xcom_pull(task_ids='task-submit')['metadata']['name'] }}}}",
        dag=dag,
        attach_log=True,
    )

```

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.0.0
apache-airflow-providers-apache-spark==4.0.1
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==6.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-docker==3.6.0
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==10.0.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-azure==6.0.0
apache-airflow-providers-microsoft-mssql==3.3.2
apache-airflow-providers-microsoft-psrp==2.2.0
apache-airflow-providers-microsoft-winrm==3.1.1
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-oracle==3.6.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.5
apache-airflow-providers-sqlite==3.3.2
apache-airflow-providers-ssh==3.6.0
apache-airflow-providers-telegram==4.0.0

### Deployment

Other 3rd-party Helm chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jamescnowell**
This reverts commit 9a4f6748521c9c3b66d96598036be08fd94ccf89.

Based on the discussion found
[here](https://github.com/apache/airflow/issues/31183), previous changes
to the Spark K8s Operator broke existing functionality and did not update the documentation for the newly enabled functionality.

The Spark Sensor no longer works, XCOM no longer works on the Operator itself, and the Operator does not fail when the Spark job fails.

Rather than attempt to fix or resolve the current implementation, I am reverting to the existing, documented implementation.

I would propose creating a _new_ Operator with alternative functionality (one which does not need a Sensor, copies logs, etc.) if that is desired.

closes: [#31183](https://github.com/apache/airflow/issues/31183)

### CODE REVIEW

**Comment by eladkal** [comment]
I don't think revert is required?
This sounds more like a case where additional functionality + docs are needed and once we have it and release new version we can (maybe) yank the old one.

The PR in question was released in April. There may be users out there who relay on it and reverting it would cause their code to break.

**Comment by jamescnowell** [comment]
>additional functionality
As it is currently, it is a non-backwards compatible change in the functionality of the Operator, which previously relied entirely on the Sensor for monitoring the job status (as far as I know). Currently, the Operator maintains a Running status for the duration of the Spark job, which changes the possible DAG configurations. 

I have an immediate need to have a working DAG, meaning I need to revert to an older version of the Operator (as this version does not fail when a job fails). On top of that, if the change moves forwards as-is, I will not only need to update my DAGs in the future, but will also lose features I may be relying on (the ability to have a fork in a DAG after launching a Spark job, but before it's finished).

I'm definitely _for_ an Operator that behaves in this way, but either by adding flags to the existing operator, or creating an Operator with a different name, and a deprecation schedule for the existing Operator.

**Comment by potiuk** [comment]
>> I'm definitely for an Operator that behaves in this way, but either by adding flags to the existing operator, or creating an Operator with a different name, and a deprecation schedule for the existing Operator.

Can you do it this way rather than reverting the change. While I understand your case is impacted, it can be easily fixed by downgrading to earlier version of provider, so "properly" fixing it seems to be a better way than reverting. Reverting a change that has already been released only adds confusion, because if somone relies on what has been already released then you break the other's workflows while you are fixing yours. Can you add a flag to control the behaviour instead?

**Comment by eladkal** [comment]
I agree with Jarek.
Your immidiate issue can be solved by downgrading the version of the provider till the underlying issue is resolved.

The fact that you agree and support the code modifications made by previous PR makes even stronger case not to revert.
Can you please modify the PR to adress the concerns you raised (docs etc..)

**Comment by jamescnowell** [comment]
I'm not able to spend that much time on changes like that right now. You can close this PR if it's not something you plan on accepting.

I find it frustrating that non-backwards compatible changes are allowed into to "stable" API versions, as will many others. 

For the "Some people may be relying on it" statement... while that is possible, the current version is fundamentally broken, so those people will have jobs that fail with no notification. I believe _most_ of those people will have ended up finding https://github.com/apache/airflow/issues/31183 as using the code provided in the examples errors out very quickly.

I understand this is already a sticky situation and there are no good solutions, this is simply the solution that I had time for, that appeared to be in line with having stable API version numbers.

**Comment by potiuk** [comment]
then maybe @blcksrx  will have time to fix it since that was the #31183 change that broke it. Do you agree @blcksrx that this is "fundamentally broken" ? 

Can you please fix it @blcksrx ? I think if not then indeed we will have to rever it, unless someone provides a fix.

> I find it frustrating that non-backwards compatible changes are allowed into to "stable" API versions, as will many others.

Surely @jamescnowell . It is frustrating for everyone. But maybe you do not understand the perspective and OSS spirit  - it might happen. Maybe you could better do it with 80 providers, 5000 or so operators and 30 commits merged a day and multiple thousands of tests to prevent such errors from happening. Airflow has 2500 contributors and you get it for absolutely free. There are many ways you and others can give back - spending time (as the 2500 contributors) is one of the ways - and I understand you do not have more of the time (but then maybe github Sponsorship or finding someone in your company - that uses the software for free) would be a good way to give back for the countless hours people spend on contributing to Airflow so that your company can use it for free.

**Comment by eladkal** [comment]
> I find it frustrating that non-backwards compatible changes are allowed into to "stable" API versions, as will many others

This was not intentional.
We have several check points to minimize such issues but its not bullet proof. I welcome you to participate in testing releases to minimize such future cases.

The issue here is that segnificant time has passed since the release and reverting / yanking the version might cause more harm than good as there may be users that already used the modified version.

You issue is solved by simply not updating the provider till a fix is merged.

**Comment by potiuk** [comment]
> @potiuk I'm not completely agree this version is broken. It's could be fixed in no time!
Can you make a fix then, please ?

**Comment by eladkal** [comment]
Closing in favor of https://github.com/apache/airflow/pull/31798
@jamescnowell I welcome you to assist with the review
