### PR TITLE
Databricks SQL operators are now Python 3.10 compatible

### LINKED ISSUE #22220: Databricks SQL fails on Python 3.10
### Apache Airflow Provider(s)

databricks

### Versions of Apache Airflow Providers

The databricks SQL does not work on Python 3.10 due to "from collections import Iterable" in the `databricks-sql-connector`

* https://pypi.org/project/databricks-sql-connector/

Details of this issue dicussed in https://github.com/apache/airflow/pull/22050

For now we will likely just exclude the tests (and mark databricks provider as non-python 3.10 compatible). But once this is fixed (in either 1.0.2 or upcoming 2.0.0 version of the library, we wil restore it back). 

### Apache Airflow version

main (development)

### Operating System

All

### Deployment

Other

### Deployment details

Just Breeze with Python 3.10

### What happened

The tests are failing:

```
  self = <databricks.sql.common.ParamEscaper object at 0x7fe81c6dd6c0>
  item = ['file1', 'file2', 'file3']
  
      def escape_item(self, item):
          if item is None:
              return 'NULL'
          elif isinstance(item, (int, float)):
              return self.escape_number(item)
          elif isinstance(item, basestring):
              return self.escape_string(item)
  >       elif isinstance(item, collections.Iterable):
  E       AttributeError: module 'collections' has no attribute 'Iterable'
  ```

https://github.com/apache/airflow/runs/5523057543?check_suite_focus=true#step:8:16781 

### What you expected to happen

Test succeed :)

### How to reproduce

Run `TestDatabricksSqlCopyIntoOperator` in Python 3.10 environment.

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by alexott**
New version of `databricks-sql-connector` fixes incompatibility with Python 3.10, so rolling back #22221, and bumping dependency.

 closes #22220

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by alexott** [comment]
Error either in mypy rules, or in the Google hook...

**Comment by potiuk** [comment]
New google dependencies which got upgraded recently, (this only shows up when you change dependencies yourself - it will upgrade to latest "matching" deps for everything and you get those kinds of errors): 

Fix here: https://github.com/apache/airflow/pull/22884

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
Rebased it after the #22884 was merged.

**Comment by alexott** [comment]
Thank you Jarek.
I’ll rebase other PRs
