### PR TITLE
[AIRFLOW-2778] add explicit import for dag_processing.list_py_filepaths in collect_dags

### PR DESCRIPTION
**Pull request by KevYuen**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

I run the following test to make sure there are no import errors in our CI. After upgrading to 1.10-stable from 1.9.0, the following test starting failing: 
```python
class TestAirflowDag:

    def test_dagbag_import(self):
        """Verify that Airflow will be able to import all DAGS in the repo
        """

        dagbag = self._get_dagbag()
        assert len(dagbag.import_errors) == 0

    def _get_dagbag(self):
        dag_folder = os.getenv('AIRFLOW_DAGS', False)
        assert dag_folder is not None

        return DagBag(dag_folder=dag_folder, include_examples=False)
```

The following error is raised:
```
# Used to store stats around DagBag processing 
stats = [] 
FileLoadStat = namedtuple( 
    'FileLoadStat', 
    "file duration dag_num task_num dags"
)  
for filepath in utils.dag_processing.list_py_file_paths(dag_folder): 

E AttributeError: module 'airflow.utils' has no attribute 'dag_processing'
```

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
I am not sure how to introduce test for this specific issue, as it looks like the area is tested but works because dag_processing is imported at some point. Please advise on this. 

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
No tests are fine on this -- there's not really an easy way to test this.

**Comment by ashb** [comment]
Test failure is a random timeout in the Kubernetes env on py3, everything else passed so merging anyway.
