### PR TITLE
[AIRFLOW-4363] Fix JSON encoding error

### PR DESCRIPTION
**Pull request by retornam**
From the docker-py code comments for APIClient pull,
the decode parameter should be set to True, when the
stream parameter is also set to True. This will allow
decoding JSON data returned from the docker registry
server into dicts

Signed-off-by: Raymond Etornam <retornam@users.noreply.github.com>

---
Issue link: [AIRFLOW-4363](https://issues.apache.org/jira/browse/AIRFLOW-4363)

Make sure to mark the boxes below before creating PR: [x]

- [x ] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by dimberman — APPROVED** [review]

**Comment by brokenjacobs** [comment]
This breaks the pull functionality because the very next function in the loop tries to do a string decode on this dictionary.
Leading to:
```  File "airflow/operators/docker_operator.py", line 269, in execute
    output = json.loads(l.decode('utf-8').strip())
AttributeError: 'dict' object has no attribute 'decode'```

**Comment by dimberman** [comment]
Darn. @brokenjacobs do you have a suggestion for a fix for this?

**Comment by brokenjacobs** [comment]
Testing a fix right now.

**Comment by retornam** [comment]
https://github.com/apache/airflow/pull/8287

**Comment by brokenjacobs** [comment]
remove the entire json.loads() line... change the loop:
```for output in self.cli.pull(self.image, stream=True, decode=True):```
That fixes it.

**Comment by hagope** [comment]
After upgrading from 1.10.9 to 1.10.10, I'm now getting this error, wondering if its related:
```
[2020-04-20 23:14:44,087] {{docker_operator.py:267}} INFO - Pulling docker image XXXX:latest
[2020-04-20 23:14:44,140] {{taskinstance.py:1145}} ERROR - 'dict' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 269, in execute
    output = json.loads(l.decode('utf-8').strip())
AttributeError: 'dict' object has no attribute 'decode'
```
