### PR TITLE
Fix remote_task_handler_kwargs passing handler params to RemoteLogIO

### LINKED ISSUE #58770: Cannot configure FileTaskHandler max_bytes via remote_task_handler_kwargs in Airflow 3
### Apache Airflow version

3.1.3

### If "Other Airflow 2/3 version" selected, which one?

_No response_

### What happened?

We encountered a breaking change when upgrading from Airflow 2.11.0 to 3.1.3 related to remote_task_handler_kwargs in airflow_local_settings.py.

Issue:

In Airflow 2.x, remote_task_handler_kwargs configured the FileTaskHandler (or its subclasses like WasbTaskHandler). We successfully used this to set max_bytes for log file size limiting:

remote_task_handler_kwargs = {"max_bytes": 5000000, "backup_count": 5}

After upgrading to Airflow 3.x, this configuration raises:

TypeError: WasbRemoteLogIO.__init__() got an unexpected keyword argument 'max_bytes'

### What you think should happen instead?

Root cause:

PR https://github.com/apache/airflow/pull/48491 introduced separate RemoteLogIO classes for remote storage operations. The current implementation in airflow_local_settings.py now passes remote_task_handler_kwargs to WasbRemoteLogIO.__init__(), which only accepts base_log_folder, remote_base, delete_local_copy, and wasb_container.

Handler-level parameters like max_bytes and backup_count should go to FileTaskHandler, but are instead being consumed by the I/O layer, which doesn't support them.

Misleading naming:

The variable name remote_task_handler_kwargs suggests these parameters configure the handler, but the current code path applies them to the remote I/O abstraction.

Question:

How should max_bytes and similar FileTaskHandler parameters be configured in Airflow 3.x with the new RemoteLogIO architecture? Should there be separate config keys for I/O-layer vs handler-layer parameters, or should the current implementation be fixed to properly separate them?

Expected behavior:

Parameters like max_bytes, backup_count and delay should configure the FileTaskHandler instance, while WasbRemoteLogIO receives only its own relevant parameters.

### How to reproduce

Configure remote logging e.g. using WasbFileTaskHandler to upload logs to a blob stroage and add:
[logging]
remote_logging = True
remote_base_log_folder = wasb-<container>://<account>.blob.core.windows.net/<path>
remote_task_handler_kwargs = {"max_bytes": 5000000, "backup_count": 5}

and start application. And check for TypeError during init of the logging system:
TypeError: WasbRemoteLogIO.__init__() got an unexpected keyword argument 'max_bytes'

### Operating System

Debian GNU/Linux 12

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by srchilukoori**
`remote_task_handler_kwargs` has two bugs when it contains FileTaskHandler
params like `max_bytes`, `backup_count`, or `delay`:

1. **TypeError at startup** — all kwargs are passed to the RemoteLogIO
   constructor (attrs-based), which rejects unknown params like `max_bytes`.
2. **Handler params silently ignored** — `_handler_kwargs` is reset to `{}`
   after each RemoteLogIO construction, so handler params never reach
   `DEFAULT_LOGGING_CONFIG["handlers"]["task"]`.

PR #65412 partially fixed this by correcting the variable name used for the
handler config update, but the kwargs split was still missing.

**Root cause:** `_handler_kwargs` was being passed wholesale to both the
RemoteLogIO constructor and the handler config update, with a reset to `{}`
in between.

**Fix:** Split `_handler_kwargs` into `_file_handler_kwargs` (params belonging
to `FileTaskHandler.__init__`: `max_bytes`, `backup_count`, `delay`) and
`_io_kwargs` (everything else) before the provider if/elif chain. RemoteLogIO
gets `_io_kwargs`, handler config gets `_file_handler_kwargs`.

This PR continues work from #63594 and #62932, both closed for inactivity.
The approach is the same (static param set split), with reviewer feedback from
those PRs addressed here (coupling guard test, expanded test coverage).

closes: #58770

---

##### Was generative AI tooling used to co-author this PR?

- [x] Yes — Claude

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.

### CODE REVIEW

**Comment by srchilukoori** [comment]
@potiuk, @eladkal could you review this PR, please. (found you from file history)

**Comment by jscheffl** [comment]
@AutomationDev85 as you filed the bug, can you have a look?

File: airflow-core/src/airflow/config_templates/airflow_local_settings.py [hunk 1]
```diff
@@ -159,7 +159,12 @@ def _default_conn_name_from(mod_path, hook_name):
             "logging/remote_task_handler_kwargs must be a JSON object (a python dict), we got "
             f"{type(remote_task_handler_kwargs)}"
         )
-    _handler_kwargs = cast("dict[str, Any]", remote_task_handler_kwargs)
+    _all_kwargs = cast("dict[str, Any]", remote_task_handler_kwargs)
+    # Params accepted by FileTaskHandler.__init__ (excluding base_log_folder, set separately).
+    # Everything else is forwarded to the RemoteLogIO constructor.
+    _FILE_HANDLER_PARAMS = frozenset({"max_bytes", "backup_count", "delay"})
```
Comment (AutomationDev85) [inline airflow-core/src/airflow/config_templates/airflow_local_settings.py]: Hard-coding these parameters is not a good approach. Different task handlers may require different parameter sets, so the configuration should be handled in a more generic way. The parameter selection should depend on the configured task handler rather than being fixed in the code.

File: airflow-core/src/airflow/config_templates/airflow_local_settings.py [hunk 2]
```diff
@@ -174,10 +179,10 @@ def _default_conn_name_from(mod_path, hook_name):
                     "remote_base": remote_base_log_folder,
                     "delete_local_copy": delete_local_copy,
                 }
-                | _handler_kwargs,
+                | _io_kwargs,
             )
         )
-        _handler_kwargs = {}
+        _io_kwargs = {}
```
Comment (AutomationDev85) [inline airflow-core/src/airflow/config_templates/airflow_local_settings.py]: All these _io_kwargs = {} lines can be removed as the variable is not used any more in code below.

Comment (srchilukoori) [reply airflow-core/src/airflow/config_templates/airflow_local_settings.py]: > All these _io_kwargs = {} lines can be removed as the variable is not used any more in code below.

@AutomationDev85 removed the dead code.

**Review by jscheffl — APPROVED** [review]
Looks good to me, @AutomationDev85 Can you have another look?

File: airflow-core/src/airflow/config_templates/airflow_local_settings.py [hunk 3]
```diff
@@ -159,7 +159,18 @@ def _default_conn_name_from(mod_path, hook_name):
             "logging/remote_task_handler_kwargs must be a JSON object (a python dict), we got "
             f"{type(remote_task_handler_kwargs)}"
         )
-    _handler_kwargs = cast("dict[str, Any]", remote_task_handler_kwargs)
+    _all_kwargs = cast("dict[str, Any]", remote_task_handler_kwargs)
+    # Dynamically determine which kwargs belong to FileTaskHandler vs RemoteLogIO.
+    import inspect
```
Comment (AutomationDev85) [inline airflow-core/src/airflow/config_templates/airflow_local_settings.py]: I think we can move this import to the top level imports.

File: airflow-core/src/airflow/config_templates/airflow_local_settings.py [hunk 4]
```diff
@@ -159,7 +159,18 @@ def _default_conn_name_from(mod_path, hook_name):
...
+
+    from airflow.utils.log.file_task_handler import FileTaskHandler
```
Comment (AutomationDev85) [inline airflow-core/src/airflow/config_templates/airflow_local_settings.py]: As part of the parameter validation that happens when arguments are added to FileHandler near the end of the file, I think we need to import the class which is actually defined at https://github.com/srchilukoori/airflow/blob/b426c4090d40e46dd4426360811a8db2e10722c2/airflow-core/src/airflow/config_templates/airflow_local_settings.py#L78

**Review by jscheffl — APPROVED** [review]
