### ISSUE TITLE
SparkKubernetesSensor: 'None' has no attribute 'metadata'

### ISSUE THREAD

**Issue by hanna-liashchuk** [apache/airflow#31183]
### Apache Airflow version

2.6.0

### What happened

After upgrading to 2.6.0 version, pipelines with SparkKubernetesOperator -> SparkKubernetesSensor stopped working correctly.

[this PR](https://github.com/apache/airflow/pull/29977) introduces some enhancement into Spark Kubernetes logic, now SparkKubernetesOperator receives the log from spark pods (which is great), but it doesn't monitor the status of a pod, which means if spark application fails - a task in Airflow finishes successfully. 
On the other hand, using previous pipelines (Operator + Sensor) is impossible now, cause SparkKubernetesSensor fails with `jinja2.exceptions.UndefinedError: 'None' has no attribute 'metadata'` as SparkKubernetesOperator is no longer pushing info to xcom. 

### What you think should happen instead

Old pipelines should be compatible with Airflow 2.6.0, even though the log would be retrieved in two places - operator and sensor. 
OR remove the sensor completely and implement all the functionality in the operator (log + status)

### How to reproduce

Create a DAG with two operators

```
t1 = SparkKubernetesOperator(
        kubernetes_conn_id='common/kubernetes_default',
        task_id=f"task-submit",
        namespace="namespace",
        application_file="spark-applications/app.yaml",
        do_xcom_push=True,
        dag=dag,
    )

    t2 = SparkKubernetesSensor(
        task_id=f"task-sensor",
        namespace="namespace",
        application_name=f"{{{{ task_instance.xcom_pull(task_ids='task-submit')['metadata']['name'] }}}}",
        dag=dag,
        attach_log=True,
    )

```

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.0.0
apache-airflow-providers-apache-spark==4.0.1
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==6.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-docker==3.6.0
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==10.0.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-azure==6.0.0
apache-airflow-providers-microsoft-mssql==3.3.2
apache-airflow-providers-microsoft-psrp==2.2.0
apache-airflow-providers-microsoft-winrm==3.1.1
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-oracle==3.6.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.5
apache-airflow-providers-sqlite==3.3.2
apache-airflow-providers-ssh==3.6.0
apache-airflow-providers-telegram==4.0.0

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
maybe related to PR https://github.com/apache/airflow/pull/29977

**Comment by hanna-liashchuk** [comment]
yes, seems that missing return in execute() method caused this

**Comment by Owen-CH-Leung** [comment]
https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py#L96

I think the execute() method should return the object created by `hook.create_custom_object()` in order for xcom to work and sensor to poke the operator and get its logs. Also : 

https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py#L103-L115

these few lines are trying to populate spark driver log directly into `SparkKubernetesOperator`, but I think the role to fetch spark driver logs should be done by sensor ? sounds duplicated to me

**Comment by matheus-rossi** [comment]
Just confirming, all my tasks with spark operator on k8s are failing now. 

I've noticed the logs on the SparkKubernetesOperator, and since this change the SparkKubernetesSensor now always returns this error: 

`'None' has no attribute 'metadata' `

Taking the opportunity, if we could eliminate the sensor, it would be awesome. From time to time, I get errors on production, because the sensor didn't find the pod, even using timeToLive ...

**Comment by hanna-liashchuk** [comment]
Agree, spark driver log in SparkKubernetesOperator is kinda duplicate but still insufficient since it's not displaying the status of the spark driver in the end. Would be great to have it all in one operator, sometimes out Sensor gets SIGTERM for no obvious reason even though spark itself is still running and finishing successfully. but this change is not backward compatible, so ...

**Comment by adminidever** [comment]
with me is associated with the same problem.

**Comment by potiuk** [comment]
@blcksrx - seems it was result of this change https://github.com/apache/airflow/pull/29977 - is it possible that you take a look ?

**Comment by jamescnowell** [comment]
I've created a PR (#31716) to revert the changes to the SparkOperator as it is:

1. Not backward compatible with the existing Operator
2. Not documented
3. Not clear what exactly the intended behavior is, though I _think_ I understand.

If this new style of Operator is desirable, I would propose adding it as a _new_ Spark operator with _new_ documentation on using it.

**Comment by blcksrx** [comment]
> @blcksrx - seems it was result of this change #29977 - is it possible that you take a look ?

The original issue true. since spark operator watches the logs until the job finishes, it didn't makes any sense to return that to sparkSensorOperator.
Also, I see I forgot to cover the case when spark pod fails (it could fix easily)

**Comment by jamescnowell** [comment]
With regards to SparkKubernetesSensor, the Operator now  remains Running for the duration of the Spark job, which (I think) means some DAG topologies will no longer work as expected. For example
```
                / ----> some other thing \
Spark Job                                          --> Final Thing
                \ ----> sensor ----------- /
```
Will no longer run "some other thing" while the Spark Job is running, but instead after the job is completed and the DAG will need to be re-arranged.

This will mean either:
1. People will need to update their DAGs when they notice a runtime change or
2. People will not notice the change, but will be running a useless SparkKubernetesSensor

This is why I would propose making this a separate operator, or behind behavioral flags on the existing operator to maintain the existing behavior while documenting an upgrade path.

**Comment by blcksrx** [comment]
> With regards to SparkKubernetesSensor, the Operator now remains Running for the duration of the Spark job, which (I think) means some DAG topologies will no longer work as expected. For example
> 
> ```
>                 / ----> some other thing \
> Spark Job                                          --> Final Thing
>                 \ ----> sensor ----------- /
> ```
> 
> Will no longer run "some other thing" while the Spark Job is running, but instead after the job is completed and the DAG will need to be re-arranged.
> 
> This will mean either:
> 
> 1. People will need to update their DAGs when they notice a runtime change or
> 2. People will not notice the change, but will be running a useless SparkKubernetesSensor
> 
> This is why I would propose making this a separate operator, or behind behavioral flags on the existing operator to maintain the existing behavior while documenting an upgrade path.

This example has a logical flaw, since the other thing is dependent to the `SparkJob`, if it wasn't dependent, it would be not related to the `SparkJob` and if it it was, it would be after the `SparkSensor`.
 Airflow operators are responsible to doing a job complete. such as moving data between data sources and mean while they keep their state as running and also keeps the logs in the airflow output.
Hence I't doesn't makes any sense just to apply a spark job and ingore it or double the work by using another operator (sparkSensor) to wait on it.

Despite of this fact it an additional argument with default value such as `print_logs=False` could solves these backward compatibility issue

**Comment by eladkal** [comment]
@blcksrx can you raise PR to address is?
