### ISSUE TITLE
get_hook() got an unexpected keyword argument 'hook_params'

### ISSUE THREAD

**Issue by raefezzeldin** [apache/airflow#28093]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Working with Airflow version 2.2.2
When trying to connect to Snowflake connection.
the following  errors appears
```
 hook = conn.get_hook(hook_params=self.hook_params)
TypeError: get_hook() got an unexpected keyword argument 'hook_params'
```

### What you think should happen instead

it was working normally three days ago, and it returns data from snowflake and append it into google sheets

### Operating System

MWAA

### Versions of Apache Airflow Providers

Package Name | Version | Description
-- | -- | --
apache-airflow-providers-amazon | 4.1.0 | Amazon integration (including Amazon Web Services (AWS)).
apache-airflow-providers-celery | 2.1.0 | Celery
apache-airflow-providers-common-sql | 1.3.1 | Common SQL Provider
apache-airflow-providers-ftp | 2.0.1 | File Transfer Protocol (FTP)
apache-airflow-providers-google | 8.2.0 | Google services including:- Google Ads- Google Cloud (GCP)- Google Firebase- Google LevelDB- Google Marketing Platform- Google Workspace (formerly Google Suite)
apache-airflow-providers-http | 2.0.1 | Hypertext Transfer Protocol (HTTP)
apache-airflow-providers-imap | 2.0.1 | Internet Message Access Protocol (IMAP)
apache-airflow-providers-jdbc | 2.1.3 | Java Database Connectivity (JDBC)
apache-airflow-providers-postgres | 4.1.0 | PostgreSQL
apache-airflow-providers-slack | 4.2.3 | Slack
apache-airflow-providers-snowflake | 3.1.0 | Snowflake
apache-airflow-providers-sqlite | 2.0.1 | SQLite

### Deployment

MWAA

### Deployment details

MWAA version 2.2.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Hello @raefezzeldin,

Is this code you are writting or code coming from the provider ?

A quick search on the doc shows that the `hook_params` was added in 2.3.0:
- [2.2.5 doc](https://airflow.apache.org/docs/apache-airflow/2.2.5/_api/airflow/models/connection/index.html#airflow.models.connection.Connection.get_hook)
- [2.3.0 doc](https://airflow.apache.org/docs/apache-airflow/2.3.0/_api/airflow/models/connection/index.html#airflow.models.connection.Connection.get_hook)

related PR: https://github.com/apache/airflow/pull/18718/

So this code is not expected to work in `2.2.2` I believe.

**Comment by potiuk** [comment]
Corect. It's invalid.
