### ISSUE TITLE
alternative secret backend failure in AWS provider

### ISSUE THREAD

**Issue by IUADE0H5** [apache/airflow#55373]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow==3.0.6
apache-airflow-core==3.0.6
apache-airflow-providers-amazon==9.12.0
apache-airflow-providers-celery==3.12.2
apache-airflow-providers-common-compat==1.7.3
apache-airflow-providers-common-io==1.6.2
apache-airflow-providers-common-sql==1.27.5
apache-airflow-providers-http==5.3.3
apache-airflow-providers-smtp==2.2.0
apache-airflow-providers-standard==1.6.0
apache-airflow-task-sdk==1.0.6

### Apache Airflow version

3.0.6

### Operating System

debian,macos

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

primary deployment - EKS+official chart+SSM as secret backend
debug env macOS with aws creds and same airflow.cfg as in chart

### What happened

Traceback (most recent call last):
  File "/Users/1/PycharmProjects/airflow-examples/venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/Users/1/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/__init__.py", line 62, in <module>
    from airflow import configuration, settings
  File "/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/configuration.py", line 2261, in <module>
    conf.validate()
  File "/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/configuration.py", line 752, in validate
    self._validate_sqlite3_version()
  File "/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/configuration.py", line 819, in _validate_sqlite3_version
    if "sqlite" not in self.get("database", "sql_alchemy_conn"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/configuration.py", line 1057, in get
    option = self._get_option_from_secrets(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/configuration.py", line 1090, in _get_option_from_secrets
    option = self._get_secret_option(section, key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/configuration.py", line 921, in _get_secret_option
    return _get_config_value_from_secret_backend(secrets_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/configuration.py", line 154, in _get_config_value_from_secret_backend
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: Cannot retrieve config from alternative secrets backend. Make sure it is configured properly and that the Backend is accessible.
Cannot retrieve config from alternative secrets backend. Make sure it is configured properly and that the Backend is accessible.
cannot import name 'SessionFactory' from partially initialized module 'airflow.providers.amazon.aws.hooks.base_aws' (most likely due to a circular import) (/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py)

### What you think should happen instead

This is a degradation from 2.10.5. With the same config 2.10.5 up&running, and 3.0.6 failing to start

### How to reproduce

1. try to use connection stored in alternative secret backend
2. create airflow config as below
airflow.cfg
`[secrets]

backend = airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend
backend_kwargs = {"connections_prefix": "/airflow/connections", "region_name": "eu-central-1", "variables_prefix": "/airflow/variables", "config_prefix": "/airflow/config"}
[database]

sql_alchemy_conn_secret = sql_alchemy_conn
`
3.Run `airflow info` or `airflow db check`

### Anything else

I tested with vault provider to check if something broken in core, but with vault as alternative secret backend 
`airflow db check` passed. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jroachgolf84** [comment]
How are you authenticating to AWS?

**Comment by IUADE0H5** [comment]
@jroachgolf84  EKS IRSA service account with access to KMS and parameter store.

**Comment by IUADE0H5** [comment]
For local debug - just ~/.aws/credentials file

**Comment by jroachgolf84** [comment]
Have you validated that you can access Parameter Store from there? Basically by running a `python3` from within the Scheduler, then trying to connect?

**Comment by IUADE0H5** [comment]
That doesn't matter. airflow don't even try to connect to AWS on 3.0.6. I am updating existing deployment, and tried several times 2.10.5 vs 3.0.6 with the same infra permissions, and it works on 2.10.5.

**Comment by IUADE0H5** [comment]
Other words - you even do not need aws account to reproduce the bug, If you will follow step by step How to reproduce

**Comment by jroachgolf84** [comment]
```
cannot import name 'SessionFactory' from partially initialized module 'airflow.providers.amazon.aws.hooks.base_aws' (most likely due to a circular import) (/Users/user/PycharmProjects/airflow-examples/venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py)
```

This is the exception that is being caught and surfaced via the `AirflowConfigException`.

**Comment by anleib** [comment]
Hit this issue while working on Airflow PoC. Seems to be fixed in `3.1.0b1` though.

**Note:**
If `sql_alchemy_conn` config value is provided through SecretManager then the secret has to store the value in plaintext URL form, the JSON form does not seem to work.

**Comment by IUADE0H5** [comment]
I can confirm that issue solved in `3.1.0b2` version.
P.S. `sql_alchemy_conn ` is in URI format already.

**Comment by eladkal** [comment]
closing as fixed
