### ISSUE TITLE
No serialized dag found

### ISSUE THREAD

**Issue by anavrotski** [apache/airflow#58421]
### Apache Airflow version

3.1.3

### What happened?

When I'm trying to start DAG (with a parameter provided via UI) manually, an error appears:
```
404 Not Found
The Dag with ID: `...` was not found
```
The api-server log:
```
wait-for-airflow-migrations 
wait-for-airflow-migrations /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/fab_auth_manager.py:108 RemovedInAirflow4Warning: The airflow.security.permissions module is deprecated; please see https://airflow.apache.org/docs/apache-airflow/stable/security/deprecated_permissions.html
wait-for-airflow-migrations 2025-11-18T10:02:23.565520Z [info     [] Context impl MySQLImpl.        [alembic.runtime.migration] loc=migration.py:211
wait-for-airflow-migrations 2025-11-18T10:02:23.565758Z [info     [] Will assume non-transactional DDL. [alembic.runtime.migration] loc=migration.py:214
api-server     await app(scope, receive, sender)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
api-server     response = await f(request)
api-server                ^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/routing.py", line 308, in app
api-server     raw_response = await run_endpoint_function(
api-server                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/routing.py", line 221, in run_endpoint_function
api-server     return await run_in_threadpool(dependant.call, **values)
api-server            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
api-server     return await anyio.to_thread.run_sync(func)
api-server            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
api-server     return await get_async_backend().run_sync_in_worker_thread(
api-server            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
api-server     return await future
api-server            ^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 976, in run
api-server     result = context.run(func, *args)
api-server              ^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/core_api/routes/ui/grid.py", line 417, in get_grid_ti_summaries
api-server     task_instances = list(get_node_sumaries())
api-server                      ^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/core_api/routes/ui/grid.py", line 387, in get_node_sumaries
api-server     node=serdag.dag.task_group,
api-server          ^^^^^^^^^^
api-server AttributeError: 'NoneType' object has no attribute 'dag'
api-server 2025-11-18T10:07:47.267201Z [error    [] No serialized dag found        [airflow.api_fastapi.core_api.routes.ui.grid] dag_id=<...my dag id...> loc=grid.py:104 version_id=UUID('019a937a-0aae-7efd-b793-392930b44c56') version_number=8
api-server INFO:     172.24.148.170:40090 - "GET /ui/grid/ti_summaries/<...my dag id...>/manual__2025-11-18T10%3A05%3A56%2B00%3A00 HTTP/1.1" 500 Internal Server Error
api-server ERROR:    Exception in ASGI application
api-server Traceback (most recent call last):
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api-server     result = await app(  # type: ignore[func-returns-value]
api-server              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/applications.py", line 1082, in __call__
api-server     await super().__call__(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
api-server     await self.middleware_stack(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
api-server     raise exc
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
api-server     await self.app(scope, receive, _send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 29, in __call__
api-server     await responder(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 130, in __call__
api-server     await super().__call__(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 46, in __call__
api-server     await self.app(scope, receive, self.send_with_compression)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
api-server     await self.app(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api-server     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api-server     raise exc
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api-server     await app(scope, receive, sender)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
api-server     await self.middleware_stack(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
api-server     await route.handle(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle
api-server     await self.app(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 78, in app
api-server     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api-server     raise exc
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api-server     await app(scope, receive, sender)
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
api-server     response = await f(request)
api-server                ^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/routing.py", line 308, in app
api-server     raw_response = await run_endpoint_function(
api-server                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/routing.py", line 221, in run_endpoint_function
api-server     return await run_in_threadpool(dependant.call, **values)
api-server            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
api-server     return await anyio.to_thread.run_sync(func)
api-server            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
api-server     return await get_async_backend().run_sync_in_worker_thread(
api-server            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
api-server     return await future
api-server            ^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 976, in run
api-server     result = context.run(func, *args)
api-server              ^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/core_api/routes/ui/grid.py", line 417, in get_grid_ti_summaries
api-server     task_instances = list(get_node_sumaries())
api-server                      ^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/core_api/routes/ui/grid.py", line 387, in get_node_sumaries
api-server     node=serdag.dag.task_group,
api-server          ^^^^^^^^^^
api-server AttributeError: 'NoneType' object has no attribute 'dag'
api-server INFO:     172.24.160.138:49844 - "GET /api/v2/version HTTP/1.1" 200 OK
api-server INFO:     172.24.160.138:49846 - "GET /api/v2/version HTTP/1.1" 200 OK

```

### How to reproduce

This error appeared after updating from 3.1.0 to 3.1.3.
After reverting back to the 3.1.0 - the error disappeared without any changes in the DAGs code.

### Operating System

linux amd64

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

official chart 1.18.0 deployed to AWS EKS.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mykola-shyshov** [comment]
any example to reproduce?

**Comment by ephraimbuddy** [comment]
Likely cause: https://github.com/apache/airflow/pull/58259. To be released in 3.1.4
