### ISSUE TITLE
AttributeError: module 'attr.validators' has no attribute 'min_len'

### ISSUE THREAD

**Issue by gabrielboehme-sf** [apache/airflow#28178]
### Apache Airflow version

2.5.0

### What happened

After I migrated from airflow 2.3.2 to 2.5.0, Im getting this error traceback, and all airflow (from a docker compose environment) are exiting. I can not even upgrade the db as is asked to do it by the logs.

This error seems to be from the attr package: the attrs package has the validators.min_len() method, not attr package.

This is the error traceback:
airflow-worker     | Traceback (most recent call last):
airflow-worker     |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
airflow-worker     |     sys.exit(main())
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/__main__.py", line 39, in main
airflow-worker     |     args.func(args)
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 51, in command
airflow-worker     |     func = import_string(import_path)
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 33, in import_string
airflow-worker     |     module = import_module(module_path)
airflow-worker     |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
airflow-worker     |     return _bootstrap._gcd_import(name[level:], package, level)
airflow-worker     |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
airflow-worker     |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
airflow-worker     |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
airflow-worker     |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
airflow-worker     |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
airflow-worker     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/celery_command.py", line 33, in <module>
airflow-worker     |     from airflow.executors.celery_executor import app as celery_app
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 52, in <module>
airflow-worker     |     from airflow.executors.base_executor import BaseExecutor, CommandType, EventBufferValueType, TaskTuple
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/executors/base_executor.py", line 29, in <module>
airflow-worker     |     from airflow.models.taskinstance import TaskInstance, TaskInstanceKey
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 69, in <module>
airflow-worker     |     from airflow.datasets import Dataset
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/datasets/__init__.py", line 25, in <module>
airflow-worker     |     @attr.define()
airflow-worker     |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/datasets/__init__.py", line 29, in Dataset
airflow-worker     |     uri: str = attr.field(validator=[attr.validators.min_len(1), attr.validators.max_len(3000)])
airflow-worker     | AttributeError: module 'attr.validators' has no attribute 'min_len'
airflow-worker exited with code 1

### What you think should happen instead

Airflow should start with no errors

### How to reproduce

Docker version:
Engine:
Version: 20.10.21
API version: 1.41 (minimum version 1.12)
Go version: go1.18.7
Git commit: 3056208
Built: Tue Oct 25 18:00:04 2022
OS/Arch: linux/amd64

Docker Compose version v2.12.2

### Operating System

Ubuntu 20.04 LTS

### Versions of Apache Airflow Providers

pip freeze from inside worker container
adal==1.2.7
aiofiles==0.8.0
aiohttp==3.8.3
aiosignal==1.3.1
alembic==1.8.1
amqp==5.1.1
anyio==3.6.2
apache-airflow==2.5.0
apache-airflow-providers-amazon==6.2.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==5.0.0
apache-airflow-providers-common-sql==1.3.1
apache-airflow-providers-docker==3.3.0
apache-airflow-providers-elasticsearch==4.3.1
apache-airflow-providers-ftp==3.2.0
apache-airflow-providers-google==8.6.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.2.0
apache-airflow-providers-http==4.1.0
apache-airflow-providers-imap==3.1.0
apache-airflow-providers-microsoft-azure==5.0.0
apache-airflow-providers-mysql==3.4.0
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-postgres==5.3.1
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.0
apache-airflow-providers-slack==7.1.0
apache-airflow-providers-sqlite==3.3.1
apache-airflow-providers-ssh==3.3.0
apispec==3.3.2
argcomplete==1.12.3
asgiref==3.5.2
asn1crypto==1.5.1
async-timeout==4.0.2
asynctest==0.13.0
attrs==20.3.0
Authlib==1.1.0
azure-batch==13.0.0
azure-common==1.1.28
azure-core==1.26.1
azure-cosmos==4.3.0
azure-datalake-store==0.0.52
azure-identity==1.12.0
azure-keyvault-secrets==4.6.0
azure-kusto-data==0.0.45
azure-mgmt-containerinstance==1.5.0
azure-mgmt-core==1.3.2
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-resource==21.2.1
azure-nspkg==3.0.2
azure-servicebus==7.8.1
azure-storage-blob==12.14.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-synapse-spark==0.7.0
Babel==2.5.0
backoff==1.10.0
backports.zoneinfo==0.2.1
bcrypt==3.1.4
beautifulsoup4==4.11.1
billiard==3.6.4.0
blinker==1.5
boto3==1.24.58
botocore==1.27.59
cached-property==1.5.2
cachelib==0.9.0
cachetools==4.2.2
cattrs==22.2.0
celery==5.2.7
certifi==2022.9.24
cffi==1.15.1
chardet==3.0.4
charset-normalizer==2.1.1
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
clickclick==20.10.2
cloudpickle==2.2.0
colorama==0.4.6
colorlog==4.8.0
commonmark==0.9.1
ConfigUpdater==3.1.1
connexion==2.14.1
cron-descriptor==1.2.32
croniter==1.3.8
cryptography==36.0.2
curlify==2.2.1
cycler==0.11.0
dask==2022.2.0
db-dtypes==1.0.4
decorator==5.1.1
Delorean==0.6.0
Deprecated==1.2.13
dill==0.3.6
distlib==0.3.6
distributed==2022.2.0
Django==3.2.8
django-braces==1.14.0
django-fernet-fields==0.6
dnspython==2.2.1
docker==6.0.1
docutils==0.19
elasticsearch==7.13.4
elasticsearch-dbapi==0.2.9
elasticsearch-dsl==7.4.0
email-validator==1.3.0
eventlet==0.33.2
exceptiongroup==1.0.4
facebook-business==14.0.0
filelock==3.8.0
Flask==2.2.2
Flask-AppBuilder==4.1.4
Flask-Babel==2.0.0
Flask-Caching==2.0.1
Flask-JWT-Extended==4.4.4
Flask-Login==0.6.2
Flask-Session==0.4.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.1
flower==1.2.0
frozenlist==1.3.3
fsspec==2022.11.0
future==0.16.0
gcloud-aio-auth==4.0.1
gcloud-aio-bigquery==6.1.2
gcloud-aio-storage==7.0.1
gevent==22.10.2
google-ads==15.0.0
google-api-core==2.0.1
google-api-python-client==2.39.0
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
google-cloud-aiplatform==1.16.1
google-cloud-appengine-logging==1.1.3
google-cloud-audit-log==0.2.4
google-cloud-automl==2.8.0
google-cloud-bigquery==2.34.4
google-cloud-bigquery-datatransfer==3.7.0
google-cloud-bigquery-storage==2.14.1
google-cloud-bigtable==1.7.3
google-cloud-build==3.9.0
google-cloud-compute==0.7.0
google-cloud-container==2.11.1
google-cloud-core==2.3.2
google-cloud-datacatalog==3.9.0
google-cloud-dataform==0.2.0
google-cloud-dataplex==1.1.0
google-cloud-dataproc==5.0.0
google-cloud-dataproc-metastore==1.6.0
google-cloud-dlp==1.0.2
google-cloud-kms==2.12.0
google-cloud-language==1.3.2
google-cloud-logging==3.2.1
google-cloud-memcache==1.4.1
google-cloud-monitoring==2.11.0
google-cloud-orchestration-airflow==1.4.1
google-cloud-os-login==2.7.1
google-cloud-pubsub==2.13.5
google-cloud-redis==2.9.0
google-cloud-resource-manager==1.6.0
google-cloud-secret-manager==1.0.2
google-cloud-spanner==1.19.3
google-cloud-speech==1.3.4
google-cloud-storage==2.6.0
google-cloud-tasks==2.10.1
google-cloud-texttospeech==1.0.3
google-cloud-translate==1.7.2
google-cloud-videointelligence==1.16.3
google-cloud-vision==1.0.2
google-cloud-workflows==1.7.1
google-crc32c==1.5.0
google-pasta==0.2.0
google-resumable-media==2.4.0
googleads==29.0.0
googleapis-common-protos==1.53.0
graphviz==0.20.1
greenlet==2.0.1
grpc-google-iam-v1==0.12.4
grpcio==1.51.1
grpcio-gcp==0.2.2
grpcio-status==1.48.2
gunicorn==20.1.0
h11==0.14.0
HeapDict==1.0.1
httpcore==0.16.2
httplib2==0.20.4
httpx==0.23.1
humanize==4.4.0
hvac==1.0.2
idna==2.10
importlib-metadata==4.13.0
importlib-resources==5.10.0
inflection==0.5.1
iniconfig==1.1.1
isodate==0.6.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==0.10.0
joblib==1.2.0
json-merge-patch==0.2
jsonpath-ng==1.5.3
jsonschema==4.17.3
kiwisolver==1.4.4
kombu==5.2.4
kubernetes==23.6.0
lazy-object-proxy==1.8.0
ldap3==2.9.1
linkify-it-py==2.0.0
locket==1.0.0
lockfile==0.12.2
looker-sdk==22.20.0
lxml==4.9.1
Mako==1.2.4
Markdown==3.4.1
markdown-it-py==2.1.0
MarkupSafe==2.1.1
marshmallow==3.19.0
marshmallow-enum==1.5.1
marshmallow-oneofschema==3.0.1
marshmallow-sqlalchemy==0.26.1
matplotlib==3.2.0
mdit-py-plugins==0.3.1
mdurl==0.1.2
msal==1.20.0
msal-extensions==1.0.0
msgpack==1.0.4
msrest==0.7.1
msrestazure==0.6.4
multidict==6.0.2
multiprocess==0.70.14
mypy-boto3-appflow==1.26.15
mypy-boto3-rds==1.26.17
mypy-boto3-redshift-data==1.26.0.post1
mysql-connector-python==8.0.31
mysqlclient==2.1.1
nox==2022.1.7
numpy==1.18.1
oauthlib==3.2.2
packaging==21.3
pandas==1.0.1
pandas-gbq==0.17.9
paramiko==2.7.1
partd==1.3.0
pathos==0.3.0
pathspec==0.9.0
patsy==0.5.3
pendulum==2.1.2
pkgutil_resolve_name==1.3.10
platformdirs==2.5.4
pluggy==1.0.0
ply==3.11
portalocker==2.6.0
pox==0.3.2
ppft==1.7.6.6
prison==0.2.1
prometheus-client==0.15.0
prompt-toolkit==3.0.33
proto-plus==1.18.1
protobuf==3.17.3
protobuf3-to-dict==0.1.5
psutil==5.9.4
psycopg2==2.9.5
psycopg2-binary==2.9.3
py==1.11.0
pyactiveresource==2.2.2
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycountry==20.7.3
pycparser==2.21
pydata-google-auth==1.4.0
Pygments==2.13.0
pyhcl==0.4.4
PyJWT==2.6.0
PyNaCl==1.5.0
pyodbc==4.0.35
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyrsistent==0.19.2
pytest==7.2.0
python-daemon==2.3.2
python-dateutil==2.8.2
python-dotenv==0.21.0
python-http-client==3.3.7
python-ldap==3.4.3
python-nvd3==0.15.0
python-slugify==7.0.0
pytz==2022.6
pytz-deprecation-shim==0.1.0.post0
pytzdata==2020.1
PyYAML==5.4.1
ratelimit==2.2.1
redis==3.5.3
redshift-connector==2.0.909
requests==2.25.0
requests-file==1.5.1
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
rfc3986==1.5.0
rich==12.6.0
rollbar==0.14.7
rsa==4.9
s3transfer==0.6.0
sagemaker==2.78.0
scikit-learn==0.24.2
scipy==1.7.1
scramp==1.4.4
sendgrid==6.8.1
setproctitle==1.3.2
ShopifyAPI==7.0.2
six==1.16.0
slack-sdk==3.19.4
smdebug-rulesconfig==1.0.1
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.44
sqlalchemy-bigquery==1.5.0
SQLAlchemy-JSONField==1.0.0
sqlalchemy-redshift==0.8.11
SQLAlchemy-Utils==0.38.3
sqlparse==0.4.3
sshtunnel==0.4.0
starkbank-ecdsa==2.2.0
statsd==4.0.1
statsmodels==0.11.1
swagger-ui-bundle==0.0.9
tabulate==0.9.0
tblib==1.7.0
tenacity==8.1.0
termcolor==2.1.1
text-unidecode==1.3
threadpoolctl==3.1.0
tomli==2.0.1
toolz==0.12.0
tornado==6.1
typing_extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
uamqp==1.6.3
uc-micro-py==1.0.1
unicodecsv==0.14.1
uritemplate==3.0.1
urllib3==1.26.13
vine==5.0.0
virtualenv==20.17.0
watchtower==2.0.1
wcwidth==0.2.5
websocket-client==1.4.2
Werkzeug==2.2.2
wrapt==1.14.1
WTForms==3.0.1
xmltodict==0.13.0
yarl==1.8.1
zeep==4.2.1
zict==2.2.0
zipp==3.11.0
zope.event==4.5.0
zope.interface==5.5.2

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Docker compose deployment with:
- airflow worker
- airflow scheduler
- airflow webserver
- airflow triggerer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
You did not perform the upgrade correctly. Airflow 2.5.0 requires attrs 22.1.0 or later, and the version in your environment is much too old.

**Comment by ogremagi4** [comment]
I have the same issue with attrs version 22.1.0 and airflow 2.5

Dagbag check of a task finishes with different results: sometimes it succeeds, sometimes fails. 
Not sure how to debug it

```
[2022-12-11T12:18:47.459+0000] {logging_mixin.py:137} INFO - [2022-12-11T12:18:47.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py
[2022-12-11T12:18:48.241+0000] {processor.py:753} INFO - DAG(s) dict_keys(['fill_locks']) retrieved from /home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py
[2022-12-11T12:18:48.305+0000] {logging_mixin.py:137} INFO - [2022-12-11T12:18:48.304+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-11T12:18:48.372+0000] {logging_mixin.py:137} INFO - [2022-12-11T12:18:48.372+0000] {dag.py:3423} INFO - Setting next_dagrun for fill_locks to 2022-12-11T12:00:00+00:00, run_after=2022-12-11T12:30:00+00:00
[2022-12-11T12:18:48.407+0000] {processor.py:175} INFO - Processing /home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py took 0.954 seconds
[2022-12-11T12:18:50.383+0000] {processor.py:153} INFO - Started process (PID=40112) to work on /home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py
[2022-12-11T12:18:50.384+0000] {processor.py:640} INFO - Processing file /home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py for tasks to queue
[2022-12-11T12:18:50.384+0000] {logging_mixin.py:115} INFO - [2022-12-11T12:18:50.384+0000] {dagbag.py:508} INFO - Filling up the DagBag from /home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py
[2022-12-11T12:18:51.098+0000] {logging_mixin.py:115} INFO - [2022-12-11T12:18:51.097+0000] {dagbag.py:321} ERROR - Failed to import: /home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py
Traceback (most recent call last):
  File "/home/airflow/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    if not self.has_logged:
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/airflow/airflow/dags/etls/new_warehouse/fill_locks.py", line 8, in <module>
    from airflow.decorators import task
  File "/home/airflow/airflow/venv/lib/python3.9/site-packages/airflow/decorators/__init__.py", line 21, in <module>
    from airflow.decorators.base import TaskDecorator
  File "/home/airflow/airflow/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 41, in <module>
    from airflow.datasets import Dataset
  File "/home/airflow/airflow/venv/lib/python3.9/site-packages/airflow/datasets/__init__.py", line 26, in <module>
    class Dataset:
  File "/home/airflow/airflow/venv/lib/python3.9/site-packages/airflow/datasets/__init__.py", line 29, in Dataset
    uri: str = attr.field(validator=[attr.validators.min_len(1), attr.validators.max_len(3000)])
AttributeError: module 'attr.validators' has no attribute 'min_len'
```
