### PR TITLE
Fix SparkKubernetesOperator deferrable mode launcher attribute error

### LINKED ISSUE #56291: Cannot run SparkKubernetesOperator in deferrable mode
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

See deployment details, but cncf-kubernetes provider version is 10.8.1, for info.

### Apache Airflow version

3.1.0

### Operating System

Official Airflow image: docker.io/apache/airflow:3.1.0-python3.12

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

I use helm with a custom image built via this Dockerfile:

```
FROM docker.io/apache/airflow:3.1.0-python3.12

USER root

# Copy requirements to working directory
COPY requirements.txt /var/airflow/requirements.txt

# Set the working directory in the container
WORKDIR /var/airflow


USER airflow

RUN pip install --upgrade pip

# Install the necessary dependencies
RUN pip install \
    --no-cache-dir \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.1.0/constraints-3.12.txt" \
    -r /var/airflow/requirements.txt
```

The requirements.txt file is:

```
apache-airflow[amazon,google,postgres,async,cncf.kubernetes,celery,slack,http,fab,standard,openlineage]==3.1.0
```

### What happened

I am using the `SparkKubernetesOperator` as follow:

```
full_reload_job = SparkKubernetesOperator(
        task_id="full_reload_job",
        namespace="spark-operator",
        application_file="spark_app/full_reload_job/spark_application_config.yml",
        kubernetes_conn_id="kubernetes_default",
        random_name_suffix=True,
        get_logs=True,
        reattach_on_restart=True,
        delete_on_termination=True,
        do_xcom_push=False,
        deferrable=True,
        retries=0,
        on_execute_callback=upload_spark_config_to_gcs,
    )
```

The job succeeds when `deferrable=False,` but fails when it is `True`.

The error I get is:

```
ERROR - Task failed with exception
AttributeError: 'SparkKubernetesOperator' object has no attribute 'launcher'

File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 920 in run
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1307 in _execute_task
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 1632 in resume_execution
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 956 in trigger_reentry
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 978 in _clean
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1013 in post_complete_action
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1056 in cleanup
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py", line 265 in process_pod_deletion
```

Any idea why this is happening? It was working fine in Airflow 2.11.0 and before.

### What you think should happen instead

The task should succeeds.

### How to reproduce

Run a SparkKubernetesOperator task in deferrable mode.

### Anything else

This issue https://github.com/apache/airflow/issues/55747 describes the same behavior but for a Snowflake operator. I suspect that this issue is not tied to a specific provider but is more generic (linked to how task are deferred maybe).

Another remark that might be important: I am using keda to autoscale the triggerer pod (as well as the worker pods), and the triggerer and worker pods downscale to 0 when there is nothing to execute.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by OmarFarooq908**
- Fix AttributeError: 'SparkKubernetesOperator' object has no attribute 'launcher'
- Add defensive checks in process_pod_deletion() and on_kill() methods
- Handle cases where launcher attribute is not available in deferrable mode
- Prevents crashes when process_pod_deletion() is called from trigger_reentry()
- Maintains backward compatibility when launcher is available
- Shows appropriate warning when launcher is not available

Fixes #56291

The issue occurs because in deferrable mode:
1. execute() sets self.launcher during _setup_spark_configuration()
2. execute() defers to a trigger via execute_async()
3. When trigger completes, trigger_reentry() calls _clean() -> cleanup()
4. cleanup() calls process_pod_deletion() but self.launcher is not available

This fix adds defensive checks to handle both scenarios:
- When launcher is available (normal execution)
- When launcher is not available (deferrable mode trigger_reentry)

Tested with full Airflow environment to ensure the fix works correctly.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Yet another discrepancy between deferrable and non-deferrable mode!

We already have many differences in behavior between executing the operator in deferrable mode and executing it in normal mode, and your fix here adds a new one — where we won’t support cleaning up the created pod if the task is executed in deferrable mode.  
A better solution would be to refactor the code and check what needs to be recreated (launcher, hook, etc.) to support deleting the pod after resuming the task **if it should be deleted**.

> if it should be deleted

If the user set `delete_on_termination=True` (which is the default value), they expect the driver pod to be deleted when the job finishes — regardless of the execution mode of the Airflow task.


A general note: to accept the PR as a fix for the bug, we expect a unit test that reproduces the issue without the fix/change, and that passes after applying the patch.

**Comment by OmarFarooq908** [comment]
> Yet another discrepancy between deferrable and non-deferrable mode!
> 
> We already have many differences in behavior between executing the operator in deferrable mode and executing it in normal mode, and your fix here adds a new one — where we won’t support cleaning up the created pod if the task is executed in deferrable mode. A better solution would be to refactor the code and check what needs to be recreated (launcher, hook, etc.) to support deleting the pod after resuming the task **if it should be deleted**.
> 
> > if it should be deleted
> 
> If the user set `delete_on_termination=True` (which is the default value), they expect the driver pod to be deleted when the job finishes — regardless of the execution mode of the Airflow task.
> 
> A general note: to accept the PR as a fix for the bug, we expect a unit test that reproduces the issue without the fix/change, and that passes after applying the patch.

@hussein-awala Thanks for the feedback! I've fixed the issues:  

- Both deferrable and non-deferrable modes now behave the same.  
- Pods are cleaned up properly when `delete_on_termination=True`.  
- `hook` and `launcher` are recreated as needed.  
- Added tests that reproduce the bug and confirm the fix.  

PR is ready for review! Let me know if anything else needs changing

**Comment by Ferdinanddb** [comment]
Hi there,

I allow myself to follow-up on this, do you think that this PR would fix the problem?

cc @hussein-awala , @romsharon98 : I assume you guys are quite busy, but may I ask you to have a look at this when you have a moment please?

Since I migrated to Airflow 3, I cannot use the `SparkKubernetesOperator` in deferrable mode anymore, and this is quite annoying as I have to use a worker slot and if my worker gets killed for some reason then I loose the track of the Spark job :/. Don't get me wrong: I don't want to be rude or anything!

**Comment by eladkal** [comment]
> I allow myself to follow-up on this, do you think that this PR would fix the problem?

I think it would be helpful for review if you test the code suggested in the PR and confirm if it actually solves the issue you experience. Reviews from community can speedup PR approval.

Note that if the code suggested in this PR solves your issue you can apply it to your deployment regardless if Airflow release it. This is provider code change and you can always subclass and apply the fix on your end.

**Comment by Ferdinanddb** [comment]
@eladkal You are right, I will test this fix!
